### ISSUE TITLE
Can read_pdf function return positions of table too?

### ISSUE THREAD

**Issue by meokbodizi** [chezou/tabula-py#102]
It would be great if tabula.read_pdf(f_pdf, multiple_tables=True, lattice=True) returns positions of each extracted table.

Thanks!

**Comment by chezou** [comment]
Since tabula-java JSON output has several extra data as `extraction_method`, `height`, `width`, `left`, `top`, you can get the position of a table via JSON format, while DataFormat format doesn't include the position.

Here is the example code: 

```py
# data.pdf is included in the repository.
In [5]: tables = read_pdf("./examples/data.pdf", output_format="json", page=2)

In [9]: top = tables[0]['top']

In [10]: left = tables[0]['left']

In [11]: bottom = tables[0]['height'] + top

In [12]: right = tables[0]['width'] + left

In [13]: top, bottom, left, right
Out[13]: (0.0, 528.8800048828125, 0.0, 564.8800048828125)
```

**Comment by meokbodizi** [comment]
@chezou thanks a lot!

**Comment by chezou** [comment]
@echo-ray Thanks for reporting. Unfortunately, JSON output field is defined by tabula-java. If you want it, could you raise an issue on [tabula-java issue](https://github.com/tabulapdf/tabula-java/issues)?

**Comment by echo-ray** [comment]
> @echo-ray Thanks for reporting. Unfortunately, JSON output field is defined by tabula-java. If you want it, could you raise an issue on [tabula-java issue](https://github.com/tabulapdf/tabula-java/issues)?

Thx for your reply~
I will ask them if they could add this, for the `page` attribute should be  used in the middle layer for the processing but not given in the final result. 
If they got any conclusion, I will report back here : )

**Comment by omkar-kumbhar** [comment]
Why does the json output always start with 0,0 ? Is it because of the extraction method? 
eg: 

[
  {
    "extraction_method": "stream",
    "top": 0.0,
    "left": 0.0,
    "width": 807.5700073242188,
    "height": 400.4200134277344,
    "data": [
      [
       ...
_____________________________

**Comment by himadrijena143** [comment]
Is table reading from PDF is only applicable where we can editable(means we can manually copy the table data to excel file also) PDF?

If we can't copy the table data in PDF to excel manually, does it mean we can't read the same using Tabula.
