### ISSUE TITLE
Multiple issues while i read the PDF

### ISSUE THREAD

**Issue by isaaccwb** [chezou/tabula-py#103]
# Summary of your issue
Hello, I tried to read a pdf via tabula-py however i was experiencing multiple issues.

# Environment

- [ ] Paste the output of `python --version` command on your terminal: ?
Enthought Canopy Python 2.7.13 | 64-bit |

- [ ] Paste the output of `java -version` command on your terminal: ?
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`

showed below when i ran java -h

??: java [-options] class [args...]
           (????)
   ?  java [-options] -jar jarfile [args...]
           (?? jar ??)
????:
    -d32          ?? 32 ?????? (?????)
    -d64          ?? 64 ?????? (?????)
    -server       ?? "server" VM
                  ??? VM ? server.

    -cp <??? zip/jar ?????????>
    -classpath <??? zip/jar ?????????>
                  ?? ; ??????JAR ???? ZIP ????????????
    -D<name>=<value>
                  ??????
    -verbose:[class|gc|jni]
                  ????????
    -version      ?????????
    -version:<value>
                  ??: ????????????????????
                  ???????????
    -showversion  ?????????
    -jre-restrict-search | -no-jre-restrict-search
                  ??: ????????????????????
                  ????????/??????? JRE
    -? -help      ???????
    -X            ??????????
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  ????????????
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  ????????????
    -esa | -enablesystemassertions
                  ??????
    -dsa | -disablesystemassertions
                  ??????
    -agentlib:<libname>[=<options>]
                  ??????????? <libname>??? -agentlib:hprof
                  ???? -agentlib:jdwp=help ? -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  ???????????????????
    -javaagent:<jarpath>[=<options>]
                  ?? Java ???????????? java.lang.instrument
    -splash:<imagepath>
                  ?????????????
??? http://www.oracle.com/technetwork/java/javase/documentation/index.html ???????

- [ ] Write your OS and it's version: ? 
WIndows 10 X64

Providing PDF would be really helpful to resolve the issue.
http://www.hkexnews.hk/listedco/listconews/SEHK/2018/0815/LTN20180815893_C.PDF

Provide your information to reproduce the issue.
## Code:
Original code:

import tabula
import pandas as pd
import requests
import distro

filename="C:\Users\isaac\Downloads\LTN20180815893_C.PDF" #I saved the PDF in my downloads folder
pageno=1

df=read_pdf(filename, pages=pageno, pandas_options={'header':None} )
df.fillna("")

Result:
NameError: name 'read_pdf' is not defined 

Resolution:
I added from tabula import read_pdf to the code

import tabula
import pandas as pd
import requests
import distro

from tabula import read_pdf
filename="C:\Users\isaac\Downloads\LTN20180815893_C.PDF"
pageno=1
df=read_pdf(filename, pages=pageno, pandas_options={'header':None} )
df.fillna("")

After this, I run again and have the below error result:
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 0: invalid start byte

Resolution: type chcp 65001 in CMD
and add below code
 java_options="-Dfile.encoding=UTF8" like this

import tabula
import pandas as pd
import requests
import distro

from tabula import read_pdf

filename="C:\Users\isaac\Downloads\LTN20180815893_C.PDF"
pageno=1

df=read_pdf(filename,java_options="-Dfile.encoding=UTF8", pages=pageno, pandas_options={'header':None} )
df.fillna("")

After I ran this, I have another issue result on below:
%run "c:\users\isaac\appdata\local\temp\tmp5te0fa.py"
9æ 04, 2018 12:37:24 ä¸å org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³è¨: To get higher rendering speed on JDK8 or later,
9æ 04, 2018 12:37:24 ä¸å org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³è¨:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
9æ 04, 2018 12:37:24 ä¸å org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³è¨:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")

Expectation:
I expect to see a result like below page (PDF page1)
https://hk.thenewslens.com/article/102379#&gid=1&pid=1

Please help!
Thanks

**Comment by chezou** [comment]
Could you write a more specific issue? The article you mentioned seems just to copy and paste into Excel/Google Spreadsheet from CSV, generated by tabula-py. So, you can't get some output like the image in the article just running Python.

If you state the following output is the issue, it is just a tabula-java warning, and you can ignore.

```
9æ�� 04, 2018 12:37:24 ä¸�å�� org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³�è¨�: To get higher rendering speed on JDK8 or later,
9æ�� 04, 2018 12:37:24 ä¸�å�� org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³�è¨�: use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
9æ�� 04, 2018 12:37:24 ä¸�å�� org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
è³�è¨�: or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
```

If you want to look the output through running your saved file, you have to write `print(df)`, or you can use Jupyter notebook or Python REPL. You want to output CSV, you have to write `df.to_csv("output.csv")`. Then you can import the CSV to Excel/Google Spreadsheet.

If you have any specific issue around tabula-py, please comment. If you want to know how to regenerate the image like the article, please ask on the website or StackOverflow.

**Comment by isaaccwb** [comment]
Thanks ! I am not generating a CSV export but using tabula.py to extract/display the PDF table

As i have posted (the code), i experienced three consecutive issues:

1:name 'read_pdf' is not defined -> I have added code from tabula import read_pdf to resolve
2: And then I experienced UnicodeDecodeError: 'utf8' issue -> I have follow the earlier post to  chcp 65001 and added code java_options="-Dfile.encoding=UTF8" to resolve.
3: Is the tabula-java warning you have explained. However, there is no resolve after I ran this code with this warning.

THank you

**Comment by chezou** [comment]
First of all, tabula-py is a software for extracting table from PDF into DataFrame, which is Python's table manipulation format or convert into CSV. If you want just to extract table and not familiar with Python, you can use [tabula](https://schoolofdata.org/extracting-data-from-pdfs/), which is GUI based software.

Comments on your issues:

> 1:name 'read_pdf' is not defined -> I have added code from tabula import read_pdf to resolve

This is not a tabula-py issue, original article code's issue. It should be work as follows:

```py
from tabula import read_pdf
import pandas as pd

filename="C:\Users\isaac\Downloads\LTN20180815893_C.PDF"
pageno=1

df=read_pdf(filename, pages=pageno, pandas_options={'header':None} )
df.fillna("")
```

> 2: And then I experienced UnicodeDecodeError: 'utf8' issue -> I have follow the earlier post to chcp 65001 and added code java_options="-Dfile.encoding=UTF8" to resolve.

Sounds strange. By default, tabula-py will set `-Dfile.encoding=UTF8`, while you need to execute `chcp 65001` on your command prompt. https://github.com/chezou/tabula-py/blob/c4b2d8373babf10f55724e7376ee2b09dde3bb2c/tabula/wrapper.py#L93

Anyway, requiring `chcp` is a known issue for Windows and [it has been documented](https://github.com/chezou/tabula-py#i-got--character-with-result-on-windows-how-can-i-avoid-it).

> 3: Is the tabula-java warning you have explained. However, there is no resolve after I ran this code with this warning.

You don't need to care tabula-java warning if you are not interested in to figure out it.

**Comment by isaaccwb** [comment]
Great thanks for your suggestion!
