### ISSUE TITLE
Allow binary files to be used in wrapper

### ISSUE THREAD

**Issue by johnny-longneck** [chezou/tabula-py#104]
**Is your feature request related to a problem? Please describe.**

I am writing a module for odoo to import PDFs and process it with tabula-py (great work)
I noticed that Odoo saves all uploaded files as binary in the database. Tabula-py requires the passed file to be a string and a file on the disk. 

So I need to convert the binary to a file, safe it, use tabula and then delete the file.

**Describe the solution you'd like**
I would like to use wrapper.read_pdf(binaryfile)

**Comment by chezou** [comment]
I think `read_pdf` aims to compatible with `pandas.read_pdf()` for future. Does it work for you with `tabula.read_pdf(BytesIO(binaryfile))` ? 

https://stackoverflow.com/questions/47392105/using-bytesio-in-pandas-read-csv

If it doesn't work with `BytesIO`, please tell me (I've never tried before). Sending PR is welcome 😄

**Comment by johnny-longneck** [comment]
Hey. It is not working with 'BytesIO' . I get the error execv expects parameter to be a string. There needs to be some adjustments in the wrapper. =)

**Comment by chezou** [comment]
Ah ha, so we need handling BytesIO. I'll add this feature on road map, but your contribution is welcome ;)

**Comment by chezou** [comment]
@johnny-longneck I'd like to confirm what `binaryfile` is. Is it `bytes` type Python object? If so, handling bytes object within tabula-py has an issue.

With Python 3 `bytes` object can be distinguished with `str` object, while Python 2 `bytes` object is the alias of `str`. So it's hard to handle bytes object for Python 2.

**Comment by johnny-longneck** [comment]
The environment I work is Python 2.7 based for now. I got my workaround with this issue writing directly a file to disk. So I got that going for me which is nice.

Seems like it won't be possible in Python 2. If you could add it as feature for Python 3 later, it is okay enough. We will switch to Python 3 in 1 year at last.
