### ISSUE TITLE
Another CalledProcessError

### ISSUE THREAD

**Issue by hengkokchin** [chezou/tabula-py#107]
# Summary of your issue
Installed tabula-py, it worked for awhile. Not sure what I did, then it stopped working.

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

```py
Python version:
    3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Java version:
    java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
tabula-py version: 1.1.1
platform: Windows-10-10.0.14393-SP0
uname:
    uname_result(system='Windows', node='SG01NB-6900288', release='10', version='10.0.14393', machine='AMD64', processor='Intel64 Family 6 Model 78 Stepping 3, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
    
None
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.
- [ ] Paste the output of `python --version` command on your terminal:
- [ ] Paste the output of `java -version` command on your terminal:
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

Providing PDF would be really helpful to resolve the issue.

- [x] (Optional, but really helpful) Your PDF URL:

I am just using the sample 'data.pdf' from your 'examples' folder.

# What did you do when you faced the problem?

I am running using JupyterLab.

After reading through the past issues related to CalledProcessError, I have tried:
- uninstalling and installing tabula again using
```
'pip install git+https://github.com/chezou/tabula-py'
```
- putting the pdf file in the same folder
- EDIT: after putting the .jar file in the same folder, tried to run via command prompt using
```
Works
java -jar tabula-1.0.2-jar-with-dependencies.jar --pages 1 --guess data.pdf
java -jar "tabula-1.0.2-jar-with-dependencies.jar" --pages 1 --guess "data.pdf"

Doesn't work
java -jar 'tabula-1.0.2-jar-with-dependencies.jar' --pages 1 --guess 'data.pdf'
```

## Code:

```
import tabula

df = tabula.read_pdf('data.pdf')
df
```

## Expected behavior:
Prints out the dataframe containing the tables in 'data.pdf'

## Actual behavior:

```
CalledProcessError                        Traceback (most recent call last)
<ipython-input-9-7350c28d9605> in <module>()
      5 import time
      6 
----> 7 df = tabula.read_pdf('data.pdf')
      8 df

C:\anaconda3\envs\PythonOnly\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     83         kwargs (dict):
     84             Dictionary of option for tabula-java. Details are shown in `build_options()`
---> 85 
     86     Returns:
     87         Extracted pandas DataFrame or list.

C:\anaconda3\envs\PythonOnly\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

C:\anaconda3\envs\PythonOnly\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    416         if check and retcode:
    417             raise CalledProcessError(retcode, process.args,
--> 418                                      output=stdout, stderr=stderr)
    419     return CompletedProcess(process.args, retcode, stdout, stderr)
    420 

CalledProcessError: Command '['java', '-jar', 'C:\\anaconda3\\envs\\PythonOnly\\lib\\site-packages\\tabula\\tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', 'data.pdf']' returned non-zero exit status 1.
```

EDIT: I executed the same code (placed in a .py file) in a command prompt
```
import tabula

df = tabula.read_pdf('data.pdf')
print(df)
```
and it works! But how do I get it to work in JupyterLab?

**Comment by chezou** [comment]
@hengkokchin Just confirmation. Does it work to point absolute path? I guess relative path could be unexpected with JupyterHub. Another possibility for Windows is existence of space. If you can try master branch version of tabula-py, you can path file like object or path
ib object instead of path. It seems your tabula-py isn't neither latest pypi version nor master branch version. The master branch version might be helpful for your issue.

see also: 
https://github.com/chezou/tabula-py/blob/master/tests/test_read_pdf_table.py#L51
https://github.com/chezou/tabula-py/blob/master/tests/test_read_pdf_table.py#L51

**Comment by hengkokchin** [comment]
Hi @chezou, sorry for the late reply. I went to work on something else.

Anyway, I tried running again the same codes on JupyterLab and now it works. I didn't change anything. Hmm, I guess its one of those 'restart-and-it-will-work' kind of issue (I experienced it with my Oracle 12c too). 

Thank you for your help! I will close this issue.
