### ISSUE TITLE
Add a "Try me on Binder" button 

### ISSUE THREAD

**Issue by pdehaye** [chezou/tabula-py#108]
**Describe the solution you'd like**
I would like there to be a button on the Github page "Try on Binder"
(see bottom here: https://mybinder.org/ )

**Describe alternatives you've considered**
This is a new type of service, and it's really nice to have it directly in the notebook. 

**Additional context**
MyBinder allows to configure a minimal virtual machine running a Jupyter notebook. So one could set up a link starting a jupyter notebook with an example of how to use tabula. It makes it much easier to convince potential users of the value.

**Comment by chezou** [comment]
Thanks for suggesting mybinder. I tried it, but tabula-py didn't work because of lacking java.

**Comment by chezou** [comment]
@pdehaye Sorry for the late response. I'm not sure how to introduce binder, but I'd be welcome your PR for that!
