### ISSUE TITLE
 How can I distinguish between two tables on a page by tabula, or read the table by paragraph?

### ISSUE THREAD

**Issue by liaoxuegithup** [chezou/tabula-py#116]
THE ISSUE TRACKER IS NOT FOR QUESTIONS.

DO NOT CREATE A NEW ISSUE TO ASK A QUESTION.

IF YOU ARE HAVING PROBLEMS WITH YOUR TABULA-PY CODE, DO NOT ASK A QUESTION HERE.

Tens of thousands of TypeScript questions have been asked and answered on StackOverflow; see https://stackoverflow.com/search?q=tabula-py . You can ask questions there or on other websites.

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.

**Comment by liaoxuegithup** [comment]
How can I distinguish between two tables on a page by tabula, or read the table by paragraph?
