### ISSUE TITLE
Use both lattice and columns options

### ISSUE THREAD

**Issue by jscottNRG** [chezou/tabula-py#117]
**Is your feature request related to a problem? Please describe.**
Lattice=True does not work with a specific document because the table does not have visible vertical column lines.  I'm using area and columns options to specify the portion of the page to consider and the x coordinates for the column boundaries, which works well.  However, I think word wrapping in the cells is an issue, and each row is split into multiple rows.

**Describe the solution you'd like**
I'd like to use the lattice option to allow tabula to detect row boundaries, while also using the columns option to specify where the column boundaries are.  I'm open to alternatives that would achieve what I need, though.

**Describe alternatives you've considered**
I've tried using just the lattice option, which works as designed to detect rows, but combines all columns.  I.e. I get an extracted dataframe that is a single column with the correct number of rows.  If I use the columns option instead of lattice, I get the right number of columns but a lot of extra rows.

**Additional context**
Python 3.6.5
Java 1.8.0_181

PDF document I'm working on is here:
[Projects.pdf](https://github.com/chezou/tabula-py/files/2461516/Projects.pdf)

lattice option method:
![lattice option](https://user-images.githubusercontent.com/44001639/46687240-9ee40f00-cbb7-11e8-809e-97369a4bfdf4.png)

columns option method:
![columns option](https://user-images.githubusercontent.com/44001639/46687243-a3102c80-cbb7-11e8-922c-1e1775e36b03.png)

**Comment by chezou** [comment]
Thanks for your request. I confirmed tabula-java can't handle both columns option and lattice option at once.

```
$ java -jar tabula-1.0.2-jar-with-dependencies.jar -a 145,25,695,1195 -c 156,252,364,811,909,1019 -l Projects.pdf
```

It should be a tabula-java enhancement, so could you raise your issue on [tabula-java repo](https://github.com/tabulapdf/tabula-java/issues?q=is%3Aopen+is%3Aissue)? Or AFAIK, [pdfplumber](https://github.com/jsvine/pdfplumber) has a feature to select lattice only for column/row.

**Comment by jscottNRG** [comment]
Will do, thanks @chezou !

**Comment by chezou** [comment]
Close this issue until tabula-java will implement this feature.
