### ISSUE TITLE
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed

### ISSUE THREAD

**Issue by nileshchakraborty** [chezou/tabula-py#120]
# Summary of your issue
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed

# Environment
Pycharm
Python 2.7

Nov 02, 2018 4:24:29 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO: To get higher rendering speed on JDK8 or later,
Nov 02, 2018 4:24:29 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
Nov 02, 2018 4:24:29 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.rendering.CIDType0Glyph2D getPathForCharacterCode
WARNING: No glyph for 45 (CID 002d) in font HiddenHorzOCR
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.rendering.CIDType0Glyph2D getPathForCharacterCode
WARNING: No glyph for 126 (CID 007e) in font HiddenHorzOCR
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.rendering.CIDType0Glyph2D getPathForCharacterCode
WARNING: No glyph for 32 (CID 0020) in font HiddenHorzOCR
Nov 02, 2018 4:24:30 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
