### ISSUE TITLE
read_pdf returns None on my Linux only 

### ISSUE THREAD

**Issue by nalsabhan** [chezou/tabula-py#125]
# Summary of your issue
I have moved from Mac to Linux mint. I tried to run the read_pdf and every attempt results in a dataframe containing "None". I have not seen similar issue online.  

# Environment

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

```
If not possible toPython version:
    2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0]
Java version:
    openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)
tabula-py version: 1.3.1
platform: Linux-4.4.0-21-generic-x86_64-with-debian-stretch-sid
uname:
    ('Linux', 'nawaf', '4.4.0-21-generic', '#37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016', 'x86_64', 'x86_64')
linux_distribution: (u'Ubuntu', u'16.04', u'Xenial Xerus')
mac_ver: ('', ('', '', ''), '') execute `tabula.environment_info()`, please answer following questions manually.

```
- [x] Paste the output of `python --version` command on your terminal: ?
`Python 2.7.15 :: Anaconda, Inc.`

- [x] Paste the output of `java -version` command on your terminal: ?
```
openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)
```

- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`
```
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
    -zero	  to select the "zero" VM
    -jamvm	  to select the "jamvm" VM
    -dcevm	  to select the "dcevm" VM
                  The default VM is server,
                  because you are running on a server-class machine.
$PATH
bash: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/home/nalsabhan/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games: No such file or directory
```

- [x] Write your OS and it's version: ?
`Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016`
- [x] (Optional, but really helpful) Your PDF URL: ?
https://www.tsu.ge/data/file_db/faculty_social_political/B2-nimushi.pdf

# What did you do when you faced the problem?

Tested multiple pdf files with text in them. Tried to update JAVA and made sure it is in the path 

## Example code:

```
import tabula as tb
df = tb.read_pdf("pdfs/test.pdf", pages = [3])
print df
```

## Output:

```
None
```

## What did you intend it to be?
I expected a table with text scattered in it.

**Comment by nalsabhan** [comment]
updated bullet-points

**Comment by nalsabhan** [comment]
@chezou thank you for the prompt reply. I have added a link to the test pdf file I tried.

**Comment by chezou** [comment]
If you want to handle PDF more manually, I'd recommend to use PDFplumber. https://github.com/jsvine/pdfplumber

Feel free to reopen if there's any specific questions on tabula-py.
