### ISSUE TITLE
Problem when specifying area in percentage format

### ISSUE THREAD

**Issue by Dip98** [chezou/tabula-py#128]
THIS PROBLEM DOES NOT OCCUR WHEN I SPECIFY THE AREA IN COORDINATE FORMAT.

On running this code:

import tabula
df = tabula.read_pdf(input_path = "D:/Code/PDF_data_extract/New Purchase order 4500663456 from SSSL.pdf", output_format = "dataframe", guess = False, relative_area = True, area = [10,10,10,10], stream = True)

I am getting this error:

CalledProcessError                        Traceback (most recent call last)
<ipython-input-34-1ef6a9d3dcab> in <module>
----> 1 df = tabula.read_pdf(input_path = "D:/Code/PDF_data_extract/New Purchase order 4500663456 from SSSL.pdf", output_format = "dataframe", guess = False, relative_area = True, area = [10,10,10,10], stream = True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
    106 
    107     try:
--> 108         output = subprocess.check_output(args)
    109 
    110     except FileNotFoundError as e:

~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    387 
    388     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 389                **kwargs).stdout
    390 
    391 

~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    479         if check and retcode:
    480             raise CalledProcessError(retcode, process.args,
--> 481                                      output=stdout, stderr=stderr)
    482     return CompletedProcess(process.args, retcode, stdout, stderr)
    483 

CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\dip.patel\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tabula\\tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--area', '%10,10,10,10', '--stream', 'D:/Code/PDF_data_extract/New Purchase order 4500663456 from SSSL.pdf']' returned non-zero exit status 1.

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
