### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by vivek1994** [chezou/tabula-py#138]
# Summary of your issue
I received CalledProcessError when trying to read a pdf file.
# Environment
* python --3.7
* java -- 1.8
* MAC

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-jar', '/anaconda3/lib/python3.7/site-packages/tabula/tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', '--format', 'JSON', '/Users/shivaswaroop/Downloads/MLC/PDF2XL/250.pdf']' returned non-zero exit status 1.

```py
# paste output of `tabula.environment_info()`
ython version:
    3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Java version:
    java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
tabula-py version: 1.3.1
platform: Darwin-18.2.0-x86_64-i386-64bit
uname:
    uname_result(system='Darwin', node='shivas-MacBook-Air.local', release='18.2.0', version='Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64', machine='x86_64', processor='i386')
linux_distribution: ('Darwin', '18.2.0', '')
mac_ver: ('10.14.1', ('', '', ''), 'x86_64')

```

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
