### ISSUE TITLE
Tabula app is able to read columns with value equal to "N/A" as such, while tabula-py converts it into "NaN"

### ISSUE THREAD

**Issue by papagala** [chezou/tabula-py#139]
Tabula app is able to read columns with value equal to "N/A" as such, while tabula-py converts it into "NaN"

# Environment

Python version:
    3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Java version:
    java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
tabula-py version: 1.3.1
platform: Windows-7-6.1.7601-SP1

# What did you do when you faced the problem?

I extracted the text using tabula app which successfully outputs columns with value = N/A while tabula-py converts the same output into NaN

## Example code:

tabula.read_pdf_with_template("file.pdf","template.json",pandas_options={'header': None},guess=False)

## Output:

Tabula app outputs 

R |   | N/A | RES | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Tabula-py

 R      NaN         NaN        RES  0.00000000  0.00000000  0.00000000                                         0.00000000           0.00000000  0.00000000 

## What did you intend it to be?

R |   | N/A | RES | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000 | 0.00000000
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

tHANKS!

**Comment by chezou** [comment]
it's padans's `read_csv` default behavior. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

You can set na_values option for pandas_option to avoid conversion.

> na_values : scalar, str, list-like, or dict, optional
> Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. By default > the following values are interpreted as NaN: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.

**Comment by papagala** [comment]
Please resolve this issue. Even though I was not able to fix it with exactly what you suggested, I used the link you provided to get where I needed to go. **The option in bold was the one that resolved my problem**

keep_default_na : bool, default True
Whether or not to include the default NaN values when parsing the data. Depending on whether na_values is passed in, the behavior is as follows:

If keep_default_na is True, and na_values are specified, na_values is appended to the default NaN values used for parsing.
If keep_default_na is True, and na_values are not specified, only the default NaN values are used for parsing.
If keep_default_na is False, and na_values are specified, only the NaN values specified na_values are used for parsing.
**If keep_default_na is False, and na_values are not specified, no strings will be parsed as NaN.**

**Comment by chezou** [comment]
Ah, I missed that option. So if you want to avoid parsing "N/A" value, you should pass both options; keep_default_na and na_values.

I guess you've already done by setting keep_default_na=True, don't you? 

Technically, it is pandas option issue and it'd be nice if we could add FAQ for tabula-py document.

**Comment by chezou** [comment]
Here is the example for `pandas.read_csv`. 

```
In [1]: fpath = "test.csv"

In [2]: import pandas as pd

In [3]: pd.read_csv(fpath)
Out[3]:
   a    b    c
0  1  NaN  2.0
1  3  4.0  NaN

In [4]: df1 = pd.read_csv(fpath)

In [5]: df1
Out[5]:
   a    b    c
0  1  NaN  2.0
1  3  4.0  NaN

In [6]: df2 = pd.read_csv(fpath, keep_default_na=False)

In [7]: df2
Out[7]:
   a    b    c
0  1  N/A    2
1  3    4  nan

In [8]: !cat test.csv
a,b,c
1,N/A,2
3,4,nan

In [9]: df3 = pd.read_csv(fpath, keep_default_na=False, na_values=['nan'])

In [10]: df3
Out[10]:
   a    b    c
0  1  N/A  2.0
1  3    4  NaN
```

You can use `pandas_option` for tabula-py like:

```py
read_pdf(pdf_path, pandas_option: {"keep_default_na": False, "na_values"=['nan']})
```

I don't have an example pdf for it, but I believe this should resolve the issue. Feel free to reopen if there still is a problem.
