### ISSUE TITLE
Problems with the module extracting two or more tables

### ISSUE THREAD

**Issue by edsilvaf** [chezou/tabula-py#142]
[example.pdf](https://github.com/chezou/tabula-py/files/3061284/example.pdf)
[example2.pdf](https://github.com/chezou/tabula-py/files/3061288/example2.pdf)

The trouble is that the module tends to have failure when i try to extract multiple tables from pdf files. Sometimes doesn´t appear the entire information or in another times the data is messy or is it my mistake in extracting tables.
Kinds Regards!
import tabula
from tabula import read_pdf
import pandas as pd
a = read_pdf(r"C:\Users\Emege\Downloads\example.pdf", guess = False,
encoding = "utf-8" ,output_format = "csv")
a.to_csv("a.csv", encoding = "utf-8")

ps: Let me know if you need some more information.

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
