### ISSUE TITLE
Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'

### ISSUE THREAD

**Issue by scut-salmon** [chezou/tabula-py#143]
has value '1.6', but '1.3' is required.
Error: could not find java.dll
Error: could not find Java 2 Runtime Environment.

My Java vesion is 
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
