### ISSUE TITLE
Error: Error: End-of-File, expected line / returned non-zero exit status 1

### ISSUE THREAD

**Issue by AngusWR** [chezou/tabula-py#144]
# Summary of your issue
When attempting to read_pdf I get the following error:

> Error: Error: End-of-File, expected line
> Error:
> Traceback (most recent call last):
>   File "C:\Users\orang\Desktop\westpac webscrape\testing00000000.py", line 8, in <module>
>     df = tabula.read_pdf(url, multiple_tables=True, pages='all', lattice=True, guess=False)
>   File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\tabula\wrapper.py", line 108, in read_pdf
>     output = subprocess.check_output(args)
>   File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\orang\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\tabula\\tabula-1.0.2-jar-with-dependencies.jar', '--pages', 'all', '--format', 'JSON', '--lattice', '20532.pdf']' returned non-zero exit status 1.

# Environment
Python 3.6.7
tabula-py 1.3.1
Windows 10

Write and check your environment. Please paste outputs of specific commands if required.

# paste output of `tabula.environment_info()`

> Python version:
>     3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
> Java version:
>     java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
> Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)
> tabula-py version: 1.3.1
> platform: Windows-10-10.0.17763-SP0
> uname:
>     uname_result(system='Windows', node='LAPTOP-ANGUS', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
> linux_distribution: ('', '', '')
> mac_ver: ('', ('', '', ''), '')

Providing PDF would be really helpful to resolve the issue.

- Your PDF URL:
[https://www.suncorp.com.au/content/dam/suncorp/bank/documents/product-information/home-lending-rate-guide.pdf](https://www.suncorp.com.au/content/dam/suncorp/bank/documents/product-information/home-lending-rate-guide.pdf)

Provide your information to reproduce the issue.

## Code:

```
import tabula
import pandas as pd

# suncorp
url = 'https://www.suncorp.com.au/content/dam/suncorp/bank/documents/product-information/home-lending-rate-guide.pdf'
df = tabula.read_pdf(url, multiple_tables=True, pages='all', lattice=True, guess=False)
print(df)
```

## Expected behavior:
Return a dataframe as it does correctly with another URL I am using: https://www.commbank.com.au/content/dam/commbank/personal/apply-online/download-printed-forms/home-loan-update-002842.pdf

## Actual behavior:
Error

This is my first time using the tabula-py library, so I apologise if I missed something obvious or am doing something wrong.

**Comment by chezou** [comment]
Thanks for reporting the issue! I also reproduced the error.

Since the host denies accessing from Python-urllib, the PDF downloaded by tabula-py becomes 0-byte file.

Unfortunately, tabula-py doesn't have a way to set user-agent, so the current workaround is to download the PDF yourself, i.e., your Python script or your browser.

**Comment by AngusWR** [comment]
Thanks for such a fast response, have used the workaround for now!

```
import requests
session = requests.Session()
session.headers.update({'User-Agent': 'Mozilla/5.0'})
url = 'https://www.suncorp.com.au/content/dam/suncorp/bank/documents/product-information/home-lending-rate-guide.pdf'
r = session.get(url)

file_path = 'webscrape_temp.pdf'
with open(file_path, 'wb') as f:
    f.write(r.content)

import tabula
import pandas as pd
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_columns', None)

# suncorp
df = tabula.read_pdf(file_path, multiple_tables=True, pages='all', lattice=True, guess=False)
print(df)

import os
os.remove(file_path)
```
