### ISSUE TITLE
Unable to execute my script from executable

### ISSUE THREAD

**Issue by zhongche** [chezou/tabula-py#149]
I created a script to extract data from a pdf. When I run my program through Jupyter-notebook and from the cmd, it works perfectly. After converting it to executable with pyinstaller, I get this error:

`Error: Unable to access jarfile E:\Users\paulhong\AppData\Local\Temp\_MEI175522\tabula\tabula-1.0.2-jar-with-dependencies.jar`
`Error:`
`Traceback (most recent call last):`
`  File "test.py", line 115, in <module>`

`  File "test.py", line 32, in extractDataDik`
`    tempDf = tabula.read_pdf(file, area = (72, 252, 115.2, 352.8), guess=False, pages='1')`
`  File "site-packages\tabula\wrapper.py", line 108, in read_pdf`
`  File "subprocess.py", line 395, in check_output`
`  File "subprocess.py", line 487, in run`
`subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'E:\\Users\\paulhong\\AppData\\Local\\Temp\\_MEI175522\\tabula\\tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--area', '72,252,115.2,352.8', 'E:\\Users\\paulhong\\Desktop\\Purchase Order 2\\SKM_C45819060508450 (003).pdf']' returned non-zero exit status 1.
[47140] Failed to execute script test`

I cannot find the folder _MEI175522 in the given path.
How should I fix this issue?

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
