### ISSUE TITLE
Tabula failing to extract numerical data from PDF tables

### ISSUE THREAD

**Issue by richeekawasthi** [chezou/tabula-py#150]
So I've been trying to extract some tables containing financial information in PDFs using tabula.
However, I noticed that while Tabula successfully extracts the cells containing textual data, it fails to extract data from cells containing numerical data. Has anyone else faced this issue and how was this resolved?

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
