### ISSUE TITLE
tabula has no attribute 'read_pdf' - in VSCode.

### ISSUE THREAD

**Issue by BruceJi7** [chezou/tabula-py#153]
# Summary of your issue

From VSCode, none of the tabula methods and attributes work.
It seems like they work from anaconda prompt, though.
```
Traceback (most recent call last):
  File "c:\Users\User\.spyder-py3\JacobPDF\PDFTableToExcel.py", line 11, in <module>
    df = tabula.read_pdf("./Import/Ground Floor Finishes Plan.pdf", pages='all')
AttributeError: module 'tabula' has no attribute 'read_pdf'
```
# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
```
Python version:
    3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode)
tabula-py version: 1.3.1
platform: Windows-10-10.0.17134-SP0
uname:
    uname_result(system='Windows', node='LAPTOP', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
```
# What did you do when you faced the problem?

I pasted in the example code from the docs and tried it.
I checked that I have tabula-py and not tabula.
Interestingly, it appears to work in Anaconda prompt, but it doesn't work in VSCode.

## Example code:
```
import tabula

inPDF = 'Ground Floor Finishes Plan.pdf'

df = tabula.read_pdf("./Import/Ground Floor Finishes Plan.pdf", pages='all')

tabula.convert_into(inPDF, "output.csv", output_format="csv", pages='all')
```
## Output:
```
PS C:\Users\User\.spyder-py3> python -u "c:\Users\User\.spyder-py3\JacobPDF\PDFTableToExcel.py"
Traceback (most recent call last):
  File "c:\Users\User\.spyder-py3\JacobPDF\PDFTableToExcel.py", line 11, in <module>
    df = tabula.read_pdf("./Import/Ground Floor Finishes Plan.pdf", pages='all')
AttributeError: module 'tabula' has no attribute 'read_pdf'
PS C:\Users\User\.spyder-py3>
```
## What did you intend it to be?

I intended it to create a .csv file.

**Comment by BruceJi7** [comment]
It also behaves this way in Spyder. Running tabula from the base environment causes the AttributeError, but from within the right environment it works well.
At this moment I think it's because neither editor is using the correct environment.

**Comment by chezou** [comment]
Don't you have the file named `tabula.py` in your project?

**Comment by BruceJi7** [comment]
In the folder alongside my Python code file? No, I don't have that file there.

**Comment by BruceJi7** [comment]
I added numpy to my conda environment but I still get that message :|

**Comment by chezou** [comment]
I'm not familiar with CodeRunner but does it ensure your virtual environment? Looking at this issue, but not sure how it works https://github.com/formulahendry/vscode-code-runner/issues/395

**Comment by chezou** [comment]
@BruceJi7 Was the link I mentioned helpful? I doubt your problem is CodeRunner origin.

**Comment by chezou** [comment]
No response from reporter . Will close
