### ISSUE TITLE
Add iterator to split content by page

### ISSUE THREAD

**Issue by bpben** [chezou/tabula-py#154]
First: Thanks so much for your work on this, this works amazingly for my project.

**Is your feature request related to a problem? Please describe.**
From what I can tell, there doesn't seem to be a way to get a DataFrame for each page.  It seems like everything gets concatenated at the end.  My solution right now is to just iterate through pages until there is a CalledProcessError since it doesn't seem like there's a page number detect capability.  But it seems like a flag could govern whether the output was a generator vs a single DataFrame.

**Describe the solution you'd like**
Some kind of flag (e.g. iterator=True) that would have the read_pdf function return a generator, which would output a list of DataFrames, one for each page.  I could implement the hack I wrote above, but I assume there's probably a better solution out there.

**Describe alternatives you've considered**
I described one above.  But pyPDF could also be used to get the total page number and iterate through.  But I'd rather that have to load that along with Tabula.

Let me know if it'd be helpful for to me to make a PR with what I'm thinking.

**Comment by bpben** [comment]
Actually, just realized `multiple_tables=True` does what I need.  I didn't really understand it from the documentation, seemed like it was multiple per page.  Do you think that needs updating in the docs? Happy to try and add that.

**Comment by chezou** [comment]
yeah, it'd be nice if you could send a PR for document improvement ;)
