### ISSUE TITLE
Tabula failed to detect spaces between different columns when setting guess = False

### ISSUE THREAD

**Issue by MiaHuang97** [chezou/tabula-py#155]
# Summary of your issue

So I am trying to extract a pdf that is just a single page of table. When all the settings are default it leaves out the last two rows in the table. But when guess = False it fails to detect the white spaces between columns and merge two columns together. 

# Environment

Python version:
    3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) Client VM (build 25.212-b10, mixed mode)
tabula-py version: 1.3.1
platform: Windows-10-10.0.17134-SP0

Providing PDF would be really helpful to resolve the issue.

https://nlcities1-my.sharepoint.com/:b:/g/personal/huang_nlc_org/Eal2FrDFUr9EgwtpQJdZa2QBLkOK6FroT0z95itJK1b2bA?e=GgiaDA

# What did you do when you faced the problem?

At first, I didn't set any options so everything is just default, but then the last two rows (fund balances) are not detected. So I set the options to guess = False and stream = True, but somehow Tabula cannot detect the white spaces separating the column this time

## Code:
Default:
![default](https://user-images.githubusercontent.com/52172632/60039170-1d200d00-9684-11e9-943b-5e4f7823beb5.png)
guess = False
![guess](https://user-images.githubusercontent.com/52172632/60039181-214c2a80-9684-11e9-802f-426568095a27.png)

## Expected behavior:

This is what I got by manually selecting the table area  on the web interface
![tabula-web](https://user-images.githubusercontent.com/52172632/60039377-91f34700-9684-11e9-871f-bdf8e2c58d64.png)

**Comment by ayubansal1998** [comment]
Because if you set guess = False then tabula try to parse other text also which is not enclosed in a table but looks like tabular data and if the length of the parsed text is greater than column size then it will merge the columns 
So if the tabular format is same than you could use the "area option"

**Comment by chezou** [comment]
As ayubansal1998 said, you need to set `area` option. If you can detect area by using `guess=True` appropretely, you can try this tip https://blog.chezo.uno/a-recent-update-of-tabula-py-a923d2ab667b#af0e
Other than that, you also can export a template from tabula.app and reuse it with `read_with_template()` function.

**Comment by chezou** [comment]
No update from reporter. Will close it. but feel free to reopen it if needed,
