### ISSUE TITLE
tabula merges column in HDFC bank statement

### ISSUE THREAD

**Issue by ayubansal1998** [chezou/tabula-py#156]
Tabula merges columns of last page in HDFC bank statement and even if there is any field which is empty in any page then tabula does not detect that field and even it writes the output of nest column.

tabula.read_pdf(pdfpath,pages='all',columns=['68.0,272.0,357.5,397.0,474.5,553.0'])
I even tried to take column co-ordinate but tabula is not detecting it like Camelot did
camelot separates columns if provided but tabula doesn't

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
