### ISSUE TITLE
Columns getting merged and mispredict data in different column

### ISSUE THREAD

**Issue by ayubansal1998** [chezou/tabula-py#157]
# I have same Issue like mentioned in this #55 
@chezou in above issue you mentioned that 'it's a kind of tabula-java option problem' but same problem occur in python also. and it also mispredicts data when the complete column is empty on any page .
I tried this

`tables=tabula.read_pdf('HDFC2.pdf',guess=False,stream=True,pages='all')`

# Even I tried to give column co-ordinate.
`tables=tabula.read_pdf('HDFC2.pdf',guess=False,stream=True,pages='all',columns=['68.0,272.0,357.5,397.0,474.5,553.0'])`
tabula doesn't even detecting columns

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
