### ISSUE TITLE
# puts two column together in one 

### ISSUE THREAD

**Issue by gillz** [chezou/tabula-py#161]
Hello,
when i try to convert a pdf file when column name / header has # sign at end than it put all column in one column.  for example  Name #  Password # it will put all names and passwords in 1 column together. 
how to fix it or remove # sign so name and password column so go to individual ( their own ) column ?

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
