### ISSUE TITLE
Missing data when using inside Flask API

### ISSUE THREAD

**Issue by KhoaNguyenDang121292** [chezou/tabula-py#162]
I'm trying to use tabula-py inside Flask API but it seemed to be not effected. It means when i used it in my normal Flask-API by command line "flask run", the tabula-py worked perfectly, but when I deploy Flask API with UWSGI and NGINX, tabula-py worked but the response data from pdf is missed about 20-30% data.

Can anybody help me to resolve this issue?

Thank you very much!

**Comment by KhoaNguyenDang121292** [comment]
This issue is resolved. I found that version tabula-py==0.9.0 is appropriate to use inside Flask API.

**Comment by chezou** [comment]
Seems not tabula-py issue. will close it.
