### ISSUE TITLE
Stream or lattice?

### ISSUE THREAD

**Issue by Brandwja** [chezou/tabula-py#164]
# Summary of your issue

It is not clear in any of the tabula-py documentation whether the tabula.read_pdf() function uses lattice or stream mode extraction as its default setting if no lattice or stream argument is passed to the function. Does the code somehow guess which of the two modes would be preferable depending on the "table" encountered in the pdf text and, if not, could you please clarify which of the two extraction modes is being used as the default (therefore rendering one of the two arguments redundant since, de facto, if you set lattice to False then you must by definition be setting stream to True, and vice versa)? Thanks in advance.

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

```Python version:
    3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Java version:
    java version "1.8.0_211"

Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
tabula-py version: 1.3.1
platform: Windows-10-10.0.17134-SP0
uname:
    uname_result(system='Windows', node='BRANDWOOD-PCLT', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

Providing PDF would be really helpful to resolve the issue.

- [ ] (Optional, but really helpful) Your PDF URL: ?


# What did you do when you faced the problem?

Provide your information to reproduce the issue.

## Code:

```
paste your core code which reproducible for the issue
```

## Expected behavior:


## Actual behavior:

```
paste your output
```

## Related Issues:

**Comment by chezou** [comment]
Close the issue since this is a question.

See https://nbviewer.jupyter.org/github/chezou/tabula-py/blob/master/examples/tabula_example.ipynb#Use-lattice-mode-for-more-accurate-extraction-for-spreadsheet-style-tables
