### ISSUE TITLE
Cannot read JBIG2 image: jbig2-imageio is not installed

### ISSUE THREAD

**Issue by akrsrivastava** [chezou/tabula-py#166]
# Summary of your issue
Getting error on using the read_pdf function

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

```py
tabula.environment_info()
Python version:
    3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Java version:
    openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)
tabula-py version: 1.1.1
platform: Windows-10-10.0.15063-SP0
uname:
    uname_result(system='Windows', node='C1FF163APDSMD', release='10', version='10.0.15063', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

Providing PDF would be really helpful to resolve the issue.

- [ ] (Optional, but really helpful) Your PDF URL: ?

# What did you do when you faced the problem?

## Code:

```
from tabula import read_pdf
df = read_pdf("0203_207_searchable.pdf",  guess = True, encoding = 'cp1252')
```

## Expected behavior:
Pandas DF created with tabular information

## Actual behavior:

```
Jul 22, 2019 6:34:30 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed
Jul 22, 2019 6:34:31 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed
Jul 22, 2019 6:34:31 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
SEVERE: Cannot read JBIG2 image: jbig2-imageio is not installed
```

**Comment by chezou** [comment]
@akrsrivastava That warning message came from PDFBox which is used by tabula-java. Not tabula-py issue. If your `df` have nothing, you have to ask tabula-java or PDFBox.
Before asking them, I recommend trying [tabula app](https://tabula.technology/).

Note that, tabula-java and tabula-py can't extract data from an image, it must be text.

**Comment by sujit25** [comment]
@akrsrivastava This issue can in following manner:

1. Clone https://github.com/tabulapdf/tabula-java repo.
2. Built it and generate its jar file.
3. Copy generated jar file to tabula-py folder in site-packages directory. Just replace existing jar with new one.

Hopefully it helps.
