### ISSUE TITLE
CalledProcessError (Jupyter Notebook)

### ISSUE THREAD

**Issue by pefreis** [chezou/tabula-py#169]
# Summary

# Environment

```py
Python version:
    3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Java version:
    java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode, sharing)
tabula-py version: 1.4.0
platform: Windows-10-10.0.17134-SP0
uname:
    uname_result(system='Windows', node='PS059', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
linux_distribution: ('MINGW64_NT-10.0-17134', '3.0.7', '')
mac_ver: ('', ('', '', ''), '')
```

PDF URL: ‪C:\tabula\test\test_file.pdf

# What did you do when you faced the problem?

I have just started a new project using tabula-py in Jupyter Notebook. When trying to execute a simple `read_pdf` I get `CalledProcessError`. I have already tried updating java and configuring the environment variables, but still get the same. Also, when I execute the .jar file located on tabula-py's package folder there's no error. May be useful to inform that on the bash from which I started Jupyter Notebook the error message I get is

> Cannot create file C:\Users\PEDRO~1.REI\AppData\Local\Temp\tmp2_v5oym2

### UPDATE
I thought it could be useful to mention also that I checked the Temp folder for the files tabula creates there. These files which Jupyter warns me could not be created are there, but are empty. On the other hand, when I executed the tabula .jar file with --outfile option similar to the one I found on the error stack trace (C:\\Users\\PEDRO~1.REI\\AppData\\Local\\Temp\\tmp...) the file was created seamlessly.

### UPDATE 2
Also tried executing .jar with the **SAME** --outfile as tabula-py was showing on error stack trace. In this case the `Cannot create file` error is thrown again. See below:

![error_python](https://user-images.githubusercontent.com/42272817/62212366-f043d180-b376-11e9-82e4-11e1f0dceb83.PNG)

![error_java](https://user-images.githubusercontent.com/42272817/62212379-f8037600-b376-11e9-92e2-296fac005f11.PNG)

### To sum up

- when I execute from .jar and specify a new name for the file to be created in Temp folder, the file is properly created and receives the output of tabula execution.

- when I execute from tabula-py, the file is created, but the output is not written to it. If I try to write the output from .jar execution to this same file, I get the same `Cannot create file` error.

## Code:

```
import tabula
file = 'C:/tabula/test/test_file.pdf'
tabula.read_pdf(file)
```

## Output:

```
Error: 

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-19-b1820cc3c098> in <module>
----> 1 tabula.read_pdf(file)

c:\users\pedro.reis\appdata\local\programs\python\python37\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
    148 
    149     try:
--> 150         output = _run(java_options, kwargs, path, encoding)
    151     finally:
    152         if temporary:

c:\users\pedro.reis\appdata\local\programs\python\python37\lib\site-packages\tabula\wrapper.py in _run(java_options, options, path, encoding)
     65 
     66     try:
---> 67         return subprocess.check_output(args)
     68     except FileNotFoundError:
     69         raise JavaNotFoundError(JAVA_NOT_FOUND_ERROR)

c:\users\pedro.reis\appdata\local\programs\python\python37\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    393 
    394     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 395                **kwargs).stdout
    396 
    397 

c:\users\pedro.reis\appdata\local\programs\python\python37\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    485         if check and retcode:
    486             raise CalledProcessError(retcode, process.args,
--> 487                                      output=stdout, stderr=stderr)
    488     return CompletedProcess(process.args, retcode, stdout, stderr)
    489 

CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'c:\\users\\pedro.reis\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar', '--pages', '1', '--guess', '--outfile', 'C:\\Users\\PEDRO~1.REI\\AppData\\Local\\Temp\\tmpab3az2_3', 'C:/tabula/test/test_file.pdf']' returned non-zero exit status 1.
```

## Related Issues:
https://github.com/chezou/tabula-py/issues/60
https://github.com/chezou/tabula-py/issues/93
https://github.com/chezou/tabula-py/issues/86

**Comment by zguan999** [comment]
I am getting the same error too

**Comment by bashallc** [comment]
also me

**Comment by chezou** [comment]
Thank you for the report. In v1.4.0 I made a workaround for tabula-java issue, which has been resolved with the latest release jar. That change using NamedTemporaryFiles causes this issue.

While I'm planning to fix back using stdout directly, but I don't have enough time to do that for personal reason. 

Meanwhile can you use 1.3.1 until I'll address? Of course, tabula-py is an OSS, it'd be much appreciated someone could help me.

**Comment by chezou** [comment]
Fixed in https://github.com/chezou/tabula-py/pull/172 and released v1.4.1.

**Comment by giblet17** [comment]
Started using tabula today for the first time and ran into the above error.
I've downloaded Java V8 and have tabula 1.4.1 as of today.
Is there anything else I am missing to get around this error?
Thanks,
Will

**Comment by chezou** [comment]
@giblet17 Thanks for reporting. Seems different problem with this issue. Can you open another issue with detailed info? I'm pretty interested in you've mentioned 1.3.1 works fine and wanna try to investigate.

**Comment by Ichiroad** [comment]
I got a similar error below. How can I solve it ? The  script works well on the pycharm but it doesn't work on .exe created by pyinstaller with using ">pyinstaller --onefile GetPdfTable.py" command. The line 91 in GetPdfTable.py is "tabula.read_pdf(file, lattice=True, pages=str(page))" which call subprocess module??. 
And I'm using:
    pyinstaller: 4.2
    tabula-py: 2.2.0
    tabula: 1.0.5

I tried:
        -other pdf files 
                --> same error
       -version down (tabula-py: 1.4.1, tabula: 1.03)
                --> same error    

----error on console----
Error from tabula-java:
Error: Unable to access jarfile C:\Users\AAAA\AppData\Local\Temp\_MEI174282\tabula\tabula-1.0.4-jar-with-dependencies.jar


Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "GetPdfTable.py", line 91, in button_click
  File "tabula\io.py", line 322, in read_pdf
  File "tabula\io.py", line 80, in _run
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\AAAA\\AppData\\Local\\Temp\\_MEI174282\\tabula\\tabula-1.0.4-jar-with-dependencies.jar', '--pages', '1', '--lattice', '--guess', '--format', 'JSON', 'C:/Users/AAAA/OneDrive - Advantest/Documents/pythonProject/test.pdf']' returned non-zero exit status 1.

I'm a beginner of Python and hope your kindness.
Best regards,
Ichiroad
