### ISSUE TITLE
I am trying to extract data from two different pdf's when i used tabula server with loccal host its detecting properly, but if i run it in python its not working. kindly please help me for this.

### ISSUE THREAD

**Issue by anandhkirupa** [chezou/tabula-py#174]
I am trying to extract data from two different pdf's when i used tabula server with local host its detecting properly for the pdf named "d.pdf", For PDF "d0.pdf" its not wvwn detecting, but if i run "d.pdf" in python its giving only header as output and for "d0.pdf" it giving "The Output file is empty". kindly please help me for this. I will attach two pdf i need two seperate csv or tsv.

# Environment

>>> import tabula - is working properly.

Output of tabula.environment_info:

>>> tabula.environment_info()
Python version:
    3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609]
Java version:
    openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
tabula-py version: 1.4.1
platform: Linux-4.4.0-164-generic-x86_64-with-Ubuntu-16.04-xenial
uname:
    uname_result(system='Linux', node='godAss', release='4.4.0-164-generic', version='#192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '16.04', 'xenial')
mac_ver: ('', ('', '', ''), '')

For your information, i am running it on Ubuntu

PDF - 1 [https://drive.google.com/open?id=12JvOPlpEXX23WuIoaWfut-F8rVtWdkAM](url)
PDF - 2 [https://drive.google.com/open?id=15XBE9SQZfiR5eVJmfDwTf4em0TTmphGe](url)

Kindly download the pdf it's my google drive link.

# What did you do when you faced the problem?
I tried to find solution in various platforms and tried different pdf's for reading.

Provide your information to reproduce the issue.

## Code:

import tabula

pdf_path = "/home/godass69/Desktop/Hackathon - Quess/d.pdf"

tabula.read_pdf(pdf_path, pages="all", stream=True)

tabula.convert_into(pdf_path, "test.tsv", output_format="tsv")

## Expected behavior:
Table Header with the data.

## Actual behavior:
![image](https://user-images.githubusercontent.com/33204634/65664049-11166380-e056-11e9-9bb8-0f5bb9883960.png)

**Comment by chezou** [comment]
Seems that using `stream=True` can extract some data same as tabula.app does:

```
>>> import tabula
>>> tabula.read_pdf(pdf_path, pages="all", stream=True)
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: Your current java version is: 1.8.0_181
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: To get higher rendering speed on old java 1.8 or 9 versions,
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   update to the latest 1.8 or 9 version (>= 1.8.0_191 or >= 9.0.4),
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
Oct 03, 2019 4:28:33 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
    Unnamed: 0    Unnamed: 1  CGST 0%    998514  Unnamed: 4              Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12
0          NaN           NaN      NaN       NaN         NaN  Service Fee for Sindhu        NaN        NaN        NaN        NaN        0.00         NaN         NaN
1     12401979  T-70367296-0  SGST 0%       NaN  25/08/2019                     NaN       0.00       0.00       0.00       0.00         NaN        0.00         INR
2          NaN           NaN      NaN       NaN         NaN        Ramakrishnegowda        NaN        NaN        NaN        NaN         NaN         NaN         NaN
3          NaN           NaN  IGST 0%       NaN         NaN                     NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
4          NaN           NaN  CGST 9%  998514.0         NaN                     NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
..         ...           ...      ...       ...         ...                     ...        ...        ...        ...        ...         ...         ...         ...
362        NaN           NaN      NaN       NaN         NaN               Subramani        NaN        NaN        NaN        NaN         NaN         NaN         NaN
363        NaN           NaN  IGST 0%       NaN         NaN                     NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
364        NaN           NaN  CGST 0%  998514.0         NaN                     NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
365        NaN           NaN      NaN       NaN         NaN  Service Fee for Sindhu        NaN        NaN        NaN        NaN        0.00         NaN         NaN
366   12401979  T-69787749-0  SGST 0%       NaN  04/08/2019                     NaN       0.00       0.00       0.00       0.00         NaN        0.00         INR

[367 rows x 13 columns]
```

![image](https://user-images.githubusercontent.com/916653/66107404-29a8ef80-e5fb-11e9-8a02-08004ae41ca4.png)

@anandhkirupa Can you write specific expected behavior? I can't understand your issue.

**Comment by chezou** [comment]
@anandhkirupa Close since it seems the limitation of tabula-java, but feel free to reopen if you find any tabula-py specific issue.
