### ISSUE TITLE
Output : Empty DataFrame

### ISSUE THREAD

**Issue by anandhkirupa** [chezou/tabula-py#175]
@chezou I am trying to read a pdf and save it in a data frame, after reading wheh i try to see the output its showing only the header not showing the data.

# Environment

>>> import tabula
>>> tabula.environment_info()
Python version:
    3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609]
Java version:
    openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
tabula-py version: 1.4.1
platform: Linux-4.4.0-164-generic-x86_64-with-Ubuntu-16.04-xenial
uname:
    uname_result(system='Linux', node='godAss', release='4.4.0-164-generic', version='#192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '16.04', 'xenial')
mac_ver: ('', ('', '', ''), '')

My PDF url
[d.pdf](https://github.com/chezou/tabula-py/files/3656657/d.pdf)

# What did you do when you faced the problem?

I converted the pdf to image and cropped the image and again converted image to pdf, still it didn't work.

## Code:

>>> import tabula
>>> from tabula import read_pdf
>>> df = read_pdf("d.pdf",pages="all")
>>> df

## Expected behavior:
extracted data from the pdf and show it as a dataframe

## Actual behavior:
![tabula](https://user-images.githubusercontent.com/33204634/65672985-98200780-e067-11e9-8108-11a9a48b89c8.png)

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.

**Comment by anandhkirupa** [comment]
> This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.

Filed bug, Thanks in advance
