### ISSUE TITLE
tabula-py: how to handle columns consisting entirely of NULL values?

### ISSUE THREAD

**Issue by rileyhun** [chezou/tabula-py#18]
tabula-py has done a mostly fantastic job doing what I need it to do so far. However, I have encountered issues caused by a table column that consists entirely of NULLs. For example, I have a table split across 5 different pages. For one page, the partitioned table in question has an empty column; this shifts the entire dataframe to the left, so that when it is merged with the partitioned tables from the other pages, the columns don't line up correctly. Is there a way around this?

**Comment by chezou** [comment]
Do you have any specific PDF? How about extracting with tabula-java?

**Comment by chezou** [comment]
@rileyhun If possible, could you give me a specific PDF? Or, please provide an example.

**Comment by chezou** [comment]
Please provide more specific information.

**Comment by hitman-dev** [comment]
Hey @chezou i have a same issue, can we connect to discuss this ?
