### ISSUE TITLE
CalledProcessError Tabula-py

### ISSUE THREAD

**Issue by Suicoleiro** [chezou/tabula-py#182]
When running tabula-py I get a "CalledProcessError":

PDF URL = https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf

!java -version
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

tabula.environment_info()
Python version:
    3.7.3 (default, Apr 24 2019, 13:20:13) [MSC v.1915 32 bit (Intel)]
Java version:
    java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)
tabula-py version: 1.4.1
platform: Windows-10-10.0.17763-SP0
uname:
    uname_result(system='Windows', node='TROMW034063', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

## Code:

```
import tabula
pdf_path = "https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf"
tabula.read_pdf(pdf_path, stream=True)

```

## Expected behavior:
Reading the PDF with tabula-py

## Actual behavior:

```
CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\loetscp1\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar', '--pages', '1', '--stream', '--guess', 'data.pdf']' returned non-zero exit status 1.
```

## Related Issues:
When excecuting the following code in command prompt

java -jar 'C:\Users\loetscp1\AppData\Local\Continuum\anaconda3\Lib\site-packages\tabula\tabula-1.0.3-jar-with-dependencies.jar' --pages 2' --guess --format JSON 'https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf'

I get the error:
Error: Unable to access jarfile 'C:\Users\loetscp1\AppData\Local\Continuum\anaconda3\Lib\site-packages\tabula\tabula-1.0.3-jar-with-dependencies.jar'

**Comment by chezou** [comment]
Thanks for your reporting @Suicoleiro .

Seems you're using anaconda. Can you check 1) `pip show tabula-py` and 2) the result of `C:\Users\loetscp1\AppData\Local\Continuum\anaconda3\Lib\site-packages\tabula\`? Also, do you use the same drive letter `C:\` for your Python script?

It'd be helpful if you can check whether tabula works with downloaded data as well.

**Comment by chezou** [comment]
@Suicoleiro Can you check the previous question?

**Comment by Suicoleiro** [comment]
Hi Chezou,

Sorry, for my late answer. Here the two screenshots on your questions.
1)
![image](https://user-images.githubusercontent.com/56967998/67934380-153f1f00-fbc8-11e9-923f-97607d477c1c.png)

2)
![image](https://user-images.githubusercontent.com/56967998/67934335-ffc9f500-fbc7-11e9-8825-970bb28c7999.png)

It shows the same behavior if I use downloaded data as well.

Highly appreciate your help!

**Comment by chezou** [comment]
thanks for your response. hmm sounds strange to see the behavior.

just in case, can you copy and paste whole code and logs for the error with downloaded PDF?
also which directory did you start Python process?

**Comment by chezou** [comment]
@Suicoleiro  Unable to reproduce the issue on my Windows 10 with Miniconda prompt.

```
(base) C:\Users\chezo>pip --version
pip 19.3.1 from C:\Users\chezo\Miniconda3\lib\site-packages\pip (python 3.7)

(base) C:\Users\chezo>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Users\\chezo\\Miniconda3\\python37.zip', 'C:\\Users\\chezo\\Miniconda3\\DLLs', 'C:\\Users\\chezo\\Miniconda3\\lib', 'C:\\Users\\chezo\\Miniconda3', 'C:\\Users\\chezo\\Miniconda3\\lib\\site-packages', 'C:\\Users\\chezo\\Miniconda3\\lib\\site-packages\\win32', 'C:\\Users\\chezo\\Miniconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\chezo\\Miniconda3\\lib\\site-packages\\Pythonwin']
>>> import tabula
>>> pdf_path = "https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf"
>>> tabula.read_pdf(pdf_path, stream=True)
             Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
```

I doubt your environment is corrupted because the output of `!java -version`, i.e. Java 13.01, (maybe from ipython?) and `tabula.environment_info()`'s Java version, i.e. 1.7.0_51, is different.

Can you try the following command on your Anaconda terminal?

```shell
curl -L -O https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf
java -jar C:\Users\loetscp1\AppData\Local\Continuum\anaconda3\Lib\site-packages\tabula\tabula-1.0.3-jar-with-dependencies.jar --guess data.pdf
```

If it works, the issue is your Python environment issue, if not works, it means your PATH issue for JAVA. In both cases, the issue isn't coming from tabula-py itself.

**Comment by Suicoleiro** [comment]
@chezou Yes, it works when running the code from the Anaconda terminal (see below). Any suggestions for fixing the Python environment issue?

![image](https://user-images.githubusercontent.com/56967998/68213580-24650900-ffdc-11e9-8f83-1243c1342911.png)

**Comment by chezou** [comment]
@Suicoleiro  Unfortunately, I'm not familiar with the building Python environment on Windows with Anaconda. Can you ask it on StackOverflow?

**Comment by Suicoleiro** [comment]
@Chezou: Thanks very much for your help. I just got it to work now. Had to delete java.exe and javaw.exe from my C:\Windows\SysWOW64 folder.

**Comment by chezou** [comment]
great to know to be fixed!

**Comment by ashishdkulkarni1592** [comment]
I am getting same error while reading pdf file which is uploaded from angular 
CalledProcessError at /api/uploadvendorchargefile/
Command '['java', '-Dfile.encoding=UTF8', '-jar', '/home2/backend/appvenv/lib/python3.5/site-packages/tabula/tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', '29168.pdf']' returned non-zero exit status 1


tabula.environment_info()
Python version:
3.5.1
Java version:
OpenJdk Version "1.8.0_232"
OpenJdk Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232.b09)
tabula-py version: 1.3.1
platform: Ubuntu 18.04
Working properly on another server on ubuntu 16.04
Uninstall and Install tabula-py
