### ISSUE TITLE
Issue while reading watermark pdf. getting garbage value in the column

### ISSUE THREAD

**Issue by jhapawan** [chezou/tabula-py#183]
While reading watermark pdf, getting garbage value in the column

https://stackoverflow.com/questions/58870493/while-reading-watermark-pdf-getting-garbage-value-in-the-column

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.

**Comment by jhapawan** [comment]
I have attached the pdf. can you please help to get it to resolve.

**Comment by chezou** [comment]
No, you need to comply the issue template.
