### ISSUE TITLE
while-reading-watermark-pdf-getting-garbage-value-in-the-column

### ISSUE THREAD

**Issue by jhapawan** [chezou/tabula-py#184]
# Check list before submit

Write and check the following questionaries.

- [ ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?
yes

- [ ] (Optional, but really helpful) Your PDF URL: ?
[1904-TV1920B2700219.pdf](https://github.com/chezou/tabula-py/files/3884816/1904-TV1920B2700219.pdf)

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
Python version:
    3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)
tabula-py version: 1.3.1
platform: Windows-10-10.0.17134-SP0
uname:
    uname_result(system='Windows', node='WKWIN8232337', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
Python 3.7.3
- [ ] Paste the output of `java -version` command on your terminal: ?
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
It is working as expected 
- [ ] Write your OS and it's version: ?
WIN10
# What did you do when you faced the problem?
Extracted data has some garbage value appended in the column value
Provide your information to reproduce the issue.

## Code:

def get_pdf_table_list(filePath):
    df = []
    pdf = PdfFileReader(open(filePath,'rb'))
    n=pdf.getNumPages()   
    for page in [str(i+1) for i in range(n)]:
    
           if int(page)==1:
               df = read_pdf(filePath, 
                        area = (348.9,18.003,761.558,593.283),
        #                lattice=True,
                        stream=True
                        ,pandas_options={'header': None}
                        ,pages = 1,
                        guess=True
                        )

              
    return df 

df= get_pdf_table_list(filepath)
```
paste your core code which reproducible for the issue
```
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 09:48:17 2019

@author: pawpanka0
"""
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 09:48:17 2019

@author: pawpanka0
"""

from tabula import read_pdf
from PyPDF2 import PdfFileReader
import os
import pandas as pd

def get_pdf_table_list(filePath):
    df = []
    pdf = PdfFileReader(open(filePath,'rb'))
    n=pdf.getNumPages()   
    for page in [str(i+1) for i in range(n)]:
    
           if int(page)==1:
               df = read_pdf(filePath, 
                        area = (348.9,18.003,761.558,593.283),
        #                lattice=True,
                        stream=True
                        ,pandas_options={'header': None}
                        ,pages = 1,
                        guess=True
                        )

              
    return df 

df= get_pdf_table_list(filepath)
[1904-TV1920B2700219.pdf](https://github.com/chezou/tabula-py/files/3884873/1904-TV1920B2700219.pdf)

## Expected behavior:
column value should not contain any garbage value

## Actual behavior:
Description column value extract value containing some garbage value

```
paste your output
```
	0	1	2	3	4	5	6	7
0	02/04/2019	TUE	10:12:36	FOR YOUR EYES ONLY	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
1	02/04/2019	TUE	15:19:18	THE DARKEST HOUR	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
2	02/04/2019	TUE	19:22:25	GOLDENEYE	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
3	02/04/2019	TUE	20:11:23	GOLDENEYE	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
4	03/04/2019	WED	10:24:55	KNIGHT AND DAY	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
5	03/04/2019	WED	14:47:16	FROZEN	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
6	03/04/2019	WED	19:54:23	EPIC MOVIE	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
7	03/04/2019	WED	20:46:38	EPIC MOVIE	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
8	04/04/2019	THU	10:24:20	ALVIN AND THE CHIPMUNKS	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
9	04/04/2019	THU	15:48:44	MINIONS	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
10	04/04/2019	THU	19:23:19	FROZEN	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
11	04/04/2019	THU	20:44:01	FROZEN	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
12	05/04/2019	FRI	10:12:27	BIG MOMMAS: LIKE FATHER, LIKE SON	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
13	05/04/2019	FRI	11:56:33	UNDERWORLD EVOLUTION	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
14	05/04/2019	FRI	13:36:06	EVAN ALMIGHTY	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
15	05/04/2019	FRI	15:17:32	SPLIT	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
16	05/04/2019	FRI	19:14:02	CONAN THE DESTROYER	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
17	05/04/2019	FRI	19:39:08	CONAN THE DESTROYER	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
18	05/04/2019	FRI	20:09:42	CONAN THE DESTROYER	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
19	05/04/2019	FRI	20:40:50	CONAN THE DESTROYER	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
20	05/04/2019	FRI	21:21:29	YOU ONLY LIVE TWICE	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
21	06/04/2019	SAT	10:50:17	TORQUE	ABUDHABIETHIADTV-ENGLISH-30 **SEC**	30.0	1,516.47	1,516.47
22	06/04/2019	SAT	13:10:59	CREED	**ABUDHABIETHIADTV-ENGLISH-30 SEC**	30.0	1,516.47	1,516.47
23	06/04/2019	SAT	13:45:05	UNDERWORLD EVOLUTION	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
24	06/04/2019	SAT	14:46:51	UNDERWORLD EVOLUTION	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
25	06/04/2019	SAT	15:44:19	THE CHRONICLES OF NARNIA: THE LION,	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
26				THE WITCH AND THE WARDROBE				
27	06/04/2019	SAT	19:18:08	THE GIRL NEXT DOOR	**ABUDHABIETHIADTV-ENGLISH-30 SEC**	30.0	1,516.47	1,516.47
28	06/04/2019	SAT	19:20:43	THE GIRL NEXT DOOR	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
29	06/04/2019	SAT	19:50:36	THE GIRL NEXT DOOR	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
30	06/04/2019	SAT	20:16:31	THE GIRL NEXT DOOR	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
31	06/04/2019	SAT	20:49:58	THE GIRL NEXT DOOR	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
32	07/04/2019	SUN	11:49:09	THE WORLD IS NOT ENOUGH	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47
33	07/04/2019	SUN	13:11:46	THE WORLD IS NOT ENOUGH	ABUDHABIETHIADTV-ENGLISH-30 SEC	30.0	1,516.47	1,516.47

## Related Issues:
https://stackoverflow.com/questions/58870493/while-reading-watermark-pdf-getting-garbage-value-in-the-column

**Comment by jhapawan** [comment]
@chezou I have added with the template as you have suggested. Now can you please help to resolve this.

**Comment by chezou** [comment]
@jhapawan Thanks for your cooperation.

I have two requests to understand your issue.
1) could you tidy up your code with minimal reproducible one with appropriate indent? 2) Could you write "expected behavior" what you imagine? I can't read your mind without having the writing down.

Also, how was the output of tabula app looks like?

**Comment by jhapawan** [comment]
Hi @chezou Thank you for your quick reply.

Please find the below attachment which is generated from tabula app.
[tabula-1908-TV1920B2701530.xlsx](https://github.com/chezou/tabula-py/files/3884997/tabula-1908-TV1920B2701530.xlsx)
I am getting garbage value (**S5EC**) appended in the column CAPTION.

**Comment by chezou** [comment]
The issue is not came from tabula-py but tabula-java itself. Can you please file a ticket on tabula-java issue?

**Comment by jhapawan** [comment]
Thank you. Sure I will create an issue on tabula-java.
