### ISSUE TITLE
Wrap Text / Row Configuration Feature Request

### ISSUE THREAD

**Issue by nacu4** [chezou/tabula-py#192]
**Is your feature request related to a problem? Please describe.**
On the PDF files that I have, the data is not always in a super clear format. There are times in which the text on the PDF is "wrapped" onto a second line. Therefore, when the file is exported to CSV, the data is inconsistent. 

**Describe the solution you'd like**
Within the function convert_into... there should be a sub function called "rows" where the user could configure the start point, end point, and number of rows. 
In the screenshot below and example code in the next section, Tabula would then convert the CSV into 1 consolidate row for every instance where the text shows "Line Item" and "Item No" and ignore everything else. 
In addition, the number of rows indicated would force the conversion to wrap text into the designated number of rows. 

The user would type something like this:
columns = (1,2,3,4,5)
start = ('Line Item%', '', '', '', '')
end = ('Item No%', '%%', '', '', '')
rows = 3 (or 1, depending on if you want the start row and end row included in the count)

**Describe alternatives you've considered**
Another option would be to just say "wrap text" Yes/No where, if the text in a column is at the edge, the next row of data would get wrapped 
Another option would be to specify the dimensions of a "typical" row size and the "maximum" row size, with the option to wrap text in a given way

**Additional context**
![image](https://user-images.githubusercontent.com/22282824/70161197-86af3900-1670-11ea-907c-b03608fe5329.png)

**Comment by nacu4** [comment]
@chezou  thanks again for your patience. Please advise if there's any problems with this Issue and I'll correct when I can.

**Comment by chezou** [comment]
tabula-py is just a wrapper of tabula-java, and there's not functions to "wrap" the cells. You have to write your post processing code for read_pdf by your self. The heuristic you've mentioned is too specific to your problem.

**Comment by nacu4** [comment]
@chezou  I'll submit to the tabula-java group
