### ISSUE TITLE
Extracting tables from a multi-page pdf (this time, with feeling)

### ISSUE THREAD

**Issue by djinnome** [chezou/tabula-py#195]
**Is your feature request related to a problem? Please describe.**

This problem is closely related to the problem of extracting two or more tables from a pdf page.
In this case, a single table spans more than one page.

**Describe the solution you'd like**
The solution I'd like is to return a list of tables extracted, one for each page.

**Describe alternatives you've considered**
What currently happens is the table is extracted from the first page, and then it quits.  Even if I use the `pages=46` and/or the `multiple_tables=True` flags.

A workaround for this is simply to split the multi-page pdf into a set of single page pdfs.

**Additional context**
This actually solves the problem for all intents and purposes.  It is a little annoying for 46 pages, but honestly, took less than 5 minutes, and there are plenty of other data cleaning issues with this pdf that are going to take way longer

(I tried to submit this before, but because I cut the template headings, it automagically closed the issue.

**Comment by chezou** [comment]
I don't think I understand your situation correctly, but do you mean setting `pages="all"` or `pages="1-10"` with multiple_pges doesn't work in your context? I'd like to see the example PDF and code which you've tried.

**Comment by chezou** [comment]
hmm, something went wrong with the bot.

@djinnome Can you tell me the answer with above question?

**Comment by djinnome** [comment]
Hi @chezou 

Thanks for the question, which actually addressed my confusion.  It isn't well-documented how to use the `pages` parameter. Now I understand.

[Attached is my pdf](https://github.com/chezou/tabula-py/files/3970785/12918_2011_868_MOESM1_ESM.pdf)


This (mostly) seems to solve the problem:

```python
from tabula import read_pdf
rxn_options={'header':None,
                       'names':['Reaction Name','Compartment', 'Metabolic Reaction',
                                             'Subsystem','Gene(s) S. pombe', 'EC']}
rxns = read_pdf('12918_2011_868_MOESM1_ESM.pdf', 
                 pandas_options=rxn_options,
                 pages='1-23')
rxns.head()
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Reaction Name</th>
      <th>Compartment</th>
      <th>Metabolic Reaction</th>
      <th>Subsystem</th>
      <th>Gene(s) S. pombe</th>
      <th>EC</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>alanine racemase</td>
      <td>Cytosol</td>
      <td>ALA &lt;-&gt; dALA</td>
      <td>Alanine and Aspartate Metabolism</td>
      <td>SPBC359.02</td>
      <td>5.1.1.1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>alanine aminotransferase (predicted)</td>
      <td>Cytosol</td>
      <td>AKG + ALA &lt;-&gt; GLU + PYR</td>
      <td>Alanine and Aspartate Metabolism</td>
      <td>SPBC582.08</td>
      <td>2.6.1.2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>L-alanine transaminase</td>
      <td>Mitochondria</td>
      <td>AKG + ALA &lt;-&gt; GLU + PYR</td>
      <td>Alanine and Aspartate Metabolism</td>
      <td>SPBC582.08</td>
      <td>2.6.1.2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>aspartate-semialdehyde dehydrogenase</td>
      <td>Cytosol</td>
      <td>4pasp + H + NADPH -&gt; aspSA + NADP + Pi</td>
      <td>Alanine and Aspartate Metabolism</td>
      <td>SPCC1827.06c</td>
      <td>1.2.1.11</td>
    </tr>
    <tr>
      <th>4</th>
      <td>asparagine synthase (glutamine-hydrolysing)</td>
      <td>Cytosol</td>
      <td>ASP + ATP + GLN + H2O -&gt; AMP + ASN + GLU + H + PPi</td>
      <td>Alanine and Aspartate Metabolism</td>
      <td>SPBC119.10</td>
      <td>6.3.5.4</td>
    </tr>
  </tbody>
</table>

```python
met_options={'header':None,
            'names':['Abbreviation', 'Metabolite Name','Compartment']}
mets = read_pdf('12918_2011_868_MOESM1_ESM.pdf', 
                 pandas_options=met_options,
                 pages='24-46')
mets.head()
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Abbreviation</th>
      <th>Metabolite Name</th>
      <th>Compartment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>13BDglcn</td>
      <td>1,3-beta-D-Glucan</td>
      <td>Extracellular</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2hb</td>
      <td>2-Hydroxybutyrate</td>
      <td>Extracellular</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2mbac</td>
      <td>2-methylbutyl acetate</td>
      <td>Extracellular</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2mbald</td>
      <td>2-methylbutyraldehyde</td>
      <td>Extracellular</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2mbtoh</td>
      <td>2-methyl-1-butanol</td>
      <td>Extracellular</td>
    </tr>
  </tbody>
</table>

Sincerely,

@djinnome

**Comment by chezou** [comment]
Thanks for your suggestion. I've added an FAQ about `pages` option explicitly https://github.com/chezou/tabula-py/commit/98c1107fcb0cc17d46a03a2d39c426ae951c8f85

Also, you can check the example notebook as well. https://nbviewer.jupyter.org/github/chezou/tabula-py/blob/master/examples/tabula_example.ipynb
