### ISSUE TITLE
CalledProcessError after bundling Python script into executable with PyInstaller

### ISSUE THREAD

**Issue by adammet** [chezou/tabula-py#198]
# Summary of your issue

I've been using tabula-py to convert a series of pdf tables into csv files for my program to parse through and collect some data. The code works perfectly when just in the script, but if I attempt to bundle my code into an executable file using PyInstaller I get an error. Thanks for any help you can give!

# Check list before submit

- Your PDF URL: Unable to upload due to sensitivity of PDF.

- Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

Python version:
    3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
Java version:
    java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode, sharing)
tabula-py version: 1.4.3
platform: Windows-7-6.1.7601-SP1
uname:
    uname_result(system='Windows', node='L17CA-D7426CPS', release='7', version='6.1.7601', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

# What did you do when you faced the problem?
Upon facing the problem I tried the previous solutions, namely putting the PDF in the same folder as the executable and modifying my tabula-py version to 1.3.1. Neither fix was successful.

## Code:

```
    pdf_path = pdf_path
    output_path = output_path
    try:
        tabula.convert_into(pdf_path,pages='all', guess=False,output_format="CSV",output_path=output_path) #Try to convert the file
    except AttributeError:
        messagebox.showerror("Operation cancelled!", "In order to continue, please re-run the program and select a PDF file.")
```

## Expected behavior:

A .csv file with the tables that were contained within the PDF.

## Actual behavior:

![image](https://user-images.githubusercontent.com/46826008/70953425-10bab280-201e-11ea-876a-c3d71d478152.png)

## Related Issues:
#60 #93 #86

**Comment by chezou** [comment]
According to this thread, that should be your Pyinstaller usage problem, not tabula-py issue. https://github.com/pyinstaller/pyinstaller/issues/3480

It might help to set an environment variable to use the specific jar file.
https://tabula-py.readthedocs.io/en/latest/faq.html#i-want-to-use-a-different-tabula-jar-file

**Comment by MartinWeiss12** [comment]
Hey, did you ever get this working? I'm having the same issue and can't find a good solution. Thanks!

**Comment by cnmasami** [comment]
> Hey, did you ever get this working? I'm having the same issue and can't find a good solution. Thanks!

hey, using --add_data arg when runing Pyinstaller,  here is the manual: https://pyinstaller.org/en/latest/spec-files.html#adding-data-files

 pyinstaller -F MyFile.py  --add-data '.\venv\Lib\site-packages\tabula\tabula-1.0.5-jar-with-dependencies.jar;tabula'

and the delimiter between 'path\xxx.jar' and 'tabula', ';' for Windows, ':' for Linux

this works for me

**Comment by neetu73** [comment]
Hi I tried to solve this problem by using the above solution .
pyinstaller -F MyFile.py --add-data '.\venv\Lib\site-packages\tabula\tabula-1.0.5-jar-with-dependencies.jar;tabula'

but , this still seems to be throwing java not found error. Is there any other way that works?

**Comment by cnmasami** [comment]
I'm sorry, I don't see any other errors with this command. Maybe
double-check the path to your JAR file or the delimiter between
'path\xxx.jar' and 'tabula' to ensure they are correct.

neetu73 ***@***.***> 于2023年4月3日周一 02:19写道：
