### ISSUE TITLE
subprocess.CalledProcessError While extracting table from PDF using tabula-py

### ISSUE THREAD

**Issue by himsoni-cloud** [chezou/tabula-py#206]
I am using Tabula PDF library to extract the table from PDF and it is throwing error subprocess.CalledProcessError.

# Check list before submit

- [ ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)? Yes

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

```
Python version:
    3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Java version:
    java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)
tabula-py version: 2.0.2
platform: Windows-10-10.0.17763-SP0
uname:
    uname_result(system='Windows', node='USHYDHIMSONI9', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
```

If not possible to execute `tabula.environment_info()`, please answer the following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
import tabula
filepathout = "C:\\Users\\himsoni\\Desktop\PDF_extraction\\black_white_format\\Testing.pdf"
df= tabula.read_pdf(filepathout, pages = 1, stream='True', multiple_tables= True)
```

## Expected behavior:

```
Get the data frame of tabular data.
```

## Actual behavior:

```
 File "C:\Users\himsoni\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\himsoni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar', '--pages', '1', '--stream', '--guess', '--format', 'JSON', 'C:\\Users\\himsoni\\Desktop\\PDF_extraction\\black_white_format\\Testing.pdf']' returned non-zero exit status 1.
```

**Comment by himsoni-cloud** [comment]
[Testing.pdf](https://github.com/chezou/tabula-py/files/4071130/Testing.pdf)

**Comment by chezou** [comment]
Thanks for reporting. Unfortunately, this is not tabula-py's issue but tabula-java's one.

```
(.venv) ➜  tabula-py git:(master) ✗ java -jar tabula/tabula-1.0.3-jar-with-dependencies.jar Testing.pdf
Error: Error expected floating point number actual='-17.-21823'
```

Can you raise an issue on [tabula-java](https://github.com/tabulapdf/tabula-java/issues) repository?

**Comment by himsoni-cloud** [comment]
Thank you
