### ISSUE TITLE
Why use both -g and -a flags?

### ISSUE THREAD

**Issue by SergioGutTal** [chezou/tabula-py#21]
Why use both `-g` and `-a` flags in options for extracting specific area? Isn't `-g` overriding the `-a` flag? You mention that it does not work without the `-r` option. I just tried without `-r` and `-g` and it works good.

```java -jar ./tabula/tabula-0.9.1-jar-with-dependencies.jar -g -r -a "337.29,226.49,472.85,384.91" table.pdf```

**Comment by chezou** [comment]
I didn't find the evidence which `-g` overrides `-a`, but it overrides `-r`.
https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L224

Why don't you PR document fixing? ;)

**Comment by chezou** [comment]
As my further investigation, I understand what tabula-java's current implementation is around `-a`.

In short, the option around area will be considered as following order (left is strong):
`-r` = `-l` > `-g` > `-a`

1. with `-r/--spreadsheet` or `-l/--lattice` option
   It works as [SPREADSHEET mode](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L227) and ignores both `-g` and `-a`. 

2. with `-g/--guess` and `-a/--area` option
  It works as [BASIC mode](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L232). In that mode, after setting [an area](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L48), it will be overriden by [guess mode](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L376).

3. with only `-a` option
  It works as BASIC mode and area option will not be overridden.

Anyway, I think it depends on the tabula-java's implementation, but  I will fix my document.
