### ISSUE TITLE
Ignoring first line if it's table heading

### ISSUE THREAD

**Issue by vamshikrishnajr** [chezou/tabula-py#211]
# Summary of your issue

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL: ?

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [x] Paste the output of `python --version` command on your terminal: ?
- [x] Paste the output of `java -version` command on your terminal: ?
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [x] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
paste your core code which minimum reproducible for the issue
```

## Expected behavior:

```
write your expected output
```

## Actual behavior:

```
paste your output
```

**Comment by vamshikrishnajr** [comment]
https://www.state.nj.us/humanservices/dmahs/news/reports/enrollment_2018.pdf

**Comment by chezou** [comment]
this issue was closed because it did not follow the issue template
