### ISSUE TITLE
DataFrame truncated after reading in multiple columns. 

### ISSUE THREAD

**Issue by jfersec** [chezou/tabula-py#216]
DataFrame truncated with ... after reading in multiple columns larger than printable size.
# Summary of your issue
When using ``data = tabula.read_pdf_with_template(PATH,JSONFILE)``  

the DataFrame returned is truncated via, ... in order to print out,  
even the example for this on readthedocs show this behavior on the example provided.  

I suspect this related to pandas, but trying I am unsure how to provide pandas_options to prevent truncating the DataFrame.  

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL: ?

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
Python version:
    3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609]
Java version:
    openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
tabula-py version: 2.0.4
platform: Linux-4.4.0-1099-aws-x86_64-with-Ubuntu-16.04-xenial
uname:
    uname_result(system='Linux', node='ip-x', release='4.4.0-1099-y', version='#110-Ubuntu SMP Fri Nov 15 00:08:08 UTC 2019', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '16.04', 'xenial')
mac_ver: ('', ('', '', ''), '')

# What did you do when you faced the problem?
Documentation on pandas states a few things to try to get DataFrame to return without truncating:
yet trying to pass a panda option like {'display.max_colwidth': -1} does not work, presumably since this flag it not being mapped to anything related to display. Not sure what to pass to prevent truncation.   

## Code:

```
import tabula
>>> tabula.read_pdf_with_template(pdf_path, "/path/to/data.tabula-template.json")
```

**Comment by chezou** [comment]
This is not the bug of tabula-py. 

The omitted column comes from pandas. You can set `pd.options.display.max_columns = None`. 

Without `max_columns`:

![image](https://user-images.githubusercontent.com/916653/73735565-cf739300-4782-11ea-95ab-46082efb2006.png)

With `max_columns`:
![image](https://user-images.githubusercontent.com/916653/73735538-c682c180-4782-11ea-8f15-01f40cc6065a.png)


See also: https://stackoverflow.com/questions/47022070/display-all-dataframe-columns-in-a-jupyter-python-notebook/49841608
