### ISSUE TITLE
Unable to execute my script on client system

### ISSUE THREAD

**Issue by nitinvijay23** [chezou/tabula-py#22]
# Summary of your issue

I have developed a script using tabula-py and created an executable using pyinstaller which works fine on my PC but when I run it on my client's PC it gives me the error

'The system cannot find the file specified tabula/wrapper.py although the the file is already present in the executable folder in the correct path. Should the client needs to have java installed to run the script?

# Environment

- [x] `python --version`: 3.5
- [ ] `java -version`: 8
- [ ] OS and it's version: win8
- [ ] Your PDF URL:

# What did you do when you faced the problem?

I have created an executable file using pyinstaller.

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?

I want to run my executable file on a windows PC without java and python installed. I guess I need to install java on PC to run my executable.

**Comment by chezou** [comment]
@nitinvijay23 Could you fill the whole descriptions after environment? Without that information, I can't help you, so I have no choice but to close this issue.

**Comment by chezou** [comment]
I don't know what Pyinstaller is, but I guess it's pyinstaller problem. tabula-py requires Python and Java. If you need a desktop application, you can use original tabula.
http://tabula.technology/
