### ISSUE TITLE
WARNING: cmap format 4 subtable is empty

### ISSUE THREAD

**Issue by jonnyhoff** [chezou/tabula-py#225]
# Summary of your issue

Dataframe only has 1 line
```
Mar 22, 2020 9:49:24 PM org.apache.fontbox.ttf.CmapSubtable processSubtype4
WARNING: cmap format 4 subtable is empty
```

# Check list before submit

- [X] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [X] (Optional, but really helpful) Your PDF URL: ?

- [X] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.
```
Python version:
    3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Java version:
    openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment 19.9 (build 13.0.2+8)
OpenJDK 64-Bit Server VM 19.9 (build 13.0.2+8, mixed mode, sharing)
tabula-py version: 2.1.0
platform: Linux-5.5.10-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
uname:
    uname_result(system='Linux', node='', release='5.5.10-200.fc31.x86_64', version='#1 SMP Wed Mar 18 14:21:38 UTC 2020', machine='x86_64', processor='x86_64')
linux_distribution: ('Fedora', '31', '')
```
- [X] Paste the output of `python --version` command on your terminal: ?
- [X] Paste the output of `java -version` command on your terminal: ?
- [X] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [X] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
import tabula

# Read pdf into list of DataFrame
df = tabula.read_pdf("file.pdf",multiple_tables=True, pages='all')

print(df)
```

## Expected behavior:

```
Multiple lines
Multiple lines
Multiple lines
Multiple lines
```

## Actual behavior:

```
[Empty DataFrame
Columns: [1, 5.00, 1788.19, Skills, *****410.62]
Index: []]
```

**Comment by stygarfield** [comment]
What is an example of the PDF?

**Comment by chezou** [comment]
Thanks for reporting. However, without having a specific PDF, I can say nothing without reading this FAQ and try tabula.app.
https://tabula-py.readthedocs.io/en/latest/faq.html#i-got-a-empty-dataframe-how-can-i-resolve-it

If your data can read by tabula.app, please reopen this issue and attach an example PDF.
