### ISSUE TITLE
Merge pages in a PDF

### ISSUE THREAD

**Issue by Rakshasv18** [chezou/tabula-py#226]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is der a feature to merge tables in from different pages in a PDF ?
Is der a feature to select only particular table in PDF ?
After converting PDF to Excel can we merge all excel file ?

**Comment by chezou** [comment]
This issue is closed because it did not follow the issue template
