### ISSUE TITLE
Read_PDF generating single item list

### ISSUE THREAD

**Issue by clurra** [chezou/tabula-py#237]
When using the tabula.read_pdf for an online pdf files, I expected a dataframe output but seemed to receive a list with the entire table data as one item in the list.

# Check list before submit

- [ x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x ] (Optional, but really helpful) Your PDF URL: 
https://www.nar.realtor/sites/default/files/documents/ehs-03-2020-overview-2020-04-21.pdf

- [x ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
```Python version:
    3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)
tabula-py version: 2.1.0
platform: Windows-10-10.0.18362-SP0
uname:
    uname_result(system='Windows', node='SENE01-VM02', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '') 
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

I tried to manually convert the tabula.read_pdf() output as a DataFrame via pd.DataFrame(output) but the ouput was a single cell df that showed truncated part of the first text extracted from the pdf. ('Unnam...').
Tried searching StackOverflow for similar issues but did not find any.

## Code:

```
import tabula
df = tabula.read_pdf()("https://www.nar.realtor/sites/default/files/documents/ehs-03-2020-overview-2020-04-21.pdf")
print(df)

## output not as expected, used pd.DataFrame() in attmept to achieve df expected
df2 = pd.DataFrame(df)
```

## Expected behavior:

Expected a table output similar to the examples provided on GitHub.
https://github.com/chezou/tabula-py/blob/master/examples/tabula_example.ipynb

## Actual behavior:

A single cell dataframe that doesn't display any data as expected via the examples provided in the linked GitHub example python notebook.

**Comment by Npvel** [comment]
I have the same issue!

**Comment by psomhorst** [comment]
Same issue here.

**Comment by chezou** [comment]
I couldn't find any issue. As of tabula-py 2.0.0, `read_pdf()` returns a list of DataFrames. 
You can find an actual DataFrame with `df[0]` for example.

```
fname = "https://www.nar.realtor/sites/default/files/documents/ehs-03-2020-overview-2020-04-21.pdf"
>>> df = tabula.read_pdf(fname)
'pages' argument isn't specified.Will extract only from page 1 by default.
Got stderr: Jun 04, 2020 11:19:49 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Jun 04, 2020 11:19:49 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Jun 04, 2020 11:19:53 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 870 fonts

>>> df
[                                           Unnamed: 0      Unnamed: 1                       Unnamed: 2               Unnamed: 3  ... Unnamed: 10 Unnamed: 11 Unnamed: 12    Mos.
0                                                Year            U.S.                        Northeast                  Midwest  ...        West         NaN  Inventory*  Supply
1                                                2017      5 ,510,000                         7 40,000                1,300,000  ...           *         NaN   1,460,000     3.9
2                                                2018      5 ,340,000                         6 90,000                1,270,000  ...           *         NaN   1,530,000     4.0
3                                                2019      5 ,340,000                         6 90,000                1,250,000  ...           *         NaN   1,390,000     3.9
...snip...


[43 rows x 14 columns]]
>>> len(df)
1
>>> df[0]
                                           Unnamed: 0      Unnamed: 1                       Unnamed: 2               Unnamed: 3  ... Unnamed: 10 Unnamed: 11 Unnamed: 12    Mos.
0                                                Year            U.S.                        Northeast                  Midwest  ...        West         NaN  Inventory*  Supply
1                                                2017      5 ,510,000                         7 40,000                1,300,000  ...           *         NaN   1,460,000     3.9
2                                                2018      5 ,340,000                         6 90,000                1,270,000  ...           *         NaN   1,530,000     4.0
3                                                2019      5 ,340,000                         6 90,000                1,250,000  ...           *         NaN   1,390,000     3.9
...snip...
[43 rows x 14 columns]
```

**Comment by psomhorst** [comment]
Agreed this is not a bug, as the provided solution (i.e. the result is now returned in a list) works as intended. However, the documentation is outdated by this point and apparently confusing enough. Is there new documentation or a list of changes available?

**Comment by chezou** [comment]
@psomhorst  Ah, now I found the point you've mentioned. I thought I've updated the ipynb, and [API document](https://tabula-py.readthedocs.io/en/latest/tabula.html#tabula.io.read_pdf), but agreed to update the screenshot on the README, which shows the old version's output. Also, I've mentioned in the ipynb file to output list of DataFrames explicitly.

Other than that, I couldn't find an ambiguous point. If you find other points, could you send a PR for improvement?

**Comment by clurra** [comment]
Ah, I see I missed the indexing piece. Thank you both so much for clearing that up.
