### ISSUE TITLE
WARNING: No Unicode mapping for C14 (1) in font ECONFB+AdvP4C4E74

### ISSUE THREAD

**Issue by Ak784** [chezou/tabula-py#238]
# Summary of your issue

I am trying to read a pdf file that has a table in it. Though the installation is successful, I encounter the below error when I try to extract the table from the pdf and it returns 0 records

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL:  [https://www.ijidonline.com/article/S1201-9712(20)30141-7/pdf](url)

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

 `3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
tabula-py version: 2.1.0
platform: Windows-10-10.0.17134-SP0
uname:
    uname_result(system='Windows', node='1234-PC', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')`

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [x] Paste the output of `python --version` command on your terminal: yes, refer below

`Python version:
   

- [x] Paste the output of `java -version` command on your terminal: yes, refer below

`java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)` 
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [x] Write your OS and it's version:  windows 10,

# What did you do when you faced the problem?

## Code:

```
df = tabula.read_pdf('pd.pdf',multiple_tables=True)
```

## Expected behavior:

I expect to see the table from pdf in a dataframe

## Actual behavior:

empty dataframe with warning as given below

`'pages' argument isn't specified.Will extract only from page 1 by default.
Got stderr: May 22, 2020 12:11:26 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C14 (1) in font ECONFB+AdvP4C4E74
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: Your current java version is: 1.8.0_131
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: To get higher rendering speed on old java 1.8 or 9 versions,
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   update to the latest 1.8 or 9 version (>= 1.8.0_191 or >= 9.0.4),
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
May 22, 2020 12:11:26 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
May 22, 2020 12:11:27 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C14 (1) in font ECONFB+AdvP4C4E74`

**Comment by chezou** [comment]
You need to specify `pages` option. See FAQ https://tabula-py.readthedocs.io/en/latest/faq.html#i-got-a-empty-dataframe-how-can-i-resolve-it
