### ISSUE TITLE
tabula-py giving different result than tabula gui(Java)

### ISSUE THREAD

**Issue by rahulranjan07** [chezou/tabula-py#24]
# Summary of your issue
I'm trying to extract a portion of a pdf page using tabula-py api. But the end character of the last cell is missed when I run the code in python. I tried parsing it using the jar file provided on the tabula-java page, and it extracted all the cells character correctly

# Environment

Write and check your environment.

- [x] `python --version`: Python 2.7.12
- [x] `java -version`:  openjdk version "1.8.0_121"
                                OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
                                OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
- [x] OS and it's version: Ubuntu 16.04
- [x] Your PDF URL: https://services.skyteam.com/Timetable/Skyteam_Timetable_NA_EU.pdf 
                               Page 15

# What did you do when you faced the problem?

I tried parsing the page in tabula-java GUI. When it used the lattice extraction method, the character was misisng. But when I clicked the stream method of extraction the page was parsed correctly.

## Example code:

>> df = tabula.read_pdf("Skyteam_Timetable_NA_EU.pdf",pages="15",area= (55.781,306.797,75.119,580.497),spreadsheet=True)
>>list(df.head().keys())

## Output:

[u'FROM:', u'Detroit, USA', u'DT']

## What did you intend to be?

[u'FROM:', u'Detroit, USA', u'DTW']

**Comment by chezou** [comment]
By default, `tabula-py` uses `guess` option `True`. This opsion overwrite `area` option. Use opsions as follows:

```py
>>> df = tabula.read_pdf("Skyteam_Timetable_NA_EU.pdf",pages="15",area= (55.781,306.797,75.119,580.497), guess=False)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
>>> list(df.head().keys())
['FROM:', 'Detroit, USA', 'DTW']
```
