### ISSUE TITLE
read_pdf with byte variable

### ISSUE THREAD

**Issue by rspadim** [chezou/tabula-py#240]
**Is your feature request related to a problem? Please describe.**
could be possible instead of save a file (download from internet) i pass to read_pdf a byte variable?

something like:

import requests
import tabula
s = requests.Session()
r=s.get("url with pdf")
pdf_df=tabula.read_pdf(r.content)

**Describe the solution you'd like**
read_pdf from byte variable

**Describe alternatives you've considered**
save to a io.byte stream

**Additional context**
no one

**Comment by chezou** [comment]
Yes, it should work. `input_path` can be a file-like object.
https://tabula-py.readthedocs.io/en/latest/tabula.html#tabula.io.read_pdf

If you find an issue, let me know with another bug issue.
