### ISSUE TITLE
Table Row lines are being input as '_' symbols

### ISSUE THREAD

**Issue by Cazforshort** [chezou/tabula-py#243]
# Summary of your issue

Row lines that make up the table segments in my text pdf are being interpreted as '_' underscores.
When I zoom in on the pdf they might actually be underscores since I can highlight segments of it.

# Check list before submit

- [X] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
paste your core code which minimum reproducible for the issue
```

## Expected behavior:

```
write your expected output
```

## Actual behavior:

```
paste your output
```

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
