### ISSUE TITLE
Tabula app is able to extract pdf while tabula-py cant

### ISSUE THREAD

**Issue by jcabralc** [chezou/tabula-py#247]
# Summary of your issue

When using Tabula app it can extract all the information in the page
When using the tabula-py with templates, It extract's only a single line

The template I generated and downloaded from Tabula app

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL:  
[PDF link](https://github.com/chezou/tabula-py/files/4880925/pdf_paginas_interesse15_ocr.pdf)
[Tabula Template](https://github.com/chezou/tabula-py/files/4880930/tabula_template_jc.zip)

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
```
import tabula; tabula.environment_info()
Python version:
    3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Java version:
    java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
tabula-py version: 1.3.0
platform: Windows-10-10.0.18362-SP0
uname:
    uname_result(system='Windows', node='JESSICA-PC', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
linux_distribution: ('MSYS_NT-10.0', '2.10.0', '')
mac_ver: ('', ('', '', ''), '')
```
If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

I've also tried to use guess=True, lattice=True, multiple_tables=True, without a template, but nothing improved

## Code:

```
df = tabula.read_pdf_with_template(path_pdf, template_file, guess=False, stream=True)
```

## Expected behavior:

![tabulapp](https://user-images.githubusercontent.com/25270393/86633814-816bf100-bfa7-11ea-93bf-bf019e706f99.PNG)

## Actual behavior:

![tabulapy](https://user-images.githubusercontent.com/25270393/86633734-6ac59a00-bfa7-11ea-8e6e-8e2575c9d426.PNG)

```
Only NISSAN/KICKS is extracted
```

**Comment by chezou** [comment]
I double-checked the creation of a template, but by default, tabula app selects only NISSAN/KICKS row. Thus, tabula-py works as expected.

![image](https://user-images.githubusercontent.com/916653/86854610-aec5b580-c0f3-11ea-8177-9c712f8d95e6.png)
![image](https://user-images.githubusercontent.com/916653/86854585-a3728a00-c0f3-11ea-8b11-67e5b5793b5b.png)

After setting the selection manually, the template includes whole area.
![image](https://user-images.githubusercontent.com/916653/86854906-52af6100-c0f4-11ea-8d0a-26817d06ab37.png)
