### ISSUE TITLE
Getting list object as output for read_pdf instead of pandas dataframe

### ISSUE THREAD

**Issue by adithyaan-creator** [chezou/tabula-py#249]
# Summary of your issue

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [x] Paste the output of `python --version` command on your terminal: ?
- [x] Paste the output of `java -version` command on your terminal: ?
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [x] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
paste your core code which minimum reproducible for the issue
```

## Expected behavior:

```
write your expected output
```

## Actual behavior:

```
paste your output
```

**Comment by adithyaan-creator** [comment]
![image](https://user-images.githubusercontent.com/54103522/87936331-4641e580-cab0-11ea-990c-a7a54dd31722.png)

**Comment by chezou** [comment]
Please do not paste code snippets in images.

That is expected behavior as of tabula-py 2.0

**Comment by adithyaan-creator** [comment]
Is there any way to convert it to a pandas dataframe?
