### ISSUE TITLE
how can I extract all tables from a 30 pages pdf file

### ISSUE THREAD

**Issue by learner176** [chezou/tabula-py#25]
# Summary of your issue

# Environment

Write and check your environment.

- [ ] `python --version`: ?
- [ ] `java -version`: ?
- [ ] OS and it's version: ?
- [ ] Your PDF URL:

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by chezou** [comment]
Follow issue template.
