### ISSUE TITLE
Convert PDF to Any File With Template

### ISSUE THREAD

**Issue by risedangel** [chezou/tabula-py#250]
**Is your feature request related to a problem? Please describe.**
It seems that we can read a pdf with templates, yet we cant convert it to other file types. 

**Describe the solution you'd like**
just like read_pdf_with_template there shoul be an option called "convert pdf with template" . Also tabula GUI app craetes problems with  encoding. The preview works fine yet the exported data is problematic. Few characters are wrong though this is probably a encoding error. I dont know whether such problem may occur for this process. I can read the pdf with template without problem yet ı hope ı will be able to convert it without problems. 
**Describe alternatives you've considered**
I have tried tabula GUI app yet by bespoke it is problematic.

**Comment by chezou** [comment]
Thanks for raising a feature request. It'd be better to separate the feature request and the issue; the issue should be raised in tabula.app repo, I guess.

For your feature request, I'd recommend using pandas features like `DataFrame.to_csv` or whatever you want. For example, you can convert your df to TSV like:

```
df.to_csv('output.tsv', sep='\t', index=False)
```

Looking at the pandas doc, I can see it supports several formats as:

![image](https://user-images.githubusercontent.com/916653/88153159-ff82f580-cc3f-11ea-8b79-c36e4ca2ad98.png)

ref: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

As there's a way to convert into many formats through pandas, I don't think we don't have an explicit function like `convert_pdf_with_template`, but please let me know if this workaround doesn't fit your situation.

**Comment by risedangel** [comment]
thank you for quick reply. 

Now the problem is whenever i read a pdf with a template with the following command;
`tabula.read_pdf_with_template`
it returns the pdf as a list. So whenever i try to write it to an .xlsx file like the followng ;
`df.to_excel(r'<path to file>\aaa.xlsx',index=False)`

it says;
`AttributeError: 'list' object has no attribute 'to_excel' `

i think for df.to_excel command to work it should return a dataframe. What can we do to make it work?

**Comment by chezou** [comment]
tabula.read_pdf_with_template sould return a list of DataFrame. Can you iterate retuned list?

**Comment by chezou** [comment]
I think this feature request has provided a workaround. I close this issue at this moment but if you have any further requests for it, feel free to reopen it.
