### ISSUE TITLE
Unable to retrieve column names spread over multiple lines

### ISSUE THREAD

**Issue by DhruvAwasthi** [chezou/tabula-py#252]
# Summary of your issue
I'm trying to parse PDFs along with table data in reading order as they are found, for preprocessing the PDFs to build an NLP pipeline. For parsing tables, I'm really glad `tabula-py` is there. It works fine in most of the cases. But the problem arises when I try to read column names spread over multiple lines. It is not able to parse the column name correctly. For preprocessing task for NLP pipeline this is a must to understand table data. 
Please spare me, if I'm wrong.

# Check list before submit

- [Yes] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [[12.pdf](https://github.com/chezou/tabula-py/files/5000709/12.pdf)] (Optional, but really helpful) Your PDF URL: ?

- [Okay] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

`Python version:
    3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Java version:
    openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode)
tabula-py version: 2.1.1
platform: Linux-5.4.43-1-MANJARO-x86_64-with-arch-Manjaro-Linux
uname:
    uname_result(system='Linux', node='caesar', release='5.4.43-1-MANJARO', version='#1 SMP PREEMPT Wed May 27 20:25:12 UTC 2020', machine='x86_64', processor='')
linux_distribution: ('Manjaro Linux', '20.0.2', 'Lysia')
mac_ver: ('', ('', '', ''), '')`
    
If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?
I read the documentation and closed issues here on GitHub but nothing seems to help much.

## Code:

```
df = tabula.read_pdf("12.pdf", pages=1)
for i in df:
    print(i.columns)
```

## Expected behavior:

```
Index(['Office Organiza-tion', 'Operation Level', 'Applicable Manuals',
       'Required Training'],
      dtype='object')
```

## Actual behavior:

```
Index(['Office Organiza-', 'Operation Level', 'Applicable Manuals',
       'Required Training'],
      dtype='object')
```

## Related Issues:
No more issues. I'm loving it.

**Comment by chezou** [comment]
Try using `lattice=True` option for those tables having explicit lines around cells.

Note that using that option extracts extra area like warnings, so you need to access last dataframe.

**Comment by DhruvAwasthi** [comment]
This raises ambiguity in many cases. As setting `lattice=True` fails to distinguish actual tables and gives rectangle boxes as well.
 Please see the PDF attached when this issue was opened first.

**Comment by chezou** [comment]
I double-checked with/without `lattice=True` option, both work fine, containing Carriage Return `\r` though.

```py
In [1]: import tabula

In [2]: fname = "https://github.com/chezou/tabula-py/files/5000709/12.pdf"

In [3]: dfs = tabula.read_pdf(fname, lattice=True, pages=1)

In [4]: len(dfs)
Out[4]: 6

In [5]: dfs[-1].columns
Out[5]:
Index(['Office Organiza-\rtion', 'Operation Level', 'Applicable Manuals',
       'Required Training\rCourses'],
      dtype='object')

In [6]: dfs2 = tabula.read_pdf(fname, pages=1)

In [7]: len(dfs)
Out[7]: 6

In [8]: dfs[-1].columns
Out[8]:
Index(['Office Organiza-\rtion', 'Operation Level', 'Applicable Manuals',
       'Required Training\rCourses'],
      dtype='object')```
