### ISSUE TITLE
First line is ignored while Reading

### ISSUE THREAD

**Issue by Jagadeeshkb** [chezou/tabula-py#255]
The issue raises when the pdf has the incomplete borders in the first row in the table.
# Summary of your issue

# Check list before submit

- [ ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?
Yes
- [ ] (Optional, but really helpful) Your PDF URL: ?
Cant't Upload
- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
Python version:
    3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Java version:
    openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)
tabula-py version: 1.4.1
platform: Windows-10-10.0.18362-SP0
uname:
    uname_result(system='Windows', node='APCL20L6F1F2CE4', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('MSYS_NT-10.0-18362', '3.0.7', '')
mac_ver: ('', ('', '', ''), '')
If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?
![image](https://user-images.githubusercontent.com/50916738/89265324-ecb1ed00-d651-11ea-9031-18ba9f8894d3.png)

## Code:
import os
import tabula
os.chdir('C://python')
table  = tb.read_pdf("Core_Lib.pdf",multiple_tables = True,pages='35', lattice = True,stream = True)
```
paste your core code which minimum reproducible for the issue
```

## Expected behavior:

```
write your expected output
```

## Actual behavior:

![image](https://user-images.githubusercontent.com/50916738/89265375-02271700-d652-11ea-8807-56ec86cdabfb.png)

```
paste your output
```

**Comment by chezou** [comment]
I don't understand what issue is. Could you explain with text based expected/actual code and give an example PDF to reproduce. Screenshot doesn't help me to reproduce.
