### ISSUE TITLE
Characters out of the desired area are appearing in my tables

### ISSUE THREAD

**Issue by Pgovalle** [chezou/tabula-py#258]
# Summary of your issue
Some characters are leaking from useless cells to the output dataframe
# Check list before submit

- [ ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)? yes

- [ ] (Optional, but really helpful) Your PDF URL: https://www.cge.cl/wp-content/uploads/2020/08/Tarifas-de-Suministro-CGE-Agosto-2020.pdf

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
>>> tabula.environment_info()
Python version:
    3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Java version:
    openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
tabula-py version: 2.1.1
platform: Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
uname:
    uname_result(system='Linux', node='papo-MACH-WX9', release='5.4.0-42-generic', version='#46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '18.04', 'bionic')
mac_ver: ('', ('', '', ''), '')

# What did you do when you faced the problem?
Here is a specific problem, but it happens in a lot of parts in the results of any page
## Code:

top = 177.0
left = 66.0
buttom = 187.0
right = 698.0
table = tabula.read_pdf('https://www.cge.cl/wp-content/uploads/2020/08/Tarifas-de-Suministro-CGE-Agosto-2020.pdf',area= [top,left,buttom,right],pages=2,lattice=True, pandas_options={'header': None})
print(table[0].loc[0][25])

## Expected behavior:
20,274
## Actual behavior:
fijo2 0m,2e7n4s
Some of the characters in the index rows randomly appear in the dataframe

**Comment by chezou** [comment]
@Pgovalle Thanks for reporting the issue. I confirmed this behavior with the following code:

```
tabula.read_pdf('https://www.cge.cl/wp-content/uploads/2020/08/Tarifas-de-Suministro-CGE-Agosto-2020.pdf', pages=2, lattice=True)
```

Looks like the title `Cargo fijo mensual BT3` is somehow leaking.

However, this behavior comes from tabula-java by confirming the following command:

```
java -jar tabula/tabula-1.0.3-jar-with-dependencies.jar -p 2 --guess Tarifas-de-Suministro-CGE-Agosto-2020.pdf
```

Could you raise the issue to [tabula-java repo](https://github.com/tabulapdf/tabula-java/issues)?
