### ISSUE TITLE
Empty table is skipped in output

### ISSUE THREAD

**Issue by luke4u** [chezou/tabula-py#259]
**Is your feature request related to a problem? Please describe.**

My case is slightly special. I believe it is related to how tabula deal with empty tables. **If right, tablua ignores output if a table is empty.** 
Specifically, if I have 4 tables on a page, randomly. Each table only has 1 cell, and I know the coordinates of each cell. I want to use multiple-table options (False) and area option with a list of the coordinates. The current output is that the empty table is neglected in the output. Thus, I cannot map the table name to the table contents, as the empty table can be 1st or 3rd. Please see the below picture for what output looks like.  

Below is the code snippet. Note, `each_trade_coord` is a list of list with coordinates for each table. As you know, the output is a dataframe with each row representing a table. 
```
df_list = tabula.read_pdf(convert_pdf_nm, guess=False, pages=1, stream=True, encoding="utf-8",
                             multiple_tables=False, area=each_trade_coord, silent = True,
                             pandas_options={'header': None, "dtype": str, "keep_default_na": True, "skip_blank_lines": False}
                             )
```
**Describe the solution you'd like**

allow options to specify how users want to deal with empty tables. For instance, use spaces for cells in an empty table.

**Describe alternatives you've considered**

Tried a few pandas options, and failed: `"keep_default_na": True, "skip_blank_lines": False` 
Also I have considered not using the multiple-table options (False). Namely, one by one extraction. **But it is too slow if you have >3000 pages!**  **So speeding up the extraction is key for my case!**

**Additional context**

Below each row represents a table with only 1 cell. But there is an empty table gone. It makes it impossible to map to their corresponding table name. 

![image](https://user-images.githubusercontent.com/45267576/91493453-3e474380-e8af-11ea-982c-35b90531bfd1.png)
Below 2 empty tables are ignored.
![image](https://user-images.githubusercontent.com/45267576/91496479-1c03f480-e8b4-11ea-9c41-771fece75680.png)

Sorry if there is already some solution which I would love to know.

**Comment by chezou** [comment]
@luke4u Thanks for raising this issue. It looks like the difference with/without multiple_tables causes this error. I'd be willing to fix the issue.

However, it's a little bit hard without having minimum reproducible PDF, so could share me a PDF that reproduces the issue?

**Comment by luke4u** [comment]
Hi @chezou , thank you for help! 

PFA example file. To reproduce the result, pls try below. 
```
each_trade_coord = [[235, 132, 243, 232], [270, 446, 279, 606], [164, 446, 171, 546], [111, 685, 119, 745]]
df_list = tabula.read_pdf(file_path, guess=False, pages=1, stream=True, encoding="utf-8",
                          skip_blank_lines=False,
                          multiple_tables=False, area=each_trade_coord, silent=True,
                          pandas_options={'header': None, "dtype": str, "keep_default_na": True,
                                          "skip_blank_lines": False}
                          )
```

[example.pdf](https://github.com/chezou/tabula-py/files/5142632/example.pdf)

current output:

![image](https://user-images.githubusercontent.com/45267576/91579685-e4448d80-e943-11ea-9c9b-40a1d34fb6b5.png)

ideal output:
![image](https://user-images.githubusercontent.com/45267576/91580697-5ff30a00-e945-11ea-8033-6b40aeb84ed4.png)

**Comment by chezou** [comment]
I double checked with your example code and I found this isn't an issue of pandas option.

PDF specification doesn't have table info itself and tabula-java extracts with some heuristics. Need to include some column without empty. Here is the example by changing area width:


```
In [6]: dfs = tabula.read_pdf(fname, guess=False, pages=1, stream=True, area=(235,131,243,231), pandas_options={'header': None})

In [7]: dfs[0]
Out[7]:
                  0
0  FR00200073243272

In [8]: dfs2 = tabula.read_pdf(fname, guess=False, pages=1, stream=True, area=(227,22.49,288,211), pandas_options={'header': None})

In [9]: dfs2[0]
Out[9]:
                         0                 1
0                    ISIN:  FR00200073243272
1             Coupon Rate:               NaN
2             Pool Number:               NaN
3             By Order Of:               NaN
4  Sending/Receiving Bank:               NaN
```

The former is one table you've mentioned, and the latter is expected area that tabula-java can recognize empty value. I think we can change column "0" into index with some conversion.

Also, I checked the behavior of tabula-java,  but, unfortunately, it was same behavior of tabula-py, which means tabula-java can't handle empty table.
