### ISSUE TITLE
tabula read_pdf breaks up words in column names into separate columns

### ISSUE THREAD

**Issue by juliedrew** [chezou/tabula-py#261]
I'm using tabula to read tables in pdfs.

I'm finding that read_pdf unexpectedly breaks up the column names in the table. For example, the original table looks like this in the pdf:

https://i.stack.imgur.com/ZbRRA.png
Fig 1. Image of Table in PDF

However when I use tabula.read_pdf() the dataframe that is extracted breaks up the words in the column names. It looks like this:

https://i.stack.imgur.com/1sxIK.png
Fig 2. Screenshot of tabula dataframe extracted

Notice that it finds 8 separate columns when there are only 4. What could cause that?

The options I'm using are:

guess=False    
pandas_options={"header": None}    
lattice=False

# Check list before submit

- [check] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)? yes

- [ ] (Optional, but really helpful) Your PDF URL: ? Can't share the PDF. It is sensitive.

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
Tabula version is "1.4.2"

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
Python 2.7.5
- [ ] Paste the output of `java -version` command on your terminal: ?
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
yes
- [ ] Write your OS and it's version: ?
CentOS Linux 7 (Core)

# What did you do when you faced the problem?

## Code:

```
        df = tabula.read_pdf(
            fp,
            pages=pageno,
            stream=True,
            guess=False,
            area=area,
            pandas_options={"header": None},
            silent=True,
            lattice=False,
        )
```

## Expected behavior:

The results I expected are something like this

```
0 Payment     Posting Date.   Paid Amount  Curr
1 NaN             NaN                   NaN                NaN
2 50xxxxx      Aug 11, 2020   13,531,846.41 EUR
```

## Actual behavior:

Screenshot of tabula dataframe extracted
https://i.stack.imgur.com/1sxIK.png

**Comment by chezou** [comment]
Thanks for your report. However, tabula-py 1.4.2 doesn't support Python 2.7 and 1.4.2 is a bit old version. Please try with the latest version and create another issue if needed.

Also, your code is incomplete and I can't say nothing to this kind of behavior without the PDF. Only thing I can advise without thePDF is column option.
