### ISSUE TITLE
Bugs when parsing merged header

### ISSUE THREAD

**Issue by adrienluitot** [chezou/tabula-py#270]
# Summary of your issue
Tabula doesn't seem to parse correctly tables with merged header column.
Example: 
![image](https://user-images.githubusercontent.com/23219818/100587100-71ef9a80-32f0-11eb-919a-bb4eabb507c0.png)

# Check list before submit
- [ x ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?
Yes

- [ x ] (Optional, but really helpful) Your PDF URL: ?
I can't in public.

- [  x ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL:
```
Python version:
    3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
Java version:
    openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
tabula-py version: 2.2.0
platform: Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
```
```
uname: Linux 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux
```

# What did you do when you faced the problem?
Just trying to extract tables from pdf.

## Code:
```python
pdf_file = tabula.read_pdf("file.pdf", multiple_tables=True, pages="all")
tabula.convert_into("file.pdf", "extracted_tables/file.json", output_format="json", pages="all")
```

## Expected behavior:
```json
{
    "top": 783.85,
    "left": 364.22,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "12:45"
},
{
    "top": 783.85,
    "left": 387.75,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "14:40"
},
{
    "top": 783.85,
    "left": 411.03,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "16:45"
},
{
    "top": 783.85,
    "left": 434.8,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "17:45"
},
```

## Actual behavior:
```json
{
    "top": 783.85,
    "left": 364.22,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "12:45"
},
{
    "top": 783.85,
    "left": 387.75,
    "width": 41.759979248046875,
    "height": 4.650000095367432,
    "text": "14:40 16:45"
},
{
    "top": 783.85,
    "left": 434.8,
    "width": 18.239990234375,
    "height": 4.650000095367432,
    "text": "17:45"
},
```
This is just a portion of the whole JSON extracted, it would be too long otherwise.
In this case I "lost" one column, with other similar cases I can "lose" more than one column.

**Comment by chezou** [comment]
Hi, thanks for your reporting.
Have you tried `lattice` option and/or `columns` option?
https://tabula-py.readthedocs.io/en/latest/tabula.html#tabula.io.build_options

If they don't work, I guess this is tabula-java limitation.

**Comment by adrienluitot** [comment]
Hello,
I have tried lattice and it didn't work.
I can't use columns because it needs automation, I have multiple pdf and I can't know where are the columns.

**Comment by chezou** [comment]
Understood.

Then, I can do nothing except for recommending creating tabula-java issue with minimal reproducible PDF.

**Comment by adrienluitot** [comment]
Okay I might try with tabula-java, otherwise I'll just fix it post extraction with a program. ^^

**Comment by davidwelshmd** [comment]
Thanks Adrien,
I have been having similar issues. i.e. tables missing whole columns etc.
As I am a beginner python programmer I have not got to grips with useing Github yet, so have not been able to submit all details there.
Looking forward to how you go with tabula-java if you go that route.
David WelshMelbourne Australiadavidwelshmd@yahoo.com
    On Wednesday, 2 December 2020, 01:15:48 am AEDT, Adrien Luitot <notifications@github.com> wrote:  
 
 


Okay I might try with tabula-java, otherwise I'll just fix it post extraction with a program. ^^

**Comment by adrienluitot** [comment]
Hello David,
Sorry for the late answer ^^

I didn't use tabula-java yet, I didn't have the time to try it.
Though, I think I will fix the problem myself after the exportation.

**Comment by davidwelshmd** [comment]
ok thanks for letting me know/
David
    On Friday, 4 December 2020, 07:42:59 pm AEDT, Adrien Luitot <notifications@github.com> wrote:  
 
 


Hello David,
Sorry for the late answer ^^

I didn't use tabula-java yet, I didn't have the time to try it.
Though, I think I will fix the problem myself after the exportation.
