### ISSUE TITLE
Issues finding a table that has top/bottom borders missing

### ISSUE THREAD

**Issue by 1andDone** [chezou/tabula-py#274]
# Summary of your issue

I'm experiencing issues finding a table that spans multiple pages and includes a page where the top and bottom border is missing. See below for an example:
![image](https://user-images.githubusercontent.com/63823064/111555347-9caa1580-875e-11eb-8476-a6ac09cf0265.png)

Hence, the table starts on one page, is continued on another page (with the top and bottom borders missing) and then is completed on another page.

# Check list before submit

- [X] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [ ] (Optional, but really helpful) Your PDF URL: ? See screenshot above.

- [X] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

```
Python version:
    3.8.2 (default, May  6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)]
Java version:
    java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
tabula-py version: 2.2.0
platform: Windows-10-10.0.19041-SP0
uname:
    uname_result(system='Windows', node='PC', release='10', version='10.0.19041', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:

```
from tabula import read_pdf

dfs = read_pdf('test.pdf', pages='all', multiple_tables=True, stream=True, pandas_options={'header': None})
```

This is not ideal but produces the expected behavior for that troublesome page:

```
df = read_pdf('test.pdf', pages=3, stream=True, relative_area=True, area=(5, 5, 90, 90), pandas_options={'header': None})
df = df[0].dropna(how='any').reset_index(drop=True)
```

## Expected behavior:

Expected one of the elements of `dfs` to be a 2x2 dataframe like below:

```
         0        1
0  R1C1 T3  R1C2 T3
1  R2C1 T3  R2C2 T3
```

## Actual behavior:

No dataframe object is found for the page missing top/bottom borders.

```
N/A
```

**Comment by chezou** [comment]
I think using `lattice=True` may help with dropping `stream=True` but I'm not sure that helps you. Could you share an example PDF that can reproduce the issue?

**Comment by malinova** [comment]
I have the same issue  with multiple tables in same pdf file, some of them spanning across two pages, missing top/bottom borders.  Rows with missing border are not recognized as being part of a table.
lattice-True does not help.

**Comment by PrateekGoyal18** [comment]
.

**Comment by constantin345c** [comment]
Hi, 
I have a file with the same issue as described: 

https://github.com/constantin345c/Misc/blob/bf66076c4d4b13f72ef90e505f6b9cdde36a2793/Sor%20Ilan%20Miron_2019_DEPUTAT_0965_17-03-2020_Anuala.pdf

@chezou would you be able to help please?

**Comment by chezou** [comment]
@constantin345c The PDF contains tables in table. I guess that's too hard to resolve. Ask on tabula-java issue instead.

**Comment by chezou** [comment]
Couldn't get example PDF for a month. Closing now.

Please open new issue with a reproducible PDF. I doubt this issue is limitation of tabula-java, though.
