### ISSUE TITLE
SIGABRT on Apple M1

### ISSUE THREAD

**Issue by mvanaltvorst** [chezou/tabula-py#287]
# Summary of your issue

https://github.com/tabulapdf/tabula-java/issues/435

    Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
    [Clang 11.0.1 ] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tabula
    >>> tabula.read_pdf("/Users/maurits/Downloads/test.pdf")
    'pages' argument isn't specified.Will extract only from page 1 by default.
    Error from tabula-java:
    
    
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/io.py", line 322, in read_pdf
        output = _run(java_options, kwargs, path, encoding)
      File "/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/io.py", line 80, in _run
        result = subprocess.run(
      File "/Users/maurits/miniforge3/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar', '--guess', '--format', 'JSON', '/Users/maurits/Downloads/test.pdf']' died with <Signals.SIGABRT: 6>.

This error happens on any PDF I try. I suspect this is a problem due to my CPU architecture, but I am not entirely sure unfortunately.

# Environment 
```
>>> import tabula; tabula.environment_info()
Python version:
    3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
[Clang 11.0.1 ]
Java version:
    openjdk version "16" 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode)
tabula-py version: 2.2.0
platform: macOS-11.4-arm64-arm-64bit
uname:
    uname_result(system='Darwin', node='Maurits-MacBook-Pro.local', release='20.5.0', version='Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101', machine='arm64')
linux_distribution: ('Darwin', '20.5.0', '')
mac_ver: ('11.4', ('', '', ''), 'arm64')
```

# What did you do when you faced the problem?

## Code:

```
tabula.read_pdf("test.pdf")
```

## Expected behavior:
Code reads PDF

## Actual behavior:
Java error. However, this error does not occur when I am using `brew --cask` installed tabula via the web interface.

**Comment by chezou** [comment]
Thanks for reporting. 

While I don't have M1 Mac, my friend tried to reproduce but couldn't achieve with Python installed by Homebrew. He succeeded to read examples/data.py in the repo.

> Python 3.9.5
openjdk 11.0.11
tabula-py: 2.2.0
macOS-11.4-arm64-arm-64bit

> > $ which python3
/opt/homebrew/bin//python3
> pip3 install tabula-py

It seems highly likely conda environment issue. Could you try with Python installed by Homebrew or official Python binary?

**Comment by showyou** [comment]
Hi mvanaltvorst,

You suspected that jar file is broken.
Did you try tabula java directory?
> $ java -Djava.awt.headless=true -Dfile.encoding=UTF8 -jar /Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar --guess --format JSON /Users/maurits/Downloads/test.pdf

If you pass the above command, then would you try to run python simply(for distinguish owing to tabula-py)
>>> import subprocess
>>> subprocess.run(['java', '-Djava.awt.headless=true', '-Dfile.encoding=UTF8', '-jar', '/Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar', '--guess', '--format', 'JSON', '/Users/maurits/Downloads/test.pdf'])

In my environment(M1 Air, Python3.9.6 aarch, OpenJDK 16.02 x64), it works.

**Comment by mvanaltvorst** [comment]
Hi showyou,

Unfortunately, the direct Java command also throws me the same SIGABRT.

```
~ java -Djava.awt.headless=true -Dfile.encoding=UTF8 -jar /Users/maurits/miniforge3/lib/python3.9/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar --guess --format JSON /Users/maurits/Downloads/test.pdf
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:532), pid=85146, tid=6403
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment Zulu16.28+11-CA (16.0+36) (build 16+36)
# Java VM: OpenJDK 64-Bit Server VM Zulu16.28+11-CA (16+36, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/maurits/hs_err_pid85146.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
[1]    85146 abort      java -Djava.awt.headless=true -Dfile.encoding=UTF8 -jar  --guess --format JSO
```

Even more interesting, running this command with brew's Tabula .jar gives me the same error:

```
~ java -Djava.awt.headless=true -Dfile.encoding=UTF8 -jar /Applications/Tabula.app/Contents/Java/tabula.jar  --guess --format JSON /Users/maurits/Downloads/test.pdf
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:532), pid=85163, tid=6147
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment Zulu16.28+11-CA (16.0+36) (build 16+36)
# Java VM: OpenJDK 64-Bit Server VM Zulu16.28+11-CA (16+36, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/maurits/hs_err_pid85163.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
[1]    85163 abort      java -Djava.awt.headless=true -Dfile.encoding=UTF8 -jar  --guess --format JSO
```

Using Azul's OpenJDK 16, ARM.
```
~ java --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode)
```

Might be a problem with my version of OpenJDK, really not sure where this issue belongs anymore.

**Comment by mvanaltvorst** [comment]
Success! Seems like there was a bug in OpenJDK + MacOS 11.4 that was resolved upstream 25 days ago. Uninstalling Azul's OpenJDK and building OpenJDK from source solved the problem.

    brew install -s openjdk
