### ISSUE TITLE
Misaligned columns when reading pdf tables

### ISSUE THREAD

**Issue by aliceedward** [chezou/tabula-py#288]
# Summary of your issue

Hey Chezou and fellow tabula users, I was trying to read some pdf tables of multiple pages into python dataframes. 
The pdf file can be found here: https://www.ffiec.gov/hmdaadwebreport/pdf/2004/Mica/temp/2004MA1_______________11500.pdf
Here is a screenshot of the table layout:
![original pdf](https://user-images.githubusercontent.com/26389068/128049711-2d45d51f-1422-4d4e-a665-91f67b9f3f4f.png)

Somehow several columns were crammed into one when I used tabula. 
df=tb.read_pdf('2004pmic_11500.pdf',pages=0,output_format="dataframe",guess=False,
                         area=(50,60,1000,2000),pandas_options={'skiprows': 13,'header': None}) 

The problem could not be fixed with df[1].str.split(' ', expand=True) function as the numbers became misplaced. 

Also tried the wrapper from tabula, but got the same result. I would greatly appreciate it if someone could give me a hand! Many thanks, Alice.

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL: ?
https://www.ffiec.gov/hmdaadwebreport/pdf/2004/Mica/temp/2004MA1_______________11500.pdf

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
Please find below some relevant environment info:
Python version:
    3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Java version:
    java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) Client VM (build 25.301-b09, mixed mode, sharing)
tabula-py version: 1.4.1
platform: Windows-10-10.0.18362-SP0
uname:
    uname_result(system='Windows', node='LAPTOP-0DEQ3DNM', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?
df[1].str.split(' ', expand=True)  but it did not help the situation :(

## Code:

```
import tabula as pd
df=tb.read_pdf('2004pmic_11500.pdf',pages=0,output_format="dataframe",guess=False,
                          area=(50,60,1000,2000),pandas_options={'skiprows': 13,'header': None})
```

## Expected behavior:

```
Correctly positioned numbers if possible :)
```

## Actual behavior:

![tabula result](https://user-images.githubusercontent.com/26389068/128049142-fb61de6f-af32-40e9-a229-79350fff98a8.png)

```

```

**Comment by chezou** [comment]
I think this PDF is too complex to parse with tabula-java because the header area is multiple lines with combined cells.

Two options come out with:
1. Use columns option to give expected boundaries
2. Give specific area excluding combined header columns

I tried option 2 and it looks better than your result.

```
import tabula
pdf_path = "https://www.ffiec.gov/hmdaadwebreport/pdf/2004/Mica/temp/2004MA1_______________11500.pdf"

dfs = tabula.read_pdf(pdf_path, pages=1, area=(142,87,520,830), stream=True)
dfs[0]
```

![image](https://user-images.githubusercontent.com/916653/128097915-2dfd6e76-7b92-4702-9057-64985d6a578f.png)

Note that extracting tabula with one pass for complex PDFs are really hard. It always happens something to tweak.

**Comment by aliceedward** [comment]
Hey chezou, thank you very much for your kind help! Correct, specific area parameters definitely help :)

**Comment by chezou** [comment]
Glad to hear that. Since this isn't a bug of tabula-py and can be tabula-java limitation. I'm going to close the issue.
