### ISSUE TITLE
When reading PDF that have forms - the form data doesn't come through when read

### ISSUE THREAD

**Issue by HarryMelamed** [chezou/tabula-py#289]
# Summary of your issue

Unable to access form data entered into a PDF

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

## Code:
import tabula

dataframe = tabula.read_pdf("CompleteMonitorForm.pdf",  pages="all", stream=True)

tabula.io.convert_into("CompleteMonitorForm.pdf","Complete.json","json")

print (dataframe)

```
paste your core code which minimum reproducible for the issue
```

## Expected behavior:

The data that has been entered into the form

```
write your expected output
```

## Actual behavior:

```
paste your output
PS C:\Users\hmelamed\Python_Basics\Traning> & C:/Users/hmelamed/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/hmelamed/Python_Basics/Traning/PDFRead.py
'pages' argument isn't specified.Will extract only from page 1 by default.
[                         MONITORING                                 Unnamed: 0
0     Is there APM  (monitoring) in                                        NaN
1                   place for prod?                                        NaN
2     If so, which APM?  New Relic,                                        NaN
3                 AppDynamics, etc?                                        NaN
4      Can the performance team get                                        NaN
5              access to the above?                                        NaN
6     Is there APM  (monitoring) in                                        NaN
7       place for test environment?                                        NaN
8     If so, which APM?  New Relic,                                        NaN
9                 AppDynamics, etc?                                        NaN
10     Can the performance team get                                        NaN
11             access to the above?                                        NaN
12                              NaN                                        NaN
13  If there is no APM in place can                                        NaN
14    your team supply time stamped                                        NaN
15     monitoring trace files using                                        NaN
16            VMSTAT, PERFMON, Etc?                                        NaN
17                              NaN                                        NaN
18                              NaN                                        NaN
19                     Architecture                                        NaN
20                             Unix                                        NaN
21                          Windows                                        NaN
22                              MVS                                        NaN
23                              NaN                                        NaN
24                    Test schedule  Who should be contacted or test schedule?
25                             Name                                 Email Role,   Testing Notification Who should receive performance test reports?
0                 Name                                   Email Role,   Defect mitigation If there are defects discovered Unnamed: 0
0              Name                           Email       Role]
PS C:\Users\hmelamed\Python_Basics\Traning> 

## Related Issues:

**Comment by HarryMelamed** [comment]
PS C:\Users\hmelamed\Python_Basics\Traning> & C:/Users/hmelamed/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/hmelamed/Python_Basics/Traning/PDFRead.py
Python version:
    3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Java version:
    java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b09)
Java HotSpot(TM) Client VM (build 25.291-b09, mixed mode)
tabula-py version: 2.2.0
platform: Windows-10-10.0.18363-SP0
uname:
    uname_result(system='Windows', node='USBILHMELAMED7', release='10', version='10.0.18363', machine='AMD64')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

PS C:\Users\hmelamed\Python_Basics\Traning>

**Comment by HarryMelamed** [comment]
Here is the PDF that I was trying to get the form data 
[CompleteMonitorForm.pdf](https://github.com/chezou/tabula-py/files/6964723/CompleteMonitorForm.pdf)

**Comment by HarryMelamed** [comment]
Same thing when I converted it to JSON.   No entered form data,

**Comment by chezou** [comment]
I believe tabula-java doesn't support form yet. Could you please ask tabula-java repository?
