### ISSUE TITLE
Unable to read Hyphen ( -) properly 

### ISSUE THREAD

**Issue by catchcharan** [chezou/tabula-py#29]
# Summary of your issue
X410-SATA-S28 text value in a pdf is getting converted as  X410?SATA?S28 into csv. this issue applicable for python and java versions on tabula.
# Environment
windows/linux
Write and check your environment.

- [ ] `python --version`: ? 2.7
- [ ] `java -version`: ? 1.7
- [ ] OS and it's version: ? windows/linux
- [ ] Your PDF URL: just pdf with one cell and the value X410-SATA-S28

# What did you do when you faced the problem?
I will replace ? with a hyphen in code temporarily
//write here

## Example code:

```
paste your core code
```
java -Xmx4080m -jar C:\Python27\lib\site-packages\tabula\tabula-0.9.2-jar-with-dependencies.jar --pages all --guess --format CSV --outfile C:\Meher\pricelistoutput.csv --spreadsheet C:\Meher\pricelist.pdf

## Output:

```
paste your output
X410?SATA?S28 

## What did you intend to be?

X410-SATA-S28

**Comment by chezou** [comment]
Basically, it is tabula-java's problem, but I think you should set appropriate locale.
https://github.com/tabulapdf/tabula-java/issues/143

**Comment by chezou** [comment]
@catchcharan I released tabula-py v1.0.0. I think this problem is resolved. Could you try it?

**Comment by chezou** [comment]
I found your code is using tabula-java. It is not tabula-py's issue.

**Comment by abedkhooli** [comment]
Trying v1 of tabula-py with Arabic pdf, text comes as ??s (same as command line in tabula-java. I am using Windows 10 and I guess it has to do with the jar file.
