### ISSUE TITLE
Not selecting all table data

### ISSUE THREAD

**Issue by alokghsingh** [chezou/tabula-py#293]
# Summary of your issue

Table 2 only selects partial table data

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?
Yes
- [x] (Optional, but really helpful) Your PDF URL: ?

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [x] Paste the output of `python --version` command on your terminal: ? Python 3.8.8
- [x] Paste the output of `java -version` command on your terminal: ? openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH` Y
- [x] Write your OS and it's version: ?
Windows 10

# What did you do when you faced the problem?
Only selects part of table data on the same page even with pages='all and multiple_table=True

## Code:

```
pdf_path = "cloud2.pdf"

dfs = tabula.read_pdf(pdf_path, stream=True,pages='all')
dfs[1]
```

## Expected behavior:

```
Did not select Exadata rows
```
[cloud.pdf](https://github.com/chezou/tabula-py/files/7358558/cloud.pdf)

## Actual behavior:

```
paste your output
```

## Related Is
[bom2.xlsx](https://github.com/chezou/tabula-py/files/7358557/bom2.xlsx)
sues:

**Comment by alokghsingh** [comment]
Not selecting Exadata rows from page#2/Table#2

**Comment by alokghsingh** [comment]
![image](https://user-images.githubusercontent.com/16858778/137608353-6492c3a4-9f51-41e9-8610-a04ea70c8434.png)
Same issue with app version...3 entries in page#2 not auto selected

**Comment by chezou** [comment]
@alokghsingh Thanks for reporting it. As you've tried by tabula app, it's the limitation of tabula-java logic. 

You need to set `area` option or create template from calibrated region on tabula app.
