### ISSUE TITLE
read_pdf() misses Bangla Unicode characters

### ISSUE THREAD

**Issue by Shareef509** [chezou/tabula-py#296]
# Summary of your issue

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL: [Sample PDF](https://drive.google.com/file/d/1shMJI7EDGmvmkL4hVaNoZQZZoZo0xPkj/view?usp=sharing)

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
 

> `Python version:
    3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Java version:
    openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
tabula-py version: 2.3.0
platform: Windows-10-10.0.19041-SP0
uname:
    uname_result(system='Windows', node='ENG401512', release='10', version='10.0.19041', machine='AMD64', processor='Intel64 Family 6 Model 78 Stepping 3, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
    `

# What did you do when you faced the problem?

## Code:

```
df = tb.read_pdf('pdfs/_2021-10-14.pdf', 
                 pages='3',
                 encoding='utf-8',
                 stream=True,
                )
df

```

### What's shown in the PDF
```
নাম: সুরনজিৎ সোম
পিতা: করুনা ময় সোম
````

### What I retrieve from directly copying from the PDF
I assume the file itself has encoding issue, so getting some unexpected characters. Which is still useful to replace with after mapping the correct one.
```
. নাম: ƀরনিজৎ Ïসাম
িপতা: কƁনা ময় Ïসাম
```

## Actual behavior:

```
      নাম: রনিজৎ সাম  \
    িপতা: ক না ময় সাম   
```
Where many characters are missed  by Tabula-Read

**Comment by chezou** [comment]
Thanks for reporting.

Unfortunately, I'm not familiar with Bengali (maybe?) so it's hard to say something without having the PDF. Can you provide an example PDF? Or, trying tabula-java would be good to determine whether the issue comes from tabula-java or not.

**Comment by Shareef509** [comment]
> Thanks for reporting.
> 
> Unfortunately, I'm not familiar with Bengali (maybe?) so it's hard to say something without having the PDF. Can you provide an example PDF? Or, trying tabula-java would be good to determine whether the issue comes from tabula-java or not.


Thank you for your response! 
Could you please check the PDF link updated above?

**Comment by chezou** [comment]
Thanks for providing the example PDF.

I'm still not sure what is the expected output for the PDF, but there are warnings from PDFbox those indicates original text has something wrong.

```
$  java -jar tabula/tabula-1.0.5-jar-with-dependencies.jar ~/Downloads/tbla-samp.pdf -t
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+207 (207) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+344 (344) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+234 (234) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+206 (206) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+383 (383) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+385 (385) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+276 (276) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+293 (293) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+279 (279) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+386 (386) in font CIDFont+F1
Nov 17, 2021 10:13:35 AM org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+354 (354) in font CIDFont+F1
জলা: মৗলভীবাজার উপেজলা:,,ীম,ল,,ইউিনয়ন: ওয়াড নং-০৮ ডাকঘর: ীম,ল,,ভাটার এলাকার,,কাড: ১৬৭৬,ভাটার এলাকার নাম: উিকল বাড়ী,,রাড
২৫০. নাম: মাঃ সিলম,,,,,২৫১. নাম: মাঃ সাখাওয়াত,,,সৗরভ ভঁূইয়া,,,,,
ভাটার নং: ৫৮১৬৭৬১১২৫৮১,,,,,ভাটার নং: ৫৮১৬৭৬১১২৫৮২,,,,,,,,
িপতা: মাঃ ল আিমন,,,,,িপতা: মাঃ ফেয়জ উি,,ন ভঁূইয়া,,,,,,
মাতা: মাছাঃ রিফয়া খাতুন,,,,,মাতা: িশউলী বগম,,,,,,,,
"পশা: ছা /ছা ী,জ তািরখ:২৮/০৩/২০০০",,,,,"পশা: ছা /ছা ী,জ",তািরখ:২১/০১/২০০২,,,,,,,
"িঠকানা: #৪০৯, আরামবাগ আর/এ, িমশনেরাড,",,,,,"ীম ল, িঠকানা: ০, উিকল বাড়ী",,"রাড,","পশপুর,","ীম ল,",মৗলভীবাজার,,,
মৗলভীবাজার,,,,,,,,,,,,,
"",,,,,,,,১৫,,,রিজে শন অিফসার,,
```

Looking at the thread in Stackoverflow, it can be an issue that the font of texts in PDF can't be converted.

https://stackoverflow.com/questions/58829597/how-to-solve-no-unicode-mapping-error-from-pdfbox
https://stackoverflow.com/questions/39485920/how-to-add-unicode-in-truetype0font-on-pdfbox-2-0-0

I think you need to contact the creator of PDF to resolve the issue.
