### ISSUE TITLE
Outputting Format w/ Multi Page PDF

### ISSUE THREAD

**Issue by adack123** [chezou/tabula-py#32]
# Summary of your issue
Hi there, 

I was curious if I'm missing something with regards to `convert_into`. I pulled down the repo and did a convert into with the example.pdf you provide for my own sanity check, and its only converting the first page of the PDF to a CSV. Is this normal behavior? Am I missing something important here?

Also, with the `options` does `format` actually work? I've been trying to use this for an outputted parse object to no avail.

Write and check your environment.

- [ ] `python --version`: 2.7
- [ ] `java -version`: 8
- [ ] OS and it's version: OS X El Capitan 10.11.6
- [ ] Your PDF URL: The example PDF

# Relevant Code

### Here's the issue with just the first page being output
![image](https://cloud.githubusercontent.com/assets/8890348/26221979/522007bc-3be6-11e7-9a15-fc2c675ae169.png)

### Here's the format options with `csv`
![image](https://cloud.githubusercontent.com/assets/8890348/26222078/ad58376c-3be6-11e7-8b59-a84e052f5064.png)

**Comment by GGPay** [comment]
Put parameter - pages="all" or specific pages ="1-2,3"

Take a look example in repository.

**Comment by adack123** [comment]
Nice, `convert_into('./examples/data.pdf', 'test.csv', output_format='csv', pages="all")` works. Have you used the `format` part of the options at all?

**Comment by GGPay** [comment]
Yeah, i've tried all 3 formats  and works fine. 
It might be super useful lib :)

convert_into("\data\data2.pdf", "\data\data2.tsv", pages="1-2",  output_format="tsv")
convert_into("\data\data2.pdf", "\data\data2.csv", pages="1-2",  output_format="csv")
convert_into("\data\data2.pdf", "\data\data2.json", pages="1-2",  output_format="json")

**Comment by chezou** [comment]
Thank you @GGPay for your supporting. It seems to be solved. 

@adack123  If you still have other problems, please file another issue.

**Comment by adack123** [comment]
@GGPay Thanks for the feedback. I wasn't really referring to the `output_format` but rather the `format` part of the options, unless they are one and the same. 

@chezou 
The docs say under options 
```
format (str, optional):
Format for output file or extracted object. (CSV, TSV, JSON)
```
Does this refer to `output_format`? I want to do something like, `read_pdf('foo.pdf', format='csv')`

**Comment by chezou** [comment]
Ah, I understand. The doc is old.

I assume you to use `output_format` rather than `format` directly.
https://github.com/chezou/tabula-py/blob/master/tabula/wrapper.py#L104-L115

**Comment by adack123** [comment]
@chezou 

Gotcha, format -> `output_format` 

What about in the `read_pdf` method? I see that you can return as JSON here, https://github.com/chezou/tabula-py/blob/master/tabula/wrapper.py#L48

What about CSV, etc?

**Comment by chezou** [comment]
I don't imagine the use case to convert into CSV. Converting CSV has a lot of options for that, so I don't want to think it is a tabula-py's responsibility.
 
Why don't you convert from data frame into csv using `pandas.DataFrame.to_csv()`?
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html

**Comment by adack123** [comment]
Yeah, I was sorting of thinking that was out of the scope of what tabula-py is used for. Anyways, thanks for the clarification on `format`

**Comment by chezou** [comment]
OK. I fixed the doc https://github.com/chezou/tabula-py/commit/d787adefaba6d0de9422473b79e55cb02cad7444
