### ISSUE TITLE
Allow columns to accept a string for relative area

### ISSUE THREAD

**Issue by tdpetrou** [chezou/tabula-py#326]
Currently, the `columns` parameter only accepts a list of floats, whereas tabula-java allows for percentages with `--columns %25,50,80.6`. This feature can still be processed with the `options` parameter, but, in my opinion, would be nicer to have directly with the `columns` parameter

**Comment by chezou** [comment]
tabula-py has the `relative_area` option. See document:
https://tabula-py.readthedocs.io/en/latest/tabula.html#tabula.io.read_pdf

**Comment by tdpetrou** [comment]
Thank you for the response. I see that parameter. But, even when set to `True`, the `columns` parameter does not work with relative positions. For example, `read_pdf(file, relative_area=True, columns=[30, 80, 95])`, uses points 30, 80, 95 and not relative area percentages.

**Comment by chezou** [comment]
Ah, understood. You mention about column, not area. That's valid request not supported yet.

Can you recreate the issue with complying the issue template? You can use feature request template.

**Comment by tdpetrou** [comment]
Sure thing. Thank you for making this package! I plan on releasing a short blog post on it next week.
