### ISSUE TITLE
Allow columns parameter to use relative area

### ISSUE THREAD

**Issue by tdpetrou** [chezou/tabula-py#327]
**Is your feature request related to a problem? Please describe.**

Currently, the `columns` parameter accepts a list of floats, which map to the horizontal location in points even when setting `relative_area` to `True`. The list of floats cannot represent relative position on the page.

**Describe the solution you'd like**

I would like the `columns` parameter to use relative position of the page width just like the `area` parameter does when `relative_area` is set to `True`.

**Describe alternatives you've considered**

This feature is able to be completed by setting the `options` parameter. For example `['--columns %25,50,80.6']`.

**Additional context**

I think it would be nice to have this feature directly available instead of using `options`.

**Comment by chezou** [comment]
Relative parameter for columns was introduced on tabula-java 1.0.4 https://github.com/tabulapdf/tabula-java/commit/a4e0d6c41a06bc6c06ef766562f3eeef5a38c22a

I haven't supported the feature yet, but it sounds reasonable to leverage it to tabula-py as well.

**Comment by chezou** [comment]
Implemented on #328. It's available on master branch. I'm going to release on PyPI after merging #329

**Comment by tdpetrou** [comment]
Amazing you work so fast. Thanks!

**Comment by chezou** [comment]
Released on PyPI as well https://pypi.org/project/tabula-py/2.6.0/

**Comment by tdpetrou** [comment]
Thanks again for doing this. Just created a blog post on tabula-py and showcased this new feature. https://www.dunderdata.com/blog/read-trapped-tables-within-pdfs-as-pandas-dataframes
