### ISSUE TITLE
Error tokenizing data. C error

### ISSUE THREAD

**Issue by rileyhun** [chezou/tabula-py#33]
# Summary of your issue

The following error appears Error 'tokenizing data. C error: Expected 4 fields in line 44, saw 5'

# Environment

Write and check your environment.

- [ ] `python --version`: 2.7
- [ ] `java -version`: 8
- [ ] OS and it's version: ?
- [ ] Your PDF URL:

I cannot post a url to the PDF because it is a bank statement, and thus contains confidential information

# What did you do when you faced the problem?

I am using the _read_pdf_ function to extract tables from PDFs. Try and Except was used to catch the errors for the pdf that tabula cannot read

## Example code:

```
 df = read_pdf(files[i], pages='all', encoding='ISO-8859-1', error_bad_lines=False)
```

## Output:

```
C:/Users/riley/Desktop/BankStatements/50139.pdf Error tokenizing data. C error: Expected 4 fields in line 44, saw 5
```

**Comment by chezou** [comment]
`error_bad_lines` doesn't worrk for now. 

This error occurs when a PDF includes concatinated cells or multiple tables. For multiple tables, you should set appropriate area (see FAQ). Or you just want to convert into csv, you can use `convert_into()`.

**Comment by chezou** [comment]
Added `multiple_tables` option. https://github.com/chezou/tabula-py/pull/34

Could you try it as follows?

```py
df = read_pdf(files[i], pages='all', encoding='ISO-8859-1', multiple_tables=True)
```

**Comment by rileyhun** [comment]
Thanks for your prompt response. I tried using the multiple_tables options and ran into some problems. 

1. some of the table values were extracted as column names. This wasn't a problem before. 
2. Since these PDFs I am trying to parse span multiple pages, each page becomes an element of the list in the output. Due to the error produced above, using _pandas'_ concat function to merge all the tables doesn't produce a desirable output

**Comment by chezou** [comment]
Understand. I hardcoded that behavior, but will change not to make the first line column name.

**Comment by chezou** [comment]
Fixed with header handling https://github.com/chezou/tabula-py/commit/76e86f4eb2246cbb2e68bc966567781af87683b4

**Comment by rileyhun** [comment]
Thanks so much! It's working great now.
