### ISSUE TITLE
tabula.io.read_pdf 'columns' argument change type annotation to Iterable[float]

### ISSUE THREAD

**Issue by Vaghinak-Vardanyan** [chezou/tabula-py#336]
**Is your feature request related to a problem? Please describe.**

The thing is that I tried to give some meaning to the coordinates and wanted to use NamedTuple instead of List, Tuple, etc. In case of the argument "area" it works as it uses more general typing - Iterable[float]. But columns typed as List[float] so the linter gives an error in that case.

**Describe the solution you'd like**

I wanted to suggest changing it to Iterable[float] as well if there is no any specific reason using List[float].

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by chezou** [comment]
Thanks for your feedback! 

I agree with your suggestion.
https://github.com/chezou/tabula-py/blob/3f76a3457223d904e6d9621b824e0a5eeafb1b89/tabula/io.py#L121

Unfortunately, I'm busy these days, and this is good for the first contribution. I'm looking forward to someone taking this opportunity!

**Comment by Vaghinak-Vardanyan** [comment]
> Thanks for answering. Indeed I would be happy to help.

**Comment by chezou** [comment]
Released on v2.7.0.
