### ISSUE TITLE
tabula.io.read_pdf argument "pandas_options" is being changed inside the function

### ISSUE THREAD

**Issue by Vaghinak-Vardanyan** [chezou/tabula-py#337]
**Is your feature request related to a problem? Please describe.**

In tabula.io.read_pdf when specifying "pandas_options" argument, it is being changed by inside the read_pdf function causing unexpected behavior. The think is when you call the function second time pandas_options is being empty and you are not getting what you want.

**Describe the solution you'd like**

I think in each case when pandas_options.pop is called, pandas_options.get can be used to avoid that behavior. 

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by chezou** [comment]
Thanks for raising the issue. It sounds like not a feature request but a bug.

Can you recreate the issue with the bug report format with minimum reproducible code?

Thanks for your cooperation!
