### ISSUE TITLE
module 'tabula' has no attribute 'read_pdf'

### ISSUE THREAD

**Issue by ragesz** [chezou/tabula-py#36]
Dear tabula Developers,

I just installed tabula on Windows 10 x64, Anaconda Python 3.6 with the following command:
`>c:\Programs\Anaconda\Scripts\pip.exe install tabula-py`

After that I restarted my python kernel and imported `tabula`:
```
import tabula
df = tabula.read_pdf('my_pdf')
```
But I get the following error message:

> AttributeError: module 'tabula' has no attribute 'read_pdf'

I checked the module folder in Anaconda (`c:/Programs/Anaconda/Lib/site-packages/tabula/`) and I found the 2 `jar` files and the 2 `py` files, and the `wrapper.py` contains the `read_pdf` function.

Can you help me why I'm not able to load this function? I tried to check the installed version but 

> AttributeError: module 'tabula' has no attribute '__version__'

By the way `pip` returned with a success message after install:

> Installing collected packages: tabula-py
> Successfully installed tabula-py-0.8.0

I use several external modules in Anaconda and never get any issue like this...

Thank you!

**Comment by chezou** [comment]
Could you please follow the issue template?

**Comment by priyanshuchauhan** [comment]
@ragesz  
```

from tabula import wrapper
df = wrapper.read_pdf('my_pdf')

```

**Comment by mitchbregs** [comment]
I am getting this error:

`AttributeError: module 'tabula' has no attribute 'convert_into'` and this error is occurring in this line: `tabula.convert_into(root.fileName, "_ExportedPDF-" + date_time + ".csv", output_format="csv", pages="all")` but when I change to `from tabula import wrapper` I get the error 'ImportError: cannot import name 'wrapper' from that line.

How do I fix this?

**Comment by chezou** [comment]
I think it will be resolved to remove `pip uninstall tabula`.
https://github.com/chezou/tabula-py/issues/42#issuecomment-314453215

**Comment by priyanshuchauhan** [comment]
@mitchbregs you've installed tabula instead of tabula-py
sudo pip install tabula-py

**Comment by Shivani2508** [comment]
Hello ,I am working with tabula to extract tables from the pdf but some pages are not being extracted by that and giving the error "AttributeError: 'NoneType' object has no attribute 'fillna'" What I concluded from observing the pdf is the pages having small table and large blank spaces are giving this error.

Please help to find the solution
Thank you

**Comment by braysonjohn148** [comment]
i tried all the above solution but still getting the same error:
Exception has occurred: ImportError
cannot import name 'wrapper' from partially initialized module 'tabula' (most likely due to a circular import) (/Users/mac/Documents/Python/Ratiba/tabula.py)

i have uninstalled tabula and installed tabula_py but still

Somebody please help

my code
from tabula import wrapper
df = wrapper.read_pdf('my_pdf')

**Comment by f0ti** [comment]
@braysonjohn148 The name of file should not be the same as the tabula module, which causes circular import as the error describes. So just change the filename

**Comment by bagcivan** [comment]
> @braysonjohn148 The name of file should not be the same as the tabula module, which causes circular import as the error describes. So just change the filename

I've been looking for the cause of the error for an hour. Thank you

**Comment by tauseefhashmi** [comment]
https://stackoverflow.com/questions/60377106/python3-module-tabula-has-no-attribute-read-pdf
Guys kindly read the above thread.

For everyone who has problem with tabula.read_pdf  try using tabula.io.read_pdf it worked for me.And also import like this
from tabula.io import read_pdf
.
