### ISSUE TITLE
cant install tabula-py on m1 mac vscode.

### ISSUE THREAD

**Issue by jixx-choi** [chezou/tabula-py#366]
using m1 mac
i'm trying to install tabula-py but i cant.
i installed 
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

Python 3.12.0 x64

# Summary of your issue

# Check list before submit

- [ ] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?
- [ 
- Yes I did
- ] 

- [ ] (Optional, but really helpful) Your PDF URL: ?

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
- [ 
- >>> import tabula; tabula.environment_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tabula' has no attribute 'environment_info'
] 

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: ?
- [ ] Paste the output of `java -version` command on your terminal: ?
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [ ] Write your OS and it's version: ?

# What did you do when you faced the problem?

googled it and tried to delete tabula then install tabule-py.
-> failed.
tried to install jpype1 but it released win version only
-> failed.

## Code:

```
def convert_pdf_to_excel(pdf_path, excel_path):

    df = tabula.read_pdf(pdf_path, pages='all')
    

    writer = pd.ExcelWriter(excel_path)
    for i, data in enumerate(df):
        data.to_excel(writer, sheet_name=f'Sheet{i+1}', index=False)
    writer.save()


pdf_path = './input.pdf'
excel_path = './output.xlsx'


convert_pdf_to_excel(pdf_path, excel_path)
```

## Expected behavior:

```
write your expected output
```

## Actual behavior:

```
<img width="1296" alt="スクリーンショット 2023-11-09 19 00 51" src="https://github.com/chezou/tabula-py/assets/111183870/ca27ef4e-da8b-4d97-9b98-f1d97143e5f0">

```

**Comment by chezou** [comment]
Thanks for creating an issue. Can you please fill the check list appropriately? I can't help without having them. Also, please stop copy and paste with the image.

I will close the issue since it doesn't comply issue template. However, feel free to ping me once you fill the list. I will reopen it. Thanks!
