### ISSUE TITLE
Java issue with linux 64-bit using any java version

### ISSUE THREAD

**Issue by duduvz14** [chezou/tabula-py#37]
I am trying to run a simple test to scrape a table from a pdf using 
`df = read_pdf_table("./test.pdf", guess=False)`
But, i get 
`CalledProcessError: Command '['java', '-jar', '/home/duduvz14/anaconda3/lib/python3.6/site-packages/tabula/tabula-0.9.2-jar-with-dependencies.jar', '--pages', '11', './test.pdf']' returned non-zero exit status 1.`
I am using Ubuntu linux 64-bit and already attempted using Java 6, 7 and 8 but the error persists
Thanks in advance for the support

**Comment by chezou** [comment]
Please follow the issue template. It seems you should set PATH to java.
