### ISSUE TITLE
Pls add "orientation" parameter to read_pdf

### ISSUE THREAD

**Issue by EZcat335** [chezou/tabula-py#374]
### Is your feature request related to a problem? Please describe.

Today the Tabula (which is pretty great) reads text in both vertical and horizontal orientation alike.
When there is a page where there is a mix of them (for whatever reason) - results are typically messed-up.

### Describe the solution you'd like

Add a parameter to read_pdf
orientation="vertical" or "horizontal" or "any"
"Any" is what we all get today by default.
"vertical" will ignore all text written horizontally,
"horizontal" will ignore all text written vertically

### Describe alternatives you've considered

selecting only the right-orientation areas with a template.
This solution only works per-specific PDF file, it does not scale to many different PDFs

**Comment by chezou** [comment]
Thanks for sharing your idea.

I did a brief investigation, and I found that PDF doesn't have a concept of "vertical" or "horizontal": https://stackoverflow.com/questions/12050743/how-to-find-whether-pdf-has-landscape-orientation-or-portrait

Also, tabula-py is just a wrapper of tabula-java; ideally, they should handle it. If tabula-java appends rotation data as metadata into JSON output format, that kind of option would be possible. However, with the limited information, it's hard to achieve it by tabula-py.

**Comment by chezou** [comment]
Haven't heard back about the definitions of "vertical" and "horizontal". Closing the issue for now. It'd be better to ask on tabula-java issue.

**Comment by EZcat335** [comment]
Yes, I understand.
But it does have Rotation property. Yay, we can use it!
[Rotation = All] - default as today
[Rotation = 90, 180] - list of rotations that will be filtered.
It is up to the user to specify which ones he/she wants.
Yes, 90 with Portrait is not the same as 90 with Landscape, but let the
user figure this out.

Oftentimes there are hundreds of pages that need to be processed - and they
are all in the same orientation, so this filtering will be super
super helpful.

**Comment by chezou** [comment]
Thanks for the response. 

I made another investigation for the rotation, and I understood that the option is too much for tabula-py since it doesn't read the actual PDF on its own.
https://stackoverflow.com/a/40630514/3762316

It'd be great for tabula-java to add this feature instead.
