### ISSUE TITLE
FutureWarning: errors='ignore' is deprecated and will raise in a future version.

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [chezou/tabula-py#379]
### Summary

Getting a warning

### Did you read the FAQ?

- [X] I have read the FAQ

### Did you search GitHub Discussions?

- [X] I have searched the discussions

### About your environment

```markdown
- Python 3.10.13
- openjdk version "11.0.16.1" 2022-08-12 LTS
- OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
- OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
- Windows 11
```

### What did you do when you faced the problem?

I just rand the `read_pdf()` function

### Code

```py
from tabula import read_pdf

read_pdf(<PATH TO PDF>, pages="all")
```

### Expected behavior

NA

### Actual behavior

<PATH TO POETRY ENV>/lib/site-packages/tabula/io.py:1045: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead

    df[c] = pd.to_numeric(df[c], errors="ignore")

**Comment by Siddhesh-Agarwal** [comment]
So, It seems from the error message that [this line](https://github.com/chezou/tabula-py/blob/235e25c94e082d7eb5e1559a0360cb59820abbdd/tabula/io.py#L1049) is the cause of the warning.

**Comment by chezou** [comment]
@Siddhesh-Agarwal Thank you for reporting. I made a patch to suppress the warning. Please have a try with master branch.

**Comment by chezou** [comment]
Released https://pypi.org/manage/project/tabula-py/release/2.9.1/
