### ISSUE TITLE
Column header

### ISSUE THREAD

**Issue by thisss** [chezou/tabula-py#38]
# Summary of your issue

I am extracting data from a table using the "guess=True" option. Unfortunately, the first row is imported as column header. (The guess is not really wrong, since the typeface is bold and there is a line below it, see [Example](https://esv.ch/documents/ranglisten/2017-06-05_12_Schwingertag_Laupen-ST.pdf).) I didn't find I way to tell read_pdf_table not to treat the particular first line as column header. 

Would it be possible to add a "header=None" option?

**Comment by chezou** [comment]
Good point. Currently, you can get without header using `multiple_tables=True`, but I will add `pandas_options` to `read_pdf()`

**Comment by chezou** [comment]
@thisss I added `pandas_option` in #39 . Bump up and try it.

**Comment by memilanuk** [comment]
Sorry to bother you... but how specifically should this be called?  I'm having a similar issue - first line is being turned into a header when it should not.  I've been trying to add pandas_options to my code, but nothing I try works.  Probably a very simple syntax snafu on my part, but an actual example would be nice.

**Comment by chezou** [comment]
@memilanuk I think you can write as follows:

```py
read_pdf(target_pdf, pandas_options={'header': None})
```

see also https://github.com/chezou/tabula-py/blob/3ca05b03887537ed905c86a0aedf2178c293ce8a/tests/test_read_pdf_table.py#L53-L75

**Comment by sprog** [comment]
Hi, I have a pdf that has multiple tables. Table data is being extracted correctly; but the column headings are not. The headings are for 5 columns and the headings cover multiple lines. The first line has 5 headings, the 2nd-5th lines have heading continuation but not for the 1st column:

e.g.

head1        head2    head3    head4     head5
                  head2    head3    head4     head5  
                  head2    head3    head4     head5
                  head2    head3    head4     head5

Is thjere a way I can handle this please?

**Comment by sprog** [comment]
Sorry last three heading lines I indented but did not align under correct headn.
