### ISSUE TITLE
[BUG] <FutureWarning: errors='ignore' >

### ISSUE THREAD

**Issue by raimondskrauklis** [chezou/tabula-py#385]
### Summary

Getting future warning about deprecated functionality

### Did you read the FAQ?

- [X] I have read the FAQ

### Did you search GitHub Discussions?

- [X] I have searched the discussions

### About your environment

```markdown
Python version:
    3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Java version:
    java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
tabula-py version: 2.9.0
platform: Windows-10-10.0.22621-SP0
uname:
    uname_result(system='Windows', node='DESKTOP-0ATBQ2G', release='10', version='10.0.22621',
```

### What did you do when you faced the problem?

'tabula-py' is working great, but getting future warning:
lib\site-packages\tabula\io.py:1045: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[c] = pd.to_numeric(df[c], errors="ignore")

### Code

def remove_unnamed_columns(df):
    # Remove 'Unnamed: 0' and 'Unnamed: 1' columns if they exist
    df = df.drop(columns=['Unnamed: 0', 'Unnamed: 1'], errors='ignore')
    return df

### Expected behavior

Keep code running when Pandas deprecate "errors='ignore' " .

### Actual behavior

Getting error:
errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead

**Comment by chezou** [comment]
Duplicated https://github.com/chezou/tabula-py/issues/379
It's not an error, but a warning.

I will release 2.9.1 to PyPI once I fix the deployment GH Actions. Meanwhile, please try the master branch.

**Comment by chezou** [comment]
Released https://pypi.org/manage/project/tabula-py/release/2.9.1/

**Comment by raimondskrauklis** [comment]
Thank You, no more 'FutureWarning'
