### ISSUE TITLE
Problem in output table characters

### ISSUE THREAD

**Issue by DsDastgheib** [chezou/tabula-py#396]
### Summary

It seems it output a table with correct dimension but the content of each cell is ??????

### Did you read the FAQ?

- [X] I have read the FAQ

### Did you search GitHub issues?

- [X] I have searched the issues

### Did you search GitHub Discussions?

- [X] I have searched the discussions

### (Optional) PDF URL

https://drive.google.com/file/d/1OW0EBy_HpTJFyMpA3CyD7_G-3tQeX1su/view?usp=sharing

### About your environment

```markdown
tabula.environment_info()

Python version:
    3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Java version:
    java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
tabula-py version: 2.9.3
platform: Windows-10-10.0.22000-SP0
```

### What did you do when you faced the problem?

![image](https://github.com/user-attachments/assets/e1e15c30-4c70-4e05-b484-2a9ffedb561d)

### Code

df = tabula.read_pdf("sktech.pdf", pages='all')
df[0]

### Expected behavior

A dataframe containing the following items:

<html>
<head><style>

</style></head><body>

سلام | ستون ۲
-- | --
۲۵۵۴۶ .۰ | محتوای یک
۸۵۹۴۳۱۵ | محتوای دو
۱۰۰۰۰۲۳ | محتوای سه
۳۵۴ | محتوای ۴

 
<br style=" font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; ">

</body>
</html>

### Actual behavior

cell content are ???????

**Comment by chezou** [comment]
This is an issue written in the FAQ. https://tabula-py.readthedocs.io/en/latest/faq.html#i-got-character-with-results-on-windows-how-can-i-avoid-it
Please have a look at it.

Or, you may be able to install with jpype to avoid it.
