### ISSUE TITLE
wrapper.py and tabula jar are missing

### ISSUE THREAD

**Issue by Wind1002** [chezou/tabula-py#42]
# Summary of your issue
I can import the library tabula, but the functions are still inaccessible. I checked the directory \site-packages\tabula. The wrapper.py and tabula jar file are missing.
# Environment

Write and check your environment.

- [x] `python --version`:  Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
- [x] `java -version`:  java version "1.8.0_131"
- [x] OS and it's version: Windows 10 64 bit
- [ ] Your PDF URL: 

# What did you do when you faced the problem?
 I tried to manually place them in the directory and run again. But it still doesn't work. 

## Example code:

```
df = tb.read_pdf("D:\\pdf table extract\\clarkfilterdcccrossref.pdf")
```

## Output:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-df8599025f3b> in <module>()
      1 #df = pd.DataFrame()
----> 2 df = tb.read_pdf("D:\\pdf table extract\\clarkfilterdcccrossref.pdf")
      3 tb.convert_into("D:\\pdf table extract\\clarkfilterdcccrossref.pdf","output.csv",output_format="csv")

AttributeError: module 'tabula' has no attribute 'read_pdf'
```

## What did you intend to be?
Read the pdf file.

**Comment by chezou** [comment]
Don't you install [`tabula`](https://pypi.python.org/pypi/tabula) instead of `tabula-py`? How did you install tabula-py?

I confirmed that error after the installation of `tabula`. After removing `tabula`, please re-install tabula-py.

```
pip uninstall tabula
pip install tabula-py
```

**Comment by chezou** [comment]
@Wind1002 If the solution does not work, please provide further information and reopen this issue.
