### ISSUE TITLE
cannot import name 'read_pdf'

### ISSUE THREAD

**Issue by akkaul** [chezou/tabula-py#44]
# Summary of your issue
Hello! I tried using tabula package to import some data in pdf but I got an error. I tried the command - from tabula import read_pdf. This gave me an error - cannot import name 'read_pdf'

I installed tabula-py package. 

# Environment

- [ ] python 3.6.1
- [ ] macOS Sierra 10.12.5

# What did you do when you faced the problem?

## Example code:

```
from tabula import read_pdf
```

## Output:
---------------------------------------------------------------------------

```
ImportError                               Traceback (most recent call last)
<ipython-input-30-59770b1fd371> in <module>()
----> 1 from tabula import read_pdf

ImportError: cannot import name 'read_pdf'
```

**Comment by akkaul** [comment]
this issue is solved. thanks!

**Comment by Lumaess** [comment]
I also meet this problem, can I know how you solve this issue? thanks~

**Comment by chezou** [comment]
@Lumaess See the FAQ in README.
