### ISSUE TITLE
ImportError: cannot import name 'read_pdf'

### ISSUE THREAD

**Issue by zlqs1985** [chezou/tabula-py#47]
# Summary of your issue
Hi, when I tried the example notebook note, anaconda IDE (spyder) gave me some error message
```
from tabula import read_pdf
Traceback (most recent call last):

  File "<ipython-input-25-59770b1fd371>", line 1, in <module>
    from tabula import read_pdf

ImportError: cannot import name 'read_pdf'
```
However, the following command works
`import tabula`

# Environment
anaconda (python 3.5) + windows10
Write and check your environment.

- [ ] `python --version`: ? 
- [ ] `java -version`: ?
- [ ] OS and it's version: ?
- [ ] Your PDF URL:

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by chezou** [comment]
See https://github.com/chezou/tabula-py/issues/42#issuecomment-314453215

If this solution is not appropriate, please reopen the issue.

**Comment by chezou** [comment]
Added FAQ https://github.com/chezou/tabula-py/commit/5c7cb8d0f267c7b68b6ba2213098f08e0bc67a6e
