### ISSUE TITLE
Some tables' numbers are extracted wrong from pdf

### ISSUE THREAD

**Issue by oryahud** [chezou/tabula-py#49]
# Summary of your issue
Some tables' numbers are extracted wrong from pdf
# Environment
[problem.pdf](https://github.com/chezou/tabula-py/files/1232750/problem.pdf)

- [ ] `python --version`: 3.6.2
- [ ] `java -version`: 1.8.0_144
- [ ] `tabula-py version`: 1.0.0
- [ ] OS and it's version: Windows 10
- [ ] Your PDF URL: [problem.pdf](https://github.com/chezou/tabula-py/files/1232756/problem.pdf)

# Steps to reproduce:
1. Read "problem.pdf" file.
2. Some numbers are wrong.
e.g: Line 6 : 3,797 -> 3,777, 5,317 -> 5,337 and there are some more...

## Example code:
df = read_pdf('problem.pdf')

## Other info:
Also reproduce on:
**tabula-java v1.01 with commad:**
 java -jar tabula-1.0.1-jar-with-dependencies.jar problem.pdf -o problem.csv
**tabula v1.1.1**

**Comment by chezou** [comment]
Thanks for reporting, but it seems tabula-java problem. Could you file [an issue on tabula-java])(https://github.com/tabulapdf/tabula-java/issues)?

**Comment by oryahud** [comment]
Thanks, I did.
https://github.com/tabulapdf/tabula-java/issues/180
