### ISSUE TITLE
When running the read_pdf_table has an attribute error

### ISSUE THREAD

**Issue by rigstechnology** [chezou/tabula-py#5]
File "/Users/nestordeharo/Documents/Python/scripts_automatizar/venv/lib/python2.7/site-packages/tabula/wrapper.py", line 74, in read_pdf_table
    result = subprocess.run(args, stdout=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'

**Comment by chezou** [comment]
Currently, we support only Python 3.5, but I will fix code to be compatible with 2.7.

**Comment by rigstechnology** [comment]
pre {font-family: sans-serif;white-space: pre-line !important;}

Thanks man

Great day

Nestor De Haro CEO Tel/Work: +52 33 8421-7447 Cel/Mobile: +52 1 33 1151-0605
http://www.rigs.com.mx/

On Mon, Sep 26, 2016 at 4:50 AM Michiaki Ariga

<
mailto:Michiaki Ariga <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Currently, we support only Python 3.5, but I will fix code to be compatible with 2.7.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/chezou/tabula-py/issues/5#issuecomment-249526835
, or

**Comment by chezou** [comment]
Fixed and bumped. You can install via pip install
