### ISSUE TITLE
Error tokenizing data

### ISSUE THREAD

**Issue by jainsourabh** [chezou/tabula-py#50]
# Summary of your issue
Error tokenizing data. C error: Expected 10 fields in line 18, saw 11
# Environment
Jupyter Notebook- Anaconda
Write and check your environment.

- [x] `python --version`: >3
- [ ] `java -version`: Version 8 update 111: 1.8.0_111
- [ ] OS and it's version: Mac OS Sierra 10.12.4
- [ ] Your PDF URL: http://www.wrldc.in/9_reportNew/dailydata_01082017.pdf

# What did you do when you faced the problem?

I used read_pdf on above url and I received this error:
"Error tokenizing data. C error: Expected 10 fields in line 18, saw 11"

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by chezou** [comment]
fill the example code and output, then reopen issue.
