### ISSUE TITLE
Repeating headers

### ISSUE THREAD

**Issue by pranali3215** [chezou/tabula-py#53]
# Summary of your issue

I have the same table continuing on multiple pages and on each page the header is written again. 
This makes sense in a pdf format, but not in a csv.

Is there a way so that it ignores the headers and only converts the table? 
For example, convert_without_header=True

**Comment by chezou** [comment]
According to this test case, the header could be multiline. https://github.com/tabulapdf/tabula-java/blob/0af623a6e0af756f71af417e3c9c5731e9f3f6bf/src/test/java/technology/tabula/TestBasicExtractor.java#L375

Currently, we can extract ignoring repeating header with extracting each page and dropping header, but it should be inefficient. If you want to efficient extraction, could you please file an issue on tabula-java?

**Comment by pranali3215** [comment]
Hi,

Thanks for the reply. 
I agree, that the current method is inefficient.

I have raised an issue with tabula-java for the same.
Here is the link: https://github.com/tabulapdf/tabula-java/issues/186

**Comment by raghurammanyam** [comment]
when i convert pdf into multiple pages ..the data is not reading from all the pages of pdf by using tabula

**Comment by chezou** [comment]
Close this issue since tabula-java issue was closed.

While I'm neutral for this feature, currently, I don't have any plan to implement it, but it would be nice to have a document for it, or PRs are welcome.
