### ISSUE TITLE
python Tabula : FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Raghav1990** [chezou/tabula-py#57]
# Summary of your issue
I'm getting an error while reading a pdf file via tabula 
# Environment

Write and check your environment.

- [ ] `python --version`:3 ?
- [ ] `java -version`: 8?
- [ ] OS and it's version: Win7 32bit ?
- [ ] Your PDF URL:

# What did you do when you faced the problem?

//write here
below is the code used
## Example code:

```
import tabula
df = tabula.read_pdf("D:/Users/rag/Documents/GE_Confidential/Projects/GE_Health_Care/pdf/test.pdf")
```

## Output:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-1c72e9de1c11> in <module>()
----> 1 df = tabula.read_pdf("D:/Users/rag/Documents/GE_Confidential/Projects/GE_Health_Care/pdf/test.pdf")

D:\Users\rag\AppData\Local\Continuum\Anaconda3\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     73 
     74     try:
---> 75         output = subprocess.check_output(args)
     76     finally:
     77         if is_url:

D:\Users\rag\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

D:\Users\rag\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    401         kwargs['stdin'] = PIPE
    402 
--> 403     with Popen(*popenargs, **kwargs) as process:
    404         try:
    405             stdout, stderr = process.communicate(input, timeout=timeout)

D:\Users\rag\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    705                                 c2pread, c2pwrite,
    706                                 errread, errwrite,
--> 707                                 restore_signals, start_new_session)
    708         except:
    709             # Cleanup if the child failed starting.

D:\Users\rag\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    988                                          env,
    989                                          cwd,
--> 990                                          startupinfo)
    991             finally:
    992                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## What did you intend to be?
i want to read a pdf table and convert it to data-frame for further analysis...
if there is any other alternative please let me know how to do it..

Many thanks in advance...

**Comment by chezou** [comment]
Thanks for reporting. It seems it is similar to [this thread](https://stackoverflow.com/questions/44490203/java-not-found-in-using-tabula-py). Could you show me outputs of `java -version` and `python --version` on your terminal?

**Comment by chezou** [comment]
No response here. I assume the problem is resolved with the previous comment. Please reopen setting PATH to java does not work.

**Comment by MurchC** [comment]
I've been having the exact same result. Running Java 1.8.0_144 Python 3.6.2


  File "C:\Users\Murch_000\Anaconda3\lib\subprocess.py", line 992, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ClementFeltin** [comment]
I also had the exact same error with Python 3.6.1 and Java 1.7.0_55-b13

~\Documents\Portable\anaconda\envs\py35_qt4\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    988                                          env,
    989                                          cwd,
--> 990                                          startupinfo)
    991             finally:
    992                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by chezou** [comment]
If you are Windows user, I recommend you to check the instruction of README.
https://github.com/chezou/tabula-py#get-tabula-py-working-windows-10

The key point of this issue is `java` command is not found from Python process. You should install Java and set the PATH appropriately.

**Comment by pauldewilson** [comment]
Also experiencing this issue

Java 1.8.0_261
Python 3.8.4

Attempting to run:

`import tabula
import os

os.chdir(r"C:\Users\me\Desktop")

files = ["Cape View Motel - Draft Projections.pdf", "Point of View Suites - Draft Projections.pdf"]
files

t = tabula.read_pdf(files[0], pages="all", multiple_tables=True)`

Which results in

`
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Roaming\Python\Python38\site-packages\tabula\io.py in _run(java_options, options, path, encoding)
     79     try:
---> 80         result = subprocess.run(
     81             args,

C:\Program Files (x86)\Python38-32\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    488 
--> 489     with Popen(*popenargs, **kwargs) as process:
    490         try:

C:\Program Files (x86)\Python38-32\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,

C:\Program Files (x86)\Python38-32\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1306             try:
-> 1307                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1308                                          # no special security

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

JavaNotFoundError                         Traceback (most recent call last)
<ipython-input-10-b830c9a1a05e> in <module>
      7 files
      8 
----> 9 t = tabula.read_pdf(files[0], pages="all", multiple_tables=True)

~\AppData\Roaming\Python\Python38\site-packages\tabula\io.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, user_agent, **kwargs)
    320 
    321     try:
--> 322         output = _run(java_options, kwargs, path, encoding)
    323     finally:
    324         if temporary:

~\AppData\Roaming\Python\Python38\site-packages\tabula\io.py in _run(java_options, options, path, encoding)
     89         return result.stdout
     90     except FileNotFoundError:
---> 91         raise JavaNotFoundError(JAVA_NOT_FOUND_ERROR)
     92     except subprocess.CalledProcessError as e:
     93         logger.error("Error from tabula-java:\n{}\n".format(e.stderr.decode(encoding)))

JavaNotFoundError: `java` command is not found from this Python process.Please ensure Java is installed and PATH is set for `java`
`
