### ISSUE TITLE
Can 'convert_into()' pdf file to json but executing 'read_pdf()' as json gives UTF-8 encoding error.

### ISSUE THREAD

**Issue by evanleeturner** [chezou/tabula-py#59]
# Summary of your issue

Can 'convert_into()' pdf file to json, but executing 'read_pdf()' as json gives UTF-8 encoding error.

# Environment

Write and check your environment.

- [ ] `python --version`: ? 3.6.1.final.0, jupyer notebook 5.0.0
- [ ] `java -version`: ?
- [ ] OS and it's version: ? win64 anaconda 4.3.22 
- [ ] Your PDF URL: https://www.dropbox.com/s/rg11o0iitia4zua/QA-17H104161-2017-09-22-DO.pdf?dl=0

# What did you do when you faced the problem?

I don't understand why the convert_into function works fine with this pdf, but passing the same pdf into read_pdf() yields an encoding error.  Shouldn't the default options for both functions be identical?  

## Example code:

```
from tabula import read_pdf
from tabula import convert_into
import pandas
file = 'T:/baysestuaries/Data/WDFT-Coastal/db_archive/QA/QA-17H104161-2017-09-22-DO.pdf'
convert_into(file,"test.json", output_format='json')
df = read_pdf(file, output_format='json')

```

## Output:

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-208-fc7babef8e03> in <module>()
----> 1 df = read_pdf(file, output_format='json')

C:\Users\ETurner\AppData\Local\Continuum\Anaconda3\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     90 
     91         else:
---> 92             return json.loads(output.decode(encoding))
     93 
     94     else:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 5134: invalid start byte

```

## What did you intend to be?

Ideally, the behavior of both functions should be identical.  I am actually trying to read this pdf as a pandas dataframe, but it is very messy.  Just reading it as a json works for me so I can parse out the items I need.  However, don't want to have to convert files first to waste disk space.

**Comment by chezou** [comment]
According to [this article](https://stackoverflow.com/questions/27340542/load-json-into-python-unicodedecodeerror), `json.loads(output.decode(encoding, 'ignore'))` would work.

`convert_into()` is just call Java process and tabula-java can handle appropriately.

**Comment by chezou** [comment]
@evanleeturner Is the encoding of the PDF really UTF-8? I wonder if it might be ISO-8859-1 like encoding.

**Comment by chezou** [comment]
Not the encoding of the PDF file, but you should align with the encoding of the terminal.

**Comment by evanleeturner** [comment]
UTF-8 should work.  I think the only questionable character is the temperature degrees ° .  The reason why I created the github issue ticket is I would expect those two functions to have the same behavior from looking at the documents.  EI. if the pdf should really fail because it's not UTF-8, it should fail in both functions.

**Comment by chezou** [comment]
tabula-py is a wrapper of tabula-java. tabula-py get tabula-java outputs via subprocess, which depends on the terminal encoding. Under the Windows environment, Java will not output with UTF-8 even if the PDF encoding is UTF-8. For example, we should set `encoding="cp932"` with Japanese Windows terminal.
I don't know what encodig your windows uses, but I think you should set appropriate encoding for the tabula-py option.

**Comment by evanleeturner** [comment]
thanks, doing "read_pdf(file, output_format='json', encoding='ISO-8859-1')" works with this file.

**Comment by chezou** [comment]
Great to hear that!
