### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by Allison418** [chezou/tabula-py#60]
# Summary of your issue
I received CalledProcessError when trying to read a pdf file.

# Environment
- python --2.7
- java -- 9
- OS -- anaconda 4.0.0

## Example code:
from tabula import read_pdf
df=read_pdf('D:\XXXX.pdf',page=1)
df

## Output:
CalledProcessError                        Traceback (most recent call last)
<ipython-input-7-911009276f0b> in <module>()
      1 from tabula import read_pdf
----> 2 df=read_pdf('D:\XXXX.pdf',page=1)
      3 df

C:\Users\legend\Anaconda2\lib\site-packages\tabula\wrapper.pyc in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     73 
     74     try:
---> 75         output = subprocess.check_output(args)
     76     finally:
     77         if is_url:

C:\Users\legend\Anaconda2\lib\subprocess.pyc in check_output(*popenargs, **kwargs)
    217         if cmd is None:
    218             cmd = popenargs[0]
--> 219         raise CalledProcessError(retcode, cmd, output=output)
    220     return output
    221 

CalledProcessError: Command '['java', '-jar', 'C:\\Users\\legend\\Anaconda2\\lib\\site-packages\\tabula\\tabula-1.0.1-jar-with-dependencies.jar', '--pages', '1', '--guess', 'D:\\XXXX.pdf']' returned non-zero exit status 1

**Comment by chezou** [comment]
Could you please paste the output of `java -version` on your terminal? Did you set the PATH to JAVA?

**Comment by chezou** [comment]
Similar question in the stackoverflow CalledProcessError

**Comment by chezou** [comment]
sorry mis pasting https://stackoverflow.com/q/45340256

**Comment by Allison418** [comment]
java -version  9.0.0

**Comment by Allison418** [comment]
I did pip install tabula-py , is there any problem with it?

**Comment by Allison418** [comment]
So is it that I should I should download java 7 or 8?

**Comment by Allison418** [comment]
Actually, I can read the sample data.pdf, but failed to read other pdf files on my computer, even the simple ones.

**Comment by chezou** [comment]
Ah ha. With the very limited info you gave, I guess it might be tabula-java's problem.

Could you file an [issue on tabula-java](https://github.com/tabulapdf/tabula-java/issues) with the output of the following command?

```
java -jar C:\Users\legend\Anaconda2\lib\site-packages\tabula\tabula-1.0.1-jar-with-dependencies.jar --pages 1 --guess D:\XXXX.pdf
```

**Comment by abhibisht89** [comment]
I am also having the same issue.
CalledProcessError                        Traceback (most recent call last)
<ipython-input-9-0928821b153b> in <module>()
      2 paths = [folder + fn for fn in os.listdir(folder) if fn.endswith('.pdf')]
      3 for path in paths:
----> 4     df = tabula.read_pdf(path, encoding = 'latin1', pages = 'all', nospreadsheet = True, error_bad_lines=False, multiple_tables=True)
      5     path = path.replace('pdf', 'xls')
      6     save_xls(df, path)

C:\Users\abhi\AppData\Local\Continuum\Anaconda3\lib\site-packages\tabula\wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     73 
     74     try:
---> 75         output = subprocess.check_output(args)
     76     finally:
     77         if is_url:

C:\Users\abhi\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    624 
    625     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 626                **kwargs).stdout
    627 
    628 

C:\Users\abhi\AppData\Local\Continuum\Anaconda3\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    706         if check and retcode:
    707             raise CalledProcessError(retcode, process.args,
--> 708                                      output=stdout, stderr=stderr)
    709     return CompletedProcess(process.args, retcode, stdout, stderr)
    710 

CalledProcessError: Command '['java', '-jar', 'C:\\Users\\abhi\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\tabula\\tabula-1.0.1-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--format', 'JSON', '--stream', 'C:/Users/abhi/Desktop/coal/coal1.pdf']' returned non-zero exit status 1

**Comment by shintojoseph1234** [comment]
you have to install java-jre and java-jdk which will solve the poroblem

sudo apt-get install default-jre

sudo apt-get install default-jdk

**Comment by Jaquedeveloper** [comment]
I am trying to generate an executable file which uses tabula-py lib. This library requires a jar file, tabula-1.0.1-jar-with-dependencies.jar, which I have in my file.py folder. 

When I run my code from command line, the function read_pdf(), from tabula-py, which uses the java jar, works all right, perfectly.

But when I generate the executable with pyinstaller, it fails to execute this function, giving the error below:

Unable to access jarfile C:\Users\jaquedeveloper\AppData\Local\Temp_MEI58442\tabula\tabula-1.0.1-jar-with-dependencies.jar

The file is not under this folder, nor the tabula folder exists. I have the file under the same folder of the executable file. How can I force the script to use it?

**Comment by VijayaLakshmiArthanari** [comment]
For windows system, How to install jdk and jre
