### ISSUE TITLE
Multiple tables in pdf

### ISSUE THREAD

**Issue by anilnaik1988** [chezou/tabula-py#61]
While i am trying to extract multiple tables from pdf using below command:-
convert_into("mypdf.pdf","outputables.csv",pages="all",multiple_tables="true",output_format="csv".
I am getting multiple tables but no delimiters are there in between the extracted tables. I would rather suggest to have some delimiters between tables in order to identify bw tables. Or is it my mistake in extracting tables.

**Comment by chezou** [comment]
Please comply the issue template.
