### ISSUE TITLE
Can only read Page 1

### ISSUE THREAD

**Issue by Allison418** [chezou/tabula-py#62]
# Summary of your issue
The file I tried to read has multiple pages and each page contains a chart, but read_pdf function can only read the first page of this file. Why is that?

# Environment
- [ ] `python --version`: 2.7
- [ ] `java -version`: 9

## Example code:
from tabula import read_pdf
df=read_pdf('D:\d.pdf',page=all)
df

**Comment by chezou** [comment]
Please comply the issue template. You should use all as a string like `page="all"` .
