### ISSUE TITLE
No delimiters between multiple tables extracted from PDF

### ISSUE THREAD

**Issue by anilnaik1988** [chezou/tabula-py#63]
Summary of your issue : While i am trying to extract multiple tables from pdf ;
I am getting multiple tables but no delimiters are there in between the extracted tables. I would rather suggest to have some delimiters between tables in order to identify bw tables. Or is it my mistake in extracting tables.

# Environment : Windows

Write and check your environment.

- [ ] Paste the output of `python --version` command on your terminal: ?Python 3.5.1
- [ ] Paste the output of `java -version` command on your terminal: ? java version "1.8.0_25"
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH` Yes its included in my PATH.
- [ ] Write your OS and it's version: ? Windows-7 
- [ ] (Optional, but really helpful) Your PDF URL: 

# What did you do when you faced the problem? 

i tried for solutions in stackoverflow and other relevant sites, as well searched in the github repo for tabula-py.

//write here

## Example code:

```
from tabula import convert_into
convert_into("input.pdf","output.csv",pages="all",multiple_tables="true",output_format="csv")
```

## Output:

```
Item No.,Q/TY,Description,Material,PN,Article No.,Type,DN
xx,yyy,zzzz,ttt,uuuu,vvvv,ttttyyy,"i"""
"Heat No.",?Max/Min Temperature,?Serial Number
"xxxx,",,
"yyy,",-29°C~175°C,
"zz,",,
```

## What did you intend to be?
```
Item No.,Q/TY,Description,Material,PN,Article No.,Type,DN
xx,yyy,zzzz,ttt,uuuu,vvvv,ttttyyy,"i"""
#some delimiters between tables..
"Heat No.",?Max/Min Temperature,?Serial Number
"xxxx,",,
"yyy,",-29°C~175°C,
"zz,",,
```

**Comment by chezou** [comment]
`convert_into` is just calling tabula-java. `multiple_tables` option doesn't work because it is for creating pandas DataFrame.

Without the PDF, I can't say anything, but I guess `guess`, `lattice`, `stream` options are related.   For further question, you should go to [tabula-java](https://github.com/tabulapdf/tabula-java/) issue.
