### ISSUE TITLE
guess = True?

### ISSUE THREAD

**Issue by ecatkins** [chezou/tabula-py#64]
In trying to switch from using subprocess/command line (tabula-java)  to tabula-py, I was getting different results for the following code:

Command line:
`java -jar tabula.jar -i -t /my/pdf_loc/my.pdf --area <area-string> -p <page-number>`

Tabula-py:
` options = '--area <area-string> -p <page-number> -i -t' ` 
`tabula.read_pdf('/my/pdf_loc/my.pdf', options = options) `

As far as I can tell, this issue was caused because the guess parameter in tabula-py is set to True by default (I was able to correct by including `guess = False` as a kwarg).

Should this be corrected so that the tabula-py reflects the default behavior of tabula-java?

**Comment by chezou** [comment]
I think many beginners assume behavior with guess True. It is same opinion as [tabulizer](https://github.com/ropensci/tabulizer)

**Comment by chezou** [comment]
And I don't recommend to use `options`, if not needed. I assume using keyword arguments.
