### ISSUE TITLE
Lattice command, not working as the same as online tabula.

### ISSUE THREAD

**Issue by mayurpande** [chezou/tabula-py#65]
------

# Summary of your issue

I am trying to use lattice, however I am unsure how to use it properly.

# Environment

Write and check your environment.

- [ ] Paste the output of `python --version` command on your terminal: ?
Python 2.7.12 (but am using virtual env so it is 3.5.2)
- [ ] Paste the output of `java -version` command on your terminal: ?
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
correct
- [ ] Write your OS and it's version: ?
Ubuntu 16.04 lts
- [ ] (Optional, but really helpful) Your PDF URL:
http://www.ndb.int/wp-content/themes/ndb/pdf/list-of-all-projects.pdf

# What did you do when you faced the problem?

Attempted to use tabula on 127.0.0.1:8080. To understand lattice more, can see that I can select the whole table by re-shaping before clicking lattice, however unsure how to do this in tabula-py

## Example code:

```
    from tabula import wrapper
    file_url = 'http://www.ndb.int/wp-content/themes/ndb/pdf/list-of-all-projects.pdf'
    wget.download(file_url)
    df = wrapper.read_pdf('list-of-all-projects.pdf',lattice=True,area=(45.497118155619596,54.596541786743515,379.14265129682997,784.9769452449567))
    df.to_csv('ndb.csv')

```

## Output:

a csv file with only one column.

[ndb.xlsx](https://github.com/chezou/tabula-py/files/1433742/ndb.xlsx)

Have uploaded as excel file for now as github doesn't support csv files

## What did you intend to be?
A csv file similar to the pdf.

**Comment by mayurpande** [comment]
Got it work with the code;

```
    df = wrapper.read_pdf('list-of-all-projects.pdf',
            lattice=True,
            area=(45.497118155619596,54.596541786743515,379.14265129682997,784.9769452449567)
            )

    df.to_excel('ndb.xlsx')

```
However when using csv file.

**Comment by chezou** [comment]
It seems setting area option had resolved correctly. Check extracted dataframe with area option.

BTW, I recommend you to use `convert_into` function to convert into csv.

**Comment by mayurpande** [comment]
Sorry to open this again. Do you mean use `convert_into` after I create the df?

**Comment by chezou** [comment]
See example code in Readme
https://github.com/chezou/tabula-py#example

**Comment by mayurpande** [comment]
originally I did but it didn't format it correctly, it put it all in one column

**Comment by chezou** [comment]
It works fine with following option:

```
In [1]: from tabula import convert_into

In [2]: convert_into("http://www.ndb.int/wp-content/themes/ndb/pdf/list-of-all-projects.pdf", "test.csv",lattice=True, guess=False)
```

![image](https://user-images.githubusercontent.com/916653/32299214-1e017ef8-bf98-11e7-8fe1-a897000e2fae.png)

**Comment by mayurpande** [comment]
Thanks, I seem to be having another problem.

The wrapper is not reading this pdf;

```
    url = 'http://www.nadb.org/pdfs/FreqUpdates/ProjectMatrix.pdf'

    
    df = wrapper.read_pdf(url,
            stream=True,
            pages='2',
            area=(71.28,8.415,546.48,199.48499999999999)
            )
```

It returns an empty df

**Comment by chezou** [comment]
You should create a new issue for another issue. You should try to set `guess=False`, if it doesn't work.
