### ISSUE TITLE
Warning : org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode

### ISSUE THREAD

**Issue by shafikhaan** [chezou/tabula-py#68]
# Summary of the issue

The warning pops up on the creation of csv, Basically i am reading the PDF for the extraction of text. I extract text and write it to the CSV, Its not generating any error, Its warning

The exact warning(s) is 

```
Nov 08, 2017 10:48:48 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (9) in font Helvetica
```

# Environment

Python version : `Python 2.7.13`

Java version : 

```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Java : `java -h` is working fine.

Os : `Ubuntu 17.04`

## What did you intend to be?

The warning should not pops up. The rest of the goal is achieved

**Comment by chezou** [comment]
It seems your PDF itself's problem.
https://issues.apache.org/jira/plugins/servlet/mobile#issue/PDFBOX-3296

**Comment by shafikhaan** [comment]
Thanks for the comment, That link clarifies it. @chezou

**Comment by lukehsiao** [comment]
@chezou Is there a way to silence these warnings?

**Comment by chezou** [comment]
@lukehsiao It seems your PR has already closed. What's the specific reason for handling warning? Warnings are output by PDFBox under tabula-java.

**Comment by lukehsiao** [comment]
You're right. We've decided to just keep the warnings. Thanks!

**Comment by pri1311** [comment]
Had a similar problem while working with a pdf file which had Verdana font. I converted it to word(docx) file changed the font all throughout and converted it back to pdf. worked well for me after that. It could be a good hack for small projects/ data.
