### ISSUE TITLE
Different outputs tabula-py and tabula-java

### ISSUE THREAD

**Issue by gaglians** [chezou/tabula-py#69]
Hello, 

Thank you for developing this wrapper. I have a problem with a pdf file: when I extract a table from a certain area, if I use tabula-py I get different data than what I get if I use tabula-java (I used tabula-java with subprocess in Python). With tabula-py I get the first 2 columns presented as one (so that I have mixed data), while tabula-java correctly shows them as 2 different columns. Here below you can find the commands I run, and receive 2 different results:
`df = tabula.read_pdf(1.pdf, encoding = 'ISO-8859-1',
	stream=True, area = (111.986,302.475,387.301,552.491), pages = 3)`
`df = check_output(['java', '-jar', 'tabula.jar', '1.pdf', '-p3', '-a 111.986,302.475,387.301,552.491', '-t'])`

Unfortunately I can't share the pdf for which this happens. Thank you.

Result with tabula-java (2 separate columns):
![image](https://user-images.githubusercontent.com/33005961/32975404-2f5f1ed2-cc07-11e7-8f8a-7af297f4a4b6.png)
Result with tabula-py (1 mixed column):
![image](https://user-images.githubusercontent.com/33005961/32975500-04d4bcca-cc08-11e7-8b3b-a66c6e73e9c2.png)

**Comment by chezou** [comment]
Could you set `guess=False` for tabula-py option? tabula-py handles it as true by default.

**Comment by gaglians** [comment]
Can't believe it was this simple and I lost 2 hours trying to figure out what was wrong! THANK YOU!

**Comment by chezou** [comment]
I'm sorry to hear that. I'll add this point to FAQ.
