### ISSUE TITLE
from tabula import read_pdf path=read_pdf("http://www.theicct.org/sites/default/files/publications/ICCT_Pocketbook_2016.pdf",multiple_tables=True) print(path)

### ISSUE THREAD

**Issue by SukanyaHanumanthu** [chezou/tabula-py#70]
from tabula import read_pdf
path=read_pdf("http://www.theicct.org/sites/default/files/publications/ICCT_Pocketbook_2016.pdf",multiple_tables=True)
print(path)

Tried this code to access tables in the pdf link "http://www.theicct.org/sites/default/files/publications/ICCT_Pocketbook_2016.pdf" in python 3.6.2

I get no errors with the output []

Would be great if someone can help me resolve this. 
Thanks,
Sukanya

**Comment by chezou** [comment]
Please follow the issue template.
