### ISSUE TITLE
tabula read correctly in first page tables only .it does not read correctly in the second page 

### ISSUE THREAD

**Issue by mahendranatarajan** [chezou/tabula-py#72]
Summary of your issue
Hi all,
I am using tabula -py for extracting table data's from pdf file as a json format , there it will only read the first page table only correctly if the first table continues in the second page it does not read the data's and empty spaces between the data's .how can i fix that issue ..?

Write and check your environment.

- [ Python 2.7.14] 
- [ java version "9.0.1"]
- [ ubuntu 17.10 ] 

# What did you do when you faced the problem?
I am using tabula -py for extracting table data's from pdf file as a json format , there it will only read the first page table only correctly if the first table continues in the second page it does not read the data's and empty spaces between the data's .how can i fix that issue ..?**
//write here

## Example code:
	df = tabula.read_pdf("/tmp/university_exam_results.pdf", output_format="json", pages="all", multiple_tables="True")

```
paste your core code
```

`import tabula

def readpdf():
	df = tabula.read_pdf("/tmp/university_exam_results.pdf", output_format="json", pages="all", multiple_tables="True")
	#print "Size : "+df.length
	print df
	#return 0
	page = 1
	student_subject_grade = {}
	subject_codes = []
	for entry in df:
		table_row = 1
		subject_split = False
		for row in entry['data']:
			
			# subject_split = False

			#break
			if table_row == 1:
				print page
				print table_row
				print row[1]["text"]
				print row[3]["text"]
				print len(row)
				col = 0
				pagebeginning = False
				for column in row:
					break
					if col == 0 and column['text'] == '':
						pagebeginning = True
						subject_codes = []
					elif col == 1 and column['text'] == "Subject Code - >":
						pagebeginning = True
						subject_codes = []
					if not pagebeginning:
						if col == 0:
							registration_number = column['text']
							if not registration_number in student_subject_grade:
								student_subject_grade[registration_number] = {}
						elif col == 1:
							student_name = column['text']
							student_subject_grade[registration_number]['name'] = student_name
						elif col > 1:
							student_subject_grade[registration_number][subject_codes[col-2]] = 	column['text']
					else:
						print "else"
						if col > 1:
							print "col >1"
							subject_codes.append(column['text'])
					col += 1	
			elif table_row == 2:
				print page
				print table_row
				print row[1]["text"]
				print row[3]["text"]
				print len(row)
				if pagebeginning:
					col = 0
					
					for column in row:
						break
						print col ,"col"
						
						if col == 0 and column['text'] == 'Reg. Number':
							continue
						elif col == 0 and column['text'] == '':
							subject_split = True
						elif col == 1 and column['text'] == 'Stud. Name':
							print "second name eliffffffffffff"
							continue
						elif col == 1 and column['text'] == '' and subject_split:
							print "name :::::::::::::::::::::::::::::::::::::::::::::"
							subject_split = True
						
						if subject_split and col > 1:
							subject_codes[col-2] = subject_codes[col-2] + column['text']
							
						col += 1
				else:
					col = 0
					for column in row:
						break
						print col,"col in else"
						if col == 0:
							registration_number = column['text']
							if not registration_number in student_subject_grade:
								student_subject_grade[registration_number] = {}
						elif col == 1:
]							student_name = column['text']
							student_subject_grade[registration_number]['name'] = student_name
						elif col > 1:
							student_subject_grade[registration_number][subject_codes[col-2]] = 	column['text']
						col += 1
			else:	
				print page
				print table_row
				print row[1]["text"]
				print row[3]["text"]
				print len(row)
				if pagebeginning and subject_split and table_row == 3:
					col = 0
					for column in row:
						break
						if col == 0 and column['text'] == 'Reg. Number':
							continue
						elif col == 1 and column['text'] == 'Stud. Name':
							continue
						col += 1	
				else:
					col = 0		
					for column in row:
						break
						#print col,"col nested else"
						if col == 0:
							registration_number = column['text']
							if not registration_number in student_subject_grade:
								#print "nested else if not"
								student_subject_grade[registration_number] = {}
						elif col == 1:
							student_name = column['text']
							student_subject_grade[registration_number]['name'] = student_name
						elif col > 1:						
							student_subject_grade[registration_number][subject_codes[col-2]] = 	column['text']
						col += 1					
			table_row += 1
		
		page += 1
		
	total_students = 1		
	university_performance_ids = []
	for key, details in student_subject_grade.iteritems():
		if key == '953413114041':
			
			print "---------------------------------------------------------------------------"
			print total_students, key 
			print "---------------------------------------------------------------------------"
			
			print details, "--------------------------------------------------------------------------"
		
		registration_number = key
		student_name = details['name']
		
		for k, v in details.iteritems():
			if key == '953413114041':
				print k, ":", v
			if k == 'name':				
				continue
			if v != '':				
				university_performance_ids.append((0, 0, {'registration_number': registration_number, 'student_name': student_name, 
												'subject_code': k, 'grade': v}))
				
		print "------------------------------------------------------------------------"
		
		total_students += 1
	return university_performance_ids

readpdf()

	
	

`

**Comment by chezou** [comment]
I'm sorry but could you follow the issue template, not to ignore putting outputs of environment checking codes, to put output and to write expectation? I can't continue helping without writing that information or be getting a minimal reproducible code and an example PDF.

If you want to convert a table PDF, I recommend you to use `convert_into()` function.

After extracting a dataframe from a PDF, tabula-py don't provide page info. `page` variable is in only your code.
