### ISSUE TITLE
Cannot import read_pdf_table

### ISSUE THREAD

**Issue by itssuyog96** [chezou/tabula-py#76]
# Summary
Cannot import read_pdf_table

# Environment

- [X] Paste the output of `python --version` command on your terminal: **Python 2.7.14**
- [X] Paste the output of `java -version` command on your terminal: 
**java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)**
- [X] Does `java -h` command work well - **yes**; Ensure your java command is included in `PATH` - **yes**
- [x] Write your OS and it's version: **Mac OS High Sierra Ver 10.13.3**
- [ ] (Optional, but really helpful) Your PDF URL:

# What did you do when you faced the problem?

I tried to import both **read_pdf** and **read_pdf_table**. **read_pdf_table** gave error however **read_pdf** works fine.

## Example code:

```
from tabula import read_pdf, read_pdf_table
```

## Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name read_pdf_table
```

## What did you intend to be?
How to import **read_pdf_table**. Please help.

**Comment by chezou** [comment]
`read_pdf_table` is obsolete. pleas use `read_pdf` instead.

**Comment by rahulsaxena-imd** [comment]
i have used read_pdf but same error "cannot import pdf"

**Comment by rahulsaxena-imd** [comment]
sorry it's "cannot import read_pdf"

**Comment by chezou** [comment]
@tdiam thanks for your advice, i've just updated the screenshot!

**Comment by PDA90** [comment]
I just fix error and run code to smooth . You should install 
1. pip install tabula-py
2. conda install tabula-py
3. conda install java
4. from tabula import read_pdf 
5. dt = read_pdf( 'file.pdf' , encoding = 'latin1', pages ='all', nospreadsheet = True )

**Comment by chezou** [comment]
I strongly not recommend installing tabula-py via conda since the conda-forge recipe [isn't maintained well](https://github.com/conda-forge/tabula-py-feedstock/pulls).
