### ISSUE TITLE
到处excel，表格数据有问题

### ISSUE THREAD

**Issue by xhochipe** [chezou/tabula-py#79]
python3.6 java8

[2.PDF](https://github.com/chezou/tabula-py/files/1805776/2.PDF)

data_copy = dict()
data_json = read_pdf(path, pages='all', encoding='gbk',guess=True,Lattice=True)

writer = pd.ExcelWriter('output1.xlsx')
data_json.to_excel(writer,'Sheet2')
writer.save()

出来的结果表格格式比较大

**Comment by chezou** [comment]
对不起，我不会说中文。
