### ISSUE TITLE
Columns keyword?

### ISSUE THREAD

**Issue by btyukodi** [chezou/tabula-py#8]
In the tabula-java command line utility there is a --columns option where the x-coordinates of the columns can be given. This is really useful for poorly formatted tables. Would it be possible to add it here?

**Comment by chezou** [comment]
Thanks for reporting. You can use `options` argument like `options="--columns 10.1,20.2,30.3"` directly. Anyway, I will add `columns` option.

**Comment by btyukodi** [comment]
Oh, I see. Maybe just adding an example on how to use "options" would do the job. Thanks a lot!

**Comment by chezou** [comment]
Thanks, I added example into README https://github.com/chezou/tabula-py/commit/245f2735974bd538cba54a6561d9419d54fe305a
