### ISSUE TITLE
CalledProcessError - non-zero exit

### ISSUE THREAD

**Issue by reichaves** [chezou/tabula-py#83]
Hello
On this PDF (https://drive.google.com/file/d/1P8kF0gUOVls6sOGed4R0C2PlVF5RFtU6/view?usp=sharing), I want to transform the tables on all the pages in CSV. I did so:

import pandas as pd
import tabula
tab = tabula.read_pdf("Ativos_Fevereiro_2018_servidores_rj.pdf", encoding='latin-1', spreadsheet=True, pages='all', header=0)
tab.to_csv('servidores_rj_ativos_fev_18.csv', index=False)

I got this error message: CalledProcessError: Command '['java', '-jar', '/home/reinaldo/Documentos/Code/intercept/seguranca/lib/python3.6/site-packages/tabula/tabula-1.0.1-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--lattice', 'Ativos_Fevereiro_2018_servidores_rj.pdf']' returned non-zero exit status 1. 

Please, what's wrong?
I'm using Ubuntu and Python3

**Comment by reichaves** [comment]
Hello
I came in a solution - divided into lots of 300 pages: https://github.com/reichaves/curso_knight_python_2017/blob/master/pdftocsv.py

**Comment by chezou** [comment]
I'm glad to hear you solved the problem. I guess your issue is heap size problem. You can set `java_options=["-Xmx2048g"]`. I also suggest to use `convert_into()` function instead of `read_pdf()` for converting to csv.

**Comment by mayurpande** [comment]
I am having the same problem I have tried to `convert_into` but where do I set `java_options`?

**Comment by chezou** [comment]
@mayurpande You can use java_options for convert_into as well as read_pdf. See also https://github.com/chezou/tabula-py/blob/master/tests/test_read_pdf_table.py#L46
