### ISSUE TITLE
CalledProcessError in Jupyter Notebook/Lab

### ISSUE THREAD

**Issue by mimischi** [chezou/tabula-py#86]
# Summary of your issue

Usage of `tabula-py` inside `ipython` on a shell works. Also running `java -jar /homeloc/scratch/mimischi/.conda/envs/mdtraj/lib/python3.6/site-packages/tabula/tabula-1.0.1-jar-with-dependencies.jar --pages 1 --guess page_14.pdf` works.

I does not work inside of Jupyter Notebook and JupyterLab, throwing the `CalledProcessError`.

The package and `tabula-java` seem to work in general, but it does not work with notebooks.

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [x] Paste the output of `python --version` command on your terminal:
```bash
$ python --version
Python 3.6.5 :: Anaconda, Inc.
```
- [x] Paste the output of `java -version` command on your terminal:
```bash
$ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`
- [x] Write your OS and it's version: Scientific Linux 7
- [x] (Optional, but really helpful) Your PDF URL: It's a non-open scientific paper. I probably can't share it.

### Some more version information:

```bash
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.32.0
jupyterlab-launcher==0.10.5
notebook==5.4.1
```

# What did you do when you faced the problem?

## Example code:

```
import tabula
tabula.read_pdf('page_14.pdf', java_options=['-Xmx2048g'])
tabula.convert_into('page_14.pdf', output_path='test.csv')
```

## Output:
```python
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-29-9b29b5139e99> in <module>()
----> 1 x = tabula.read_pdf('page_14.pdf', java_options=['-Xmx2048g'], encoding='utf-8')

/homeloc/scratch/mimischi/.conda/envs/mdtraj/lib/python3.6/site-packages/tabula/wrapper.py in read_pdf(input_path, output_format, encoding, java_options, pandas_options, multiple_tables, **kwargs)
     73 
     74     try:
---> 75         output = subprocess.check_output(args)
     76     finally:
     77         if is_url:

/homeloc/scratch/mimischi/.conda/envs/mdtraj/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

/homeloc/scratch/mimischi/.conda/envs/mdtraj/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    416         if check and retcode:
    417             raise CalledProcessError(retcode, process.args,
--> 418                                      output=stdout, stderr=stderr)
    419     return CompletedProcess(process.args, retcode, stdout, stderr)
    420 

CalledProcessError: Command '['java', '-Xmx2048g', '-jar', '/homeloc/scratch/mimischi/.conda/envs/mdtraj/lib/python3.6/site-packages/tabula/tabula-1.0.1-jar-with-dependencies.jar', '--pages', '1', '--guess', 'page_14.pdf']' returned non-zero exit status 1.
```

**Comment by mimischi** [comment]
Yes, running `!java -h` works without any problems.

**Comment by chezou** [comment]
Ummmm, sounds strange. I thought your java environment on Jupyter was something strange or your PDF file path is something wrong with the notebook.

Does following command work properly?

```
!ls ./page_14.pdf
```

I'll try to add more verbose error messages for debugging.

**Comment by mimischi** [comment]
Yes, I can list and access all related files. Just re-tried everything in a fresh notebook.

**Comment by chezou** [comment]
hmmm, sounds strange. OK. I'll add to put the error code from Java.

**Comment by mimischi** [comment]
I really hope I'm not missing something, but would appreciate some more verbose errors! :)

**Comment by chezou** [comment]
Added error message #87

Could you install from github as following?

```
pip install git+https://github.com/chezou/tabula-py
```

**Comment by mimischi** [comment]
This is stupid, but it works now. I do not know what happened, but uninstalling `tabula-py` and reinstalling it again seems to have solved the problem. I cannot reproduce it anymore.

Sorry for the hassle, but thank you for your responses!

**Comment by chezou** [comment]
I'm glad to hear that! Feel free to reopen if the problem will happen again.
