### ISSUE TITLE
CONVERTING SELECTED PAGES

### ISSUE THREAD

**Issue by sidmohan** [chezou/tabula-py#9]
Hello all, is there any option of converting selected pages of PDF into excel / csv? i mean to say if i want to convert only tables present on page 12 to 20 of the PDF then what option do i have? regards

**Comment by sidmohan** [comment]
request input from anyone please

**Comment by chezou** [comment]
I'm sorry but your question is completely tabula-java one. You should go and ask on tabula-java issue.
https://github.com/tabulapdf/tabula-java/issues
