### ISSUE TITLE
Tabula Java Version

### ISSUE THREAD

**Issue by vasants** [chezou/tabula-py#92]
Hi! 

Great library! Thank you.

I made some custom enhancements to tabula java to support regex headers. I want to use my compiled version against your library. I am seeing that the output returned from tabula java is 

b'TableString: technology.tabula.Rectangle[x=83.0,y=474.0,w=361.0,h=79.0,bottom=553.000000,right=444.000000]\nTableString: technology.tabula.Rectangle[x=83.0,y=564.0,w=361.0,h=48.0,bottom=612.000000,right=444.000000]\nTableString: 

Where as the jar bundled with your python package returns a json

[{"extraction_method":"stream","top":0.0,"left":0.0,"width":401.8199768066406,"height":551.3999633789062,"data":[[{"top":478.87,"left":90.0,"width":91.75,"height":6.329999923706055,"text":"Limits of Insurance"},{"top":0.0,"left":0.0,"width":0.0,"height":0.0,"text":""}],[{"top":489.25,"left":90.0,"width":79.12594604492188,"height":5.550000190734863,"text":"Each Occurrence"},

Did you customize your java jar or am I missing something? I switched to the 1.0.1 tag and am still seeing the same issue. Pls let me know!

Thanks
Vasant

**Comment by chezou** [comment]
I didn't change anything from tabula-java release version jar. It seems your application's issue.
