### ISSUE TITLE
Apache font error

### ISSUE THREAD

**Issue by saviour123** [chezou/tabula-py#99]
# Summary of your issue

Ubuntu 17.10
Python 3.6.3
Java 8

# What did you do when you faced the problem?
I wanted to convert a csv with about 500 pages with the tool. It failed with the error below. And never wrote to file.

`> tabula.read_pdf("file.pdf", output_format="json", output_path="file.json")`

## Error:

```
Jun 12, 2018 7:58:19 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font NimbusSanL-BoldItal for newcenturyschoolbook,BoldItalic
Jun 12, 2018 7:58:19 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font NimbusSanL-BoldItal for newcenturyschoolbook,BoldItalic
Jun 12, 2018 7:58:19 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font NimbusSanL-BoldItal for newcenturyschoolbook,BoldItalic
```

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
